### ISSUE TITLE
Chickens drop feathers like a crazy!

### ISSUE THREAD

**Issue by Bulldog83** [capnkirok/animaniamod#10]
### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12.2
Minecraft Forge Server 14.23.1.2608
Animania 1.4.6

Mods:
appliedenergistics2-rv5-stable-9.jar
ChinjufuMod[1.12.2]3.1.4.1.jar
CoFHCore-1.12.2-4.3.10.5-universal.jar
deepresonance-1.12-1.6.0.jar
ElecCore-1.12.2-1.8.434.jar
Futurepack+Colorization+Addon-1.0.1.jar
Futurepack-1.12.2-26.3.123.jar
mcjtylib-1.12-2.6.4.jar
Mekanism-1.12.2-9.4.3.330.jar
MekanismGenerators-1.12.2-9.4.3.330.jar
MekanismTools-1.12.2-9.4.3.330.jar
millenaire-6.2.0-beta.9.jar
RedstoneFlux-1.12-2.0.1.2-universal.jar
ThermalDynamics-1.12.2-2.3.10.4-universal.jar
ThermalExpansion-1.12.2-5.3.10.15-universal.jar
ThermalFoundation-1.12.2-2.3.10.6-universal.jar
animania-1.12.2-1.4.6.jar
AppleCore-mc1.12.2-3.1.0.jar
AppleSkin-mc1.12-1.0.9.jar
Baubles-1.12-1.5.2.jar
BetterFps-1.4.8.jar
BetterWithMods-1.12-2.0.27.jar
BiomesOPlenty-1.12.2-7.0.1.2330-universal.jar
Born+In+A+Barn+V1.8-1.12-1.0.jar
Chameleon-1.12-4.1.3.jar
[ClayWorldGen-1.1.0-1.12.0.jar
CodeChickenLib-1.12.2-3.1.5.331-universal.jar
CoFHWorld-1.12.2-1.1.1.12-universal.jar
CoralReef-2.4-1.12.2.jar
CraftingTweaks_1.12.1-8.1.6.jar
CraftStudio-1.0.0.93-mc1.12-alpha.jar
CraftTweaker2-1.12-4.1.5.jar
CreativeCore+v1.9.17+mc1.12.2.jar
CustomMobSpawner-3.11.3.jar
DrZharks MoCreatures Mod-12.0.3.jar
Ferdinand's+Flowers-1.9.3-1.12.jar
GardenStuff-1.12-2.1.1.jar
gigaherz.commons-1.12.1-0.6.4.jar
Hwyla-1.8.23-B38_1.12.jar
instantunify-1.12.2-1.1.1.jar
jei_1.12.2-4.8.5.159.jar
jeiintegration_1.12.2-1.5.1.36.jar
JustEnoughResources-1.12.2-0.8.7.41.jar
LootTableTweaker-1.12.2-1.1.13.jar
lostcities-1.12-2.0.5.jar
lostsouls-1.12-1.1.4.jar
Mantle-1.12-1.3.1.21.jar
minecolonies-universal-1.12.2-0.8.7582.jar
modtweaker-4.0.7.jar
MTLib-3.0.3.jar
natura-1.12.2-4.3.2.42.jar
naturalnetherportals-1.2.0-mc1.12.x.jar
NoMoreRecipeConflict-0.9(1.12).jar
NotEnoughIDs-1.5.4.2.jar
NotEnoughItems-1.12.2-2.4.1.233-universal.jar
paintedbiomes-1.12.2-0.5.4.jar
Placebo-1.12.2-1.3.1.jar
Plants-1.12.2-2.6.3.jar
PrimalCore-1.12.2-0.6.39.jar
RealisticTorches-1.12.2-2.1.1.jar
RebornCore-1.12.2-3.6.5.197-universal.jar
shetiphiancore-1.12.0-3.5.6.jar
Survivalist-1.12.2-2.1.4.jar
TConstruct-1.12.2-2.9.1.65.jar
TerraCore-1.12-2.1.8.jar
terraqueous-1.12.0-1.4.10.jar
Tinkers'+Addons-1.12.1-1.0.7.jar
UniDict-1.12.2-2.4.jar
WailaHarvestability-mc1.12-1.1.12.jar
WanionLib-1.12.2-1.5.jar
Wawla-1.12.2-2.5.251.jar
 WrapUp-1.12-1.1.3.jar
### Screenshots encouraged
![2018-03-06_10 12 51](https://user-images.githubusercontent.com/20737750/37019116-136b411c-2128-11e8-9265-9135f511a27a.png)

**Comment by Bulldog83** [comment]
Config option: "# Allow Animania Chickens to drop Feathers B:chickensDropFeathers=false" don't take effect.

**Comment by Deshiba** [comment]
The problem might be with another mod in your list. I'm not going to check them all.

This definately doesn't happen with just animania.

**Comment by Bulldog83** [comment]
Yes. It's not this mod... W/o Animania chickens drop feathers too. Sorry.

**Comment by capnkirok** [comment]
Good to hear. Might want to check Terraqueous....
