### ISSUE TITLE
Severe Multiplayer-LAN connection issue.

### ISSUE THREAD

**Issue by SlayerTheChikken** [capnkirok/animaniamod#102]
### Expected Behavior
Being able to join a lan or local multiplayer server from a different PC.

### Actual Behavior
Player is able to join and is then kicked after a minute. During this minute no actions do anything.
LocalHost connection works fine.

### Steps to Reproduce
Add Animania and host in a server, connect via another PC locally. Possibly does same thing via Singleplayer-LAN.

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2, Animania 1.5.1.1

Any further requested info can be provided, if you'd like an exact test environment replica my modpack has this setup in the latest version, Tekxit 3 Official.

**Comment by capnkirok** [comment]
Thanks, @Slayer5934 ... it's probably connected to the recent reports about lag.

Of course, I have the same problem just plain vanilla on my LAN, so I'll need to find a way to test.

**Comment by SlayerTheChikken** [comment]
Try direct ethernet if you can, no chance for error there since its literally connected through cable, a cheap router/switch would also work.

**Comment by SlayerTheChikken** [comment]
Any update on the issue? Pretty serious problem, I offer my services if you need help. I can test and such.

**Comment by capnkirok** [comment]
I did test this last week @Slayer5934 and had no problems. Can you try two things for me? Try turning off 'Sleep' and also put it in Ambient mode (both options found in the config). Let me know if it works then.

**Comment by SlayerTheChikken** [comment]
Will try this thanks

**Comment by capnkirok** [comment]
Any luck? I tested LAN again here on a completely new network and didn't have any issues. Just out of curiosity, what version of Forge are you on?

**Comment by SlayerTheChikken** [comment]
I wont be able to help till atleast the end of this month, i have lots going on unfortunately

**Comment by SlayerTheChikken** [comment]
It may have been an issue with my router, Im going to do some tests soon, I hope D=

**Comment by SlayerTheChikken** [comment]
I think you can close this issue, everything SEEMS to be working fine now
