### ISSUE TITLE
1.5.1.1 Crashed dedicated server

### ISSUE THREAD

**Issue by kreezxil** [capnkirok/animaniamod#103]
### Expected Behavior
not crash

### Actual Behavior
crash while encountering a hedgehog

### Steps to Reproduce
find a hedgehog

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2, 1.5.1.1, Server

### server crash report
http://paste.ubuntu.com/p/Ny4S8sktTz/

**Comment by capnkirok** [comment]
Yes, sadly, this is a known issue, see #91 and #93 recommend you don't attack the hedgehogs in the meantime.

**Comment by Tschipp** [comment]
Closing this duplicate
