### ISSUE TITLE
Mob IDs for Animania

### ISSUE THREAD

**Issue by Xorbah** [capnkirok/animaniamod#106]
Using the latest version for 1.12.2

I can't find what IDs are associated with the mobs from this mod, the spawn eggs don't show them and i'm trying to adjust the spawns using the Bad Mobs mod which requires the proper mob ID.

**Comment by Deshiba** [comment]
I did some work on journeymap compat. To summon animals I used the following commands.

/summon animania:chick_leghorn
/summon animania:rooster_leghorn
/summon animania:hen_leghorn

The mob ID is probably the same?

**Comment by Tschipp** [comment]
As @Deshiba said, those are the only mob IDs that exist. Numerical IDs don't exist since like 1.6. To find out the mob IDs, type "/summon animania:" and press tab to cycle through all available options.
