### ISSUE TITLE
[Suggestion] Config for limiting milk to only vanilla milk

### ISSUE THREAD

**Issue by Alessandro404** [capnkirok/animaniamod#107]
I'm using this mod with the mod "food funk", that makes food rot over time.

The problem is, Animania put a lot of other types of milk as placeable fluids. While cool, this completely bypass food funk functionality, as there isn't (as I know of) a way to store a tag within a fluid (the mod uses a tag for checking rot time).

As it stand, it would be very useful a config to remove every milk fluid from the mod and limit animals to only give minecraft vanilla milk.

Thank you

**Comment by Tschipp** [comment]
Unfortunately, due to the way the cheese mold is written, it requires an actual liquid to make cheese. Since vanilla milk isn't a real liquid, this would need major rewriting of the cheese mold.
Therefore, I probably won't implement this suggestion, sorry.
