### ISSUE TITLE
German translations not working in 1.5.1.1

### ISSUE THREAD

**Issue by ShuzzDE** [capnkirok/animaniamod#108]
### Expected Behavior
All texts should be german (or at least most of them)

### Actual Behavior
English text is displayed in HWYLA and everywhere else

### Steps to Reproduce
Just install the mod and change language of Minecraft to "Deutsch (Deutschland)"

### Version of Minecraft, version of Animania, Single Player or Server
MC 1.12.2 / Animania 1.5.1.1 / SSP

I noticed that the keys in the .lang file are different from the en_US one, so the german translation file has probably not been updated when the keys changed.
This will probably affect other languages, too.

**Comment by capnkirok** [comment]
Hey ShuzzDE, German hasn't been updated since the original (I just checked). If you have time, would you like to contribute? 

You can find the files here:
https://github.com/capnkirok/animaniamod/tree/1.12/src/main/resources/assets/animania/lang

You can get the English keys from the EN_en file. Let me know if you can help :)

PC

**Comment by ShuzzDE** [comment]
Hi!
I actually translated the file already. However, I'm not entirely sure that I got every single animal's name right. Some of the animal breeds do have individual german names, others do not and since I'm not really into animal farming it was... difficult to find translations.

Nevertheless, I think it would be a good start.
Should I just put the file in a pull request?

**Comment by capnkirok** [comment]
Pull request would be great! Thank you! I may ask for a review from one of my German friends.

**Comment by TobiPeterG** [comment]
Hey, I'm a native German speaker and could have a look at the translations if you'd like to.

**Comment by Tschipp** [comment]
Yes that would be very nice!

**Comment by TobiPeterG** [comment]
> Yes that would be very nice!

OK, well, do you know where the already translated file can be found or should I translate it again? O.o

**Comment by Tschipp** [comment]
You can find everything here in the source on github:
https://github.com/capnkirok/animaniamod/tree/1.12/src/main/resources/assets/animania/lang

**Comment by TobiPeterG** [comment]
I've just created a pull request with the updated translation.
I hope everything's as intended.

Have a nice day!
