### ISSUE TITLE
[Crash] Crash when drinking milk bottle, truffle soup when AppleCore is installed

### ISSUE THREAD

**Issue by Luke616** [capnkirok/animaniamod#11]
### Expected Behavior
Milk bottle, truffle soup able to be eaten normally

### Actual Behavior
When installed alongside applecore (required library for hunger in peace, hunger overhaul) the game crashes
https://pastebin.com/Eh9VVmmz

This link may be able to help
https://github.com/squeek502/AppleCore/wiki/Integrating-food-items-with-AppleCore

### Steps to Reproduce
1- Install the latest animania, applecore
2- Try to drink a milk bottle or consume truffle soup (may be other foods)

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12.2
Forge 1.12.2-14.23.2.2624
Animania 1.12.2-1.4.6
CraftStudio 1.0.0.93-mc1.12-alpha
AppleCore mc1.12.2-3.1.1

**Comment by Tschipp** [comment]
Huh, iirc we’ve had this issue before, the issue was that the item stack size was decreased before the heal was applied (i think)

**Comment by capnkirok** [comment]
AppleCore doesn’t like it if you access FoodStats directly. They really should provide error trapping if they’re going to implement this way. Thanks for the link!

**Comment by Tschipp** [comment]
I can't even join the world with AppleCore installed...

**Comment by laserlemons** [comment]
Is your Java out of date maybe? I just tried it and I can load applecore and animania just fine. I do get the truffle soup crash though.

**Comment by Tschipp** [comment]
Yeah it also works for me, just not in the dev environment...

**Comment by capnkirok** [comment]
Ok found the error. Looks like AppleCore is less forgiving about stack size than vanilla mc. Need to shrink the stack AFTER applying effects. Zero stack size results in NPE.

Fixed in next release.
