### ISSUE TITLE
Some breeds don't spawn

### ISSUE THREAD

**Issue by kuroyure** [capnkirok/animaniamod#111]
### Expected Behavior
Be able to find other variants of peacock, ferrets and frogs are nowhere to be Found and hedgehogs are realy rare, If still spawning

### Actual Behavior
The Animals quoted above seem to not spawn frequently If spawning at all, the peacock breeds i Found até limited to blue, white and charcoal and they don't drop any meat

### Steps to Reproduce
Im currently using this modpack but soon will try to find the culprit and test animania alone
https://minecraft.curseforge.com/projects/terra-bestia 
the pack was made by me but this happens in other packs too

Minecraft:1.12
Animania:1.5.11
Singleplayer

**Comment by Deshiba** [comment]
When looking at the files on CF: https://minecraft.curseforge.com/projects/terra-bestia/files/2622247 I see that you have a lot of animal spawning mods or mods that happen to spawn more mobs. Also there's a couple of terrain gen mods or mods that happen to generate structures in it as well.

It wouldn't surprise me if it's another compatibility issue with it working fine with just Animania and BoP for instance.

**Comment by kuroyure** [comment]
Yeah but i tested without some and of those animal spawning mods and It happens to work same way, now about the peacocks idk what can cause that

**Comment by kuroyure** [comment]
Also how structures affect It ?

**Comment by Tschipp** [comment]
All animals are spawning. if there is space in the passive mob limit. If you have many mods that add mobs, they all increase the passive mob cap and don't allow more mobs to spawn.

**Comment by kuroyure** [comment]
Should i remove some of those mods then ?

**Comment by kuroyure** [comment]
Also that still not solves peacock problems

**Comment by capnkirok** [comment]
Or just curb some of their spawns, if possible. Peacocks only spawn in Jungles and Swamps. Have you tried upping the spawn percentage in the config for Peacocks? 

Also in the next update, you can choose the biomes in which all animals spawn.

**Comment by kuroyure** [comment]
I mean their drops, they don't Drop their meat

**Comment by Tschipp** [comment]
Closing this, it has been proven time and time again that all breeds are spawning.
