### ISSUE TITLE
Book of Fauna

### ISSUE THREAD

**Issue by Tschipp** [capnkirok/animaniamod#113]
_From @Deshiba on April 24, 2017 8:12_

It would be nice to add a book of life/fauna with fixed pages that uncover when you discover. A book that tracks the different animals and species you've found and gets filled with information the more you find out about that animal. Think bits and bobs of info like favorite food, habitat, special drops.

This would promote exploration for the adventurers and tickle the completionists among us. Though it might be too much work to implement.

_Copied from original issue: capnkirok/animania#121_

**Comment by Tschipp** [comment]
I like this idea, kind of like the lexica botania. I'm not sure how much work it would be though @capnkirok

**Comment by Tschipp** [comment]
_From @capnkirok on April 25, 2017 4:59_

@Deshiba this is great idea! It would add a nice new dimension to the mod. It's not a small piece of work, so it will take some time. And we need to get some new animals in first (horses, goats, falcons).

**Comment by Tschipp** [comment]
_From @darthvader45 on June 14, 2017 11:2_

I'd be tickled pink if the goats were anything like the Mo' Creatures goats in behavior (generally eat anything, don't leave em too close to your drops when you die, that sort of thing).

**Comment by Tschipp** [comment]
Seeing as how big the mod has become, an in-game wiki seems like a smart idea

**Comment by darthvader45** [comment]
Agreed.
