### ISSUE TITLE
[Suggestion] Modded seed compatibility

### ISSUE THREAD

**Issue by Tschipp** [capnkirok/animaniamod#132]
_From @mmelvin0 on December 7, 2017 5:13_

I realize this is low-priority, but I didn't see an open or closed issue for this...

I was going to try and write a quick mod to make BWM hemp seeds placeable, but I took a look and saw that vanilla seeds are hardcoded in at least three spots so I gave up.

It may not be worth it to make it work (e.g. dynamic textures) but just figure there's a lot of mod seeds and it would be a nice to have integration at some point in the future.

_Copied from original issue: capnkirok/animania#472_

**Comment by Tschipp** [comment]
_From @capnkirok on December 11, 2017 16:58_

Yeah, it's a good idea. I think we could add this to the config / seed placement code at some point.

**Comment by Tschipp** [comment]
While vanilla seeds can be placed on the floor, the config can be edited to allow other seeds to be placed in the trough.

**Comment by grundyboy34** [comment]
Just wondering, could we have another config to place modded seeds on the ground? If not another config, could even make it so that all foods for animals that can eat from the ground, can then be placed on the ground.

**Comment by Tschipp** [comment]
Not something that we're currently planning on.
