### ISSUE TITLE
[1.12.2] Horses disappear/teleport vast distances after being ridden on servers

### ISSUE THREAD

**Issue by Tschipp** [capnkirok/animaniamod#135]
_From @Whiskey-Sunshine on December 28, 2017 0:39_

### Expected Behavior
Horses stay where they were when dismounted (Both Animania draft horses and vanilla Minecraft horses)

### Actual Behavior
Horses teleport in the direction you initially came from when being ridden for distances over 100m (Only caught this twice, they move absurdly fast, only on screen moving far into the distance ala enderman teleporting for 2-3 frames), or just outright disappear. Can rarely be found back where they were first mounted or spawned but not always. For example, white horse in saddle and diamond armor, rode from one location to another, disappeared when dismounted. Went back to the previous location and found the horse, still in saddle and armor, wandering around roughly where it had first spawned in the world. Also occurred with Animania draft horses several times (Named horses disappear, later found back where they were mounted or first spawned, again).

### Steps to Reproduce
Ride a horse on a server more than 100m and dismount. Could be even shorter distances. The longer you ride and the faster the horse, the more likely it is to happen.

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12.2, Animania 1.4.3, Forge server 1.12.2-14.23.1.2560

### Screenshots encouraged
Hard to get screenshots when the horse is there, and suddenly not.

_Copied from original issue: capnkirok/animania#492_

**Comment by Tschipp** [comment]
_From @capnkirok on January 7, 2018 10:30_

Weeeiird. Thanks for the report.

Sounds like a Server / Client desync.

**Comment by Tschipp** [comment]
_From @olsonea on January 11, 2018 14:22_

I can confirm this in vanilla 1.12.2.

**Comment by Tschipp** [comment]
_From @capnkirok on January 12, 2018 13:33_

@olsonea wait... are you saying this is a Vanilla MC issue?

**Comment by Tschipp** [comment]
_From @ghost on January 15, 2018 7:32_

I've ridden a few draft-horses over long distances, only to turn around after dismounting and notice they have 'disappeared'.
Often they will just immediately start walking back along the route you took, sideways, towards their mounting point (sometimes they'll stop 2~5 chunks away, view distance depending, sometimes they'll go all the way home) and randomly become invisible, approaching them seems to render them visible again, if you can remember which direction to look for them.
Easily testable with a super flat map in single-player.

Note: Not having this behavior without Animania installed, Vanilla +/-FML or otherwise.

**Comment by Tschipp** [comment]
_From @capnkirok on January 15, 2018 10:4_

Thanks @Draylynn for the repro steps.

**Comment by Tschipp** [comment]
_From @olsonea on January 15, 2018 14:29_

Yes, I am saying this is a Vanilla MC issue.

I have noticed that the horses will sometimes reappear if I exit the world,
and reload it.

**Comment by Tschipp** [comment]
_From @capnkirok on January 15, 2018 20:15_

Ok, so re-reading the above, I can now explain why the horses immediately head back to their starting point... and also could explain the 'teleportation' issue. It would also explain similar behavior in vanilla.

When a horse (or any animal) is being ridden, the AI continues to execute (I just verified this). That means they they get cues to 'wander' or do whatever while they are being ridden. The paths are then set into the animal, but ignored because the animal has a 'rider'. When dismounted, the animal immediately tries to execute the older instructions... wandering back to some older coordinates. The server may intervene at some point... seeing the huge gap between the current location and the AI set location and compensate by teleporting... or just give up when the AI timer runs its course.

I've implemented some code in the development version that disables the AI when the horse is being ridden. This prevents any instructions coming in. Once dismounted, the AI is then re-enabled and all is back to normal. 

This won't fix vanilla, but it will fix the Animania horses.

**Comment by Tschipp** [comment]
_From @ghost on February 27, 2018 12:35_

Just a note, I'm still noticing this behavior on 1.4.6. Just got off my draft stallion, turned around, fwoosh, gone.

**Comment by Tschipp** [comment]
_From @capnkirok on March 17, 2018 8:46_

Ok, thanks.

**Comment by Tschipp** [comment]
_From @JkHowling on April 11, 2018 20:25_

Just happened to me with a donkey with ALL MY STUFF ON IT. I dismounted to check out an igloo and poof went the donkey with all my loot :'D

**Comment by Tschipp** [comment]
_From @capnkirok on April 12, 2018 8:23_

Well, unfortunately, @JkHowling that means this is a vanilla MC problem (which someone else said above), and since we extend the vanilla horse, it appears we inherited it on Animania. Will complain to Mojang, see if there's any progress...

**Comment by Tschipp** [comment]
Is this still an issue?

**Comment by capnkirok** [comment]
Yes, it still happens. It just happened to me while playing vanilla.

**Comment by Tschipp** [comment]
Well if it happens in vanilla, then it’s not our issue to fix  ¯\__(ツ)__/¯

**Comment by bluemonkmn** [comment]
I just saw my horse disappear after dismounting it in vanilla 1.14.2 and Google brought me here when I tried to look up the explanation.

**Comment by Vyniboy** [comment]
I can hear the noises my horse makes but I can't find it.Is it possible he is underground?
