### ISSUE TITLE
Add a Revert option, to convert animals back

### ISSUE THREAD

**Issue by Tschipp** [capnkirok/animaniamod#140]
_From @Nikola135 on January 24, 2018 21:46_

I just want to know how to safely remove Animania. My friend gave me this server with this mod on it, but if I remove this mod by deleting it, all animals disappear. In config I saw that he replaced all vanilla animals with Animania animals.
Is there a way to revers this process and how?

_Copied from original issue: capnkirok/animania#530_

**Comment by Tschipp** [comment]
_From @capnkirok on January 24, 2018 22:20_

Well, you can safely remove animania at any time. However, it will take a very long time for vanilla animals to respawn naturally (and light will have to be > 9). 

Your best bet is to introduce new animals manually. I could add a reverse engineering option, might be a good idea. That way if you turn off 'replace' it converts the original back to vanilla.

Can I ask why you are removing Animania?

**Comment by Tschipp** [comment]
_From @Nikola135 on January 24, 2018 22:43_

Thank you for fast response.

Well, my girlfriend that plays it. She likes more old sheep. I probably wouldn't have to remove it if only sheep could be vanilla. But she does like everything else.

I have been looking into writing a command that will do that, but i don't have time to learn how mc code works, but from what I could find so far, I should be executing something like this:

/execute @e[type=animania:sheep_dorper] ~ ~ ~ summon sheep ~ ~ ~, /kill @e[type=animania:sheep_dorper]
and replace dorper with:
dorper
dorset
friesian
merino
jacob
suffolk

If this will do the job over whole server (even in parts that are not loaded), then as far as I am concerned you do not have to implement that fix, although it would be nice, just fix my code/say right way to do it.

But in any case, only reason I tend to not use mods at all is because it is almost always server killing to remove them.

**Comment by Tschipp** [comment]
_From @capnkirok on January 25, 2018 18:23_

Your plan will work. Make sure you turn off Animania Sheep spawning and Replace Vanilla Sheep in the config first, otherwise it will keep happening :)

I will add this 'revert' option into our suggestions list. Let me know how it goes!

**Comment by Tschipp** [comment]
Yeah so the plan is a command, probably like /convertanimals that kills all animania animals and replaces them with the vanilla (only in loaded chunks though)

**Comment by Nikola135** [comment]
Hi.

It's nice to see this is going to be implemented.

If I find what code I used to revert sheep, I'll paste it here to help you and others. But it was a bit long time ago.

Thank you.
