### ISSUE TITLE
Edible Truffles

### ISSUE THREAD

**Issue by Tschipp** [capnkirok/animaniamod#145]
_From @Deshiba on February 15, 2018 21:44_

### Expected Behavior
Truffles to be edible in raw form

### Actual Behavior
Truffles can't be eaten raw

### Additional Info
Most truffle species [can be eaten raw](https://en.wikipedia.org/wiki/Truffle#Culinary_use). It would be justified to be able to eat them in the game as well.

 

_Copied from original issue: capnkirok/animania#566_

**Comment by capnkirok** [comment]
Added in next release
