### ISSUE TITLE
[Suggestion] JourneyMap compatibility

### ISSUE THREAD

**Issue by Tschipp** [capnkirok/animaniamod#147]
_From @DeymorSalk on February 20, 2018 20:2_

Animals do not appear on the map.
--------------------------------------
Os animais não aparecem no mapa. 

_Copied from original issue: capnkirok/animania#573_

**Comment by Tschipp** [comment]
_From @MauveCloud on February 20, 2018 21:3_

Are you sure about that?  I've had them appear on JourneyMap, but they get generic dots even if I set JourneyMap to use small/large icons, and that can be changed: https://journeymap.info/Custom_Mob_Icon_Sets

**Comment by Tschipp** [comment]
_From @Deshiba on February 20, 2018 21:48_

I Don't think there are custom Icons yet. Maybe making them and adding journeyMap support  could be a thing.

It'd also be nice to have for the wiki

**Comment by Tschipp** [comment]
_From @capnkirok on February 20, 2018 23:44_

Custom Journey Map icons would be nice @DeymorSalk :)

**Comment by Tschipp** [comment]
_From @Deshiba on February 21, 2018 15:49_

Extra info, these have been requested before in #155

**Comment by Tschipp** [comment]
_From @capnkirok on February 22, 2018 18:13_

Never hurts to ask again :)

**Comment by Tschipp** [comment]
_From @Deshiba on March 14, 2018 7:2_

Working on the icons now. Pigs are done, at this rate ETA should be 3 to 10 days

**Comment by TheSexyYeti** [comment]
Any update on those JourneyMap Icons?. I really wanna use the Animania Mod but not if there aren't any JourneyMap Icons.

**Comment by Deshiba** [comment]
The icons are partially made as seen on http://www.animaniamod.net/index.php/Template:Animal
As you can see in this table, the frogs aren't up to par and there's no icons for Sheep and Rabbits yet.

Once those are in it's a matter of making a PR and having the devs aprove. I don't want to give an ETA because I haven't kept the last one and my interests tend to waver from time to time.
