### ISSUE TITLE
Hamsters disappear when put down

### ISSUE THREAD

**Issue by Tschipp** [capnkirok/animaniamod#164]
_From @littlebear22 on August 29, 2018 17:43_

### Expected Behavior
Shift right click with hamster on shoulder, and hamster will go from shoulder to ground, making an adorable popping sound.

### Actual Behavior
Shift right click with hamster on shoulder, and hamster makes the pop noise, but disappears instead of showing up on the block I'm aiming at.

### Steps to Reproduce
Shift right click on a block to place a hamster while standing in or near tall grass.

I "think" that it has to do with tall grass.  The block I'm aiming at is bare (no grass) but the block I'm standing on or maybe just near has tall grass on it.  I think the tall grass blocks the placement of the hamster.  Happened 3 times in a survival world.   RIP :(  I don't want to send more hamsters to the void to test more in this world.  I did look on Journeymap to see if maybe they popped down into an underground cave or something, but didn't see them.  

So, to be clear, I've been able to place the hamsters correctly before in the same world.  But 3 times now when I was trying to place them, they stopped existing.  I'm not positive what the issue is, the only difference I see when I successfully place them and I don't, is tall grass.

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2 Minecraft.  Animania is 1.5.1.1.  Single player.  I added Animania to All The Mods 3, v.5.9.8d.

### Screenshots encouraged
No more hamsters to show screenshots of.  :(

(Hope I did this right, this is my first time on github.  Please feel free to kindly correct any mistakes.)

_Copied from original issue: capnkirok/animania#636_

**Comment by Tschipp** [comment]
_From @capnkirok on August 30, 2018 9:10_

Weird....! Haven't seen this one before in Single Player. I've seen it happen in multi-player after a shoulder ride where the render seems to fail. Will take a peek.

**Comment by Tschipp** [comment]
_From @Deshiba on August 30, 2018 12:38_

In multiplayer a relog fixes the issue. I wonder if the entity actually still exists and is invisible or if it is completely gone.

**Comment by Tschipp** [comment]
_From @littlebear22 on August 31, 2018 20:39_

If it helps, I have logged in and out of that game a couple of times since then.  Still no sign of my little hamster friends.  Since they're small and hard to see, I used journey map too, and looked for the blue "pet" icons on the map that were there before they disappeared.  I did not see anything.   I'd have to assume they're all just gone.  But if there's a command that I can run to ask the game how many pets I have, maybe that would help determine once and for all if they are just not rendering or if they really no longer exist?

**Comment by Syrious** [comment]
I can confirm this bug, which only appears when playing on a remote server. Sometimes the hamster gets placed on the ground and sometimes it just vanishes. After a couple of minutes the hamster reappears on an older spot where I placed it down.

The block you place the hamster doesn't seem the problem though. It tried planks, grass, dirt, stone. And it only happens after the second or third try.

**Comment by GuptaChinmay234** [comment]
This bug was on iskall85's latest video
