### ISSUE TITLE
Animals don't spawn in old chunks

### ISSUE THREAD

**Issue by Tschipp** [capnkirok/animaniamod#167]
Animals should spawn in old chunks
Animals are not spawning in old chunks. So they are not replacing completely the Vanilla mobs
Steps to Reproduce
1.10.2 Single Player
Screenshots encouraged
 
**capnkirok commented on 8 Apr**
Hey @MrFarrelll yeah, if you add Animania to an existing world they won't spawn in the old areas. Is that what you are saying is going on with you?

 
**Marfjeh commented on 7 Jul •** 
i can say this happend to me to an existing world, it removed all the vanilla mobs instead replacing them. so every animal in the world is gone. (what is enabled in the config)

**capnkirok commented on 7 Jul**
Yes, I see the problem. Animania used to replace animals in old chunks but that led to overspwaning. Now it removes them without replacing, leaving the world barren. Need to fix this for existing worlds. Thanks, both.

 
**Deshiba commented on 8 Jul**
@capnkirok On a similar note. If you have animania installed and remove it for some reason, all animals will despawn and vanilla animals take a while to respawn in old chunks.

Would there be a way to replace animania animals with vanilla ones when animania is removed?

 
**Marfjeh commented on 8 Jul •** 
@capnkirok On a similar note. If you have animania installed and remove it for some reason, all animals >will despawn and vanilla animals take a while to respawn in old chunks.

Would there be a way to replace animania animals with vanilla ones when animania is removed?

The way forge and minecraft works in my understanding, if it cannot find the entity and or block it will just silently remove them. and there is no way to replace them back to vanilla animales. Or what you can do is maybe that they are still registered as a vanilla mob, but problem is you probably need to rewrite the mod i'm afraid for that.

Yes, I see the problem. Animania used to replace animals in old chunks but that led to overspwaning. Now it removes them without replacing, leaving the world barren. Need to fix this for existing worlds. Thanks, both.

Awesome. because i'm playing my modpack and wanted to install this mod, it just removed all the mobs D: and it doesnt seem they respawn, but i havent checked everywhere. My world is pre-generated for around 1000 chunks x 1000 chunks. and if players doesnt want to replace to mobs, they can just disable it in the config.

**capnkirok commented on 8 Jul**
One way to do this would be through commands. Was thinking of the following:

Spawn Animania animals (in an existing world)
Replace vanilla animals with Animania versions
Remove Animania animals of type X
Replace Animania animals with vanilla versions
Reduce Animania animal of type X by X percent (or something)
 
**Marfjeh commented on 8 Jul**
that would be awesome. so i can add animania to my existing world :D

 
**Crowfooted commented 21 days ago**
Is this still an issue with Animania? Is it because animals only spawn when the chunk generates, or is it something to do with the chunk itself?

 
**Marfjeh commented 21 days ago**
Every existing vanilla mob gets purged and it doesnt get replaced with animania mobs. but i do not know that they fixed it.

 
**capnkirok commented 19 days ago**
In the latest version, there's now a small chance that a vanilla animal will be replaced with Animania even in existing chunks. I have to be very careful about this due to overspawning (there are so many checks and balances right now).

But the new commands are not in yet.

**Comment by V10lator** [comment]
Could a possible fix for this be to add a capability ( https://mcforge.readthedocs.io/en/latest/datastorage/capabilities/ ) to a chunk when it gets created/populated, then check for it when the chunk loads and if the capability is not there spawn animals (and ofc. set the tag, so basically have a function to spawn the animals and set the tag for a chunk which gets called from the chunk generation/population event as well as the chunk load event if tag is not there) ?

**Comment by Tschipp** [comment]
Closing this as this is how vanilla works as well
