### ISSUE TITLE
[Suggestion]Placeable horse cart chest

### ISSUE THREAD

**Issue by Tschipp** [capnkirok/animaniamod#169]
mser7 commented on 1 Sep
I want the chest on the horse cart to have a placeable variant that is separated with the vanilla chest
https://cdn.discordapp.com/attachments/465429280076333057/482132549691244552/2018-08-23_17.11.50.png

**capnkirok commented on 2 Sep**
I would have to make my own chest for this to work. While this is possible, I am not sure of the benefits, other than for aesthetic reasons. Will leave this on here as a suggestion.

**Comment by capnkirok** [comment]
I've decided against this one.

**Comment by mser7** [comment]
Perhap you can make the horse cart chest look like the vanilla chest instead?
