### ISSUE TITLE
[Suggestion] Add config option to disable food in dungeon chests.

### ISSUE THREAD

**Issue by laserlemons** [capnkirok/animaniamod#17]
In my modpack it doesn't make much sense to find a bunch of cooked steak in dungeon chests. Would you mind adding a config option to disable it?

**Comment by Tschipp** [comment]
That is definitely not from us, what other mods are you using?

**Comment by laserlemons** [comment]
Oh, weird! I'll do more testing and see if I can figure out which mod is doing it. All the dungeon chests are full of an assortment of Animania foods so this is the first mod I suspected.

**Comment by laserlemons** [comment]
I found it! My apologies, it turned out to be Hunger Overhaul. In their config they have an option to include Harvestcraft food in dungeon chests and it looks like it does it for this mod too.

**Comment by capnkirok** [comment]
Hunger Overhaul pulls from OreDictionary... all of Animania meats are listed there and share  Harvestcraft's lists. Full list is here: https://github.com/capnkirok/animaniamod/blob/60b4598f0e37bedec695db110053315d3c074f4a/src/main/java/com/animania/common/handler/DictionaryHandler.java
