### ISSUE TITLE
Fire escape does not trigger in Sleep Mode

### ISSUE THREAD

**Issue by DrunkBlood** [capnkirok/animaniamod#172]
### Expected Behavior
Animals run away(aimless) when they are on fire

### Actual Behavior
Animals stay sleeping although being burnt alive

### Steps to Reproduce
1. Get Animals to sleep
2. Set a FireBlock (also by Flint & Steal) under them
3. Watch

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2; 1.5.1.1 ; SG with LAN as host

**Comment by capnkirok** [comment]
Oops. Yeah, they react when attacked... but not from fire... thanks.

**Comment by capnkirok** [comment]
Actually, it looks like this has nothing to do with sleep. They wake up, but they don't run. And they don't run away when they are awake either.

**Comment by capnkirok** [comment]
Ok this is fixed in the next release.

**Comment by mser7** [comment]
Would this fix the Ice and Fire runaway behavior issue?
