### ISSUE TITLE
Get a lot of error messages when I start my Forge Server

### ISSUE THREAD

**Issue by djdanby** [capnkirok/animaniamod#173]
I get a lot of error messages when I start my Forge Server. Whether this error message affects the server I do not know. But I wanted to report it anyway, if relevant.
If further information is needed, please answer here. The log file is very long, so I copied the most relevant lines to get the overview.

### Steps to Reproduce
I starting my server

### Version of Minecraft, version of Animania, Single Player or Server
Linux Server
Minecraft 1.12.2 
Forge-1.12.2-14.23.5.2768

Log File: https://pastebin.com/ZnKaXgME

**Comment by Tschipp** [comment]
This is intended, those are just warnings
