### ISSUE TITLE
Suggestion: Config option to have spider and cave spider attack small animals

### ISSUE THREAD

**Issue by mser7** [capnkirok/animaniamod#175]
It would make sense that giant spider hunt weak and small animals, like pigs, goats, sheeps and critters. This create another challenge for players to build extra protection for their animals

**Comment by Deshiba** [comment]
Spiders aren't regular farm animals, I think this is out of scope for this mod. But hold on till the devs reply.

**Comment by mser7** [comment]
Minecraft spiders, fantasy monsters that hunt even a human, will definately enjoy gnawling on some baby meat. This is another challenge, if you feel like only tending to animals boring.
