### ISSUE TITLE
cart detaching

### ISSUE THREAD

**Issue by njtxus** [capnkirok/animaniamod#179]
### Expected Behavior
cart staying linked

### Actual Behavior
cart or wagon becomes detached very easily and with no obstacles in way. tried on flat road and detaches at around the same point each time. again with nothing in the way and no difference on terrain.

### Steps to Reproduce
pull a cart or wagon a fair distance.

### Version of Minecraft, version of Animania, Single Player or Server
12.2 single player

**Comment by capnkirok** [comment]
Question, what version of Animania are you running?

**Comment by njtxus** [comment]
apologies. i should have stated 1.5.11 is the version

**Comment by capnkirok** [comment]
Thanks for the follow up. I had made some changes in the previous version to combat this, but it sounds like there are still issues. I will take another look.

**Comment by Tschipp** [comment]
Is this still an issue?

**Comment by njtxus** [comment]
yes it is still very easy to lose the wagons. i tried it with askitor (another cart mod) to see if it did the same but it stays attached fine. it's like it's just to sensitive. maybe allowing a bit of rubberbanding could work. thanks!
