### ISSUE TITLE
Animals cause tons of server lag

### ISSUE THREAD

**Issue by LunixNovalis** [capnkirok/animaniamod#18]
### Expected Behavior
Not to lag?

### Actual Behavior
Having at least 2 of each animal causes my server to have less than 13 tps after a few minutes of gameplay. I removed the animals and server tps was at 20.

### Steps to Reproduce
Have 2 or more of each animal.

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12.2
Animania 1.4.6
Server

### Screenshots encouraged
Before removing animals:
![2018-03-12_05 37 34](https://user-images.githubusercontent.com/32338780/37276472-27a834ac-25b8-11e8-9eb0-4ecb0020a9f9.png)
After removing animals:
![2018-03-12_05 41 02](https://user-images.githubusercontent.com/32338780/37276474-28058986-25b8-11e8-9991-21c5a1e4dda4.png)

**Comment by Tschipp** [comment]
What Animania Version are you using? What version of Minecraft is this?

**Comment by LunixNovalis** [comment]
Sorry about that. Don't know why I forgot that info.

Minecraft Version 1.12.2
Animania Version 1.4.6

**Comment by Tschipp** [comment]
Hmm... not sure about this. On the Animania Server we have many more Animals without any problems. How good is your server usually?

**Comment by Deshiba** [comment]
I also see different dogs in the first image, what mod are those from? Are you sure those don't cause the problem?

**Comment by LunixNovalis** [comment]
The wolves are from Sophisticated Wolves. I don't think the wolves caused too much lag, but I'll test it out again with them still there and without to see.
The server runs pretty good, although its not the best. I use a BisectHosting server with 6gb of RAM. The only people to play on it are my brother and I.

**Comment by LunixNovalis** [comment]
Tested it again without the wolves. With Animania Animals it got down to 12 tps. As soon as I killed them it went back to 20 tps.
![2018-03-12_21 35 39](https://user-images.githubusercontent.com/32338780/37317911-e4dcac3a-263d-11e8-88a0-0451c0b8bd93.png)

**Comment by Deshiba** [comment]
Weird, we're not having this issue on our server...

**Comment by laserlemons** [comment]
Could it have something to do with the area that they're in? Maybe a pathfinding bug or something like that? We've got a server that runs on 3GB RAM and have zero lag issues with the animals.

**Comment by capnkirok** [comment]
Not able to reproduce your issue, so going to ask more questions:

More questions:
- What is your entity count? Can you take a screenshot with the Debug Screen visible?
- Do you happen to have any animals stuck in water (like a large lake) nearby?
- What happens if you remove your fences (as an experiment)? Does the TPS reduce?

**Comment by capnkirok** [comment]
I've changed pathing again so the animal must be able to path to the item or entity it is looking for, instead of getting stuck in a loop until the timer expires. There was also a bug in the Trough Render that was causing serious lag.
