### ISSUE TITLE
Rabbits don't attack when I attack them (Animation fine but no dmg)

### ISSUE THREAD

**Issue by Malrama** [capnkirok/animaniamod#182]
Hello :3

I just build this mod with the last commit you did 5 hours ago, "Manual Update and Sweep" and everything is fine so far except one thing:

Once you attack a Rabbit, it starts to follow you and play some attacking animations (like jumping left and right) but it deals no dmg. Now, I am not sure if it is a bug or if you just haven't implemented it yet nor if you have the intention to do so. But it looks like the rabbit should attack you, otherwise the animations don't make any sense.

Anyway, I just wanted to inform you about it :)

Greetings.

**Comment by capnkirok** [comment]
Haven't finished testing the release yet, but thanks for the heads up. Rabbits are not supposed to attack.

**Comment by capnkirok** [comment]
Fixed
