### ISSUE TITLE
[SUGGESTION] Cross-mod compat with rustic for beehives

### ISSUE THREAD

**Issue by Sunconure11** [capnkirok/animaniamod#183]
Both add their own apiary mechanics, as well as products made from them. Would it be possible to add some support for the two mods together?

**Comment by Malrama** [comment]
I endorse this! :3 It would be really cool

**Comment by Tschipp** [comment]
What kind of compat are we talking about?

**Comment by Sunconure11** [comment]
For starters, both add a honey fluid.

**Comment by Deshiba** [comment]
@Tschipp I think he means oreDict compat. Both Erebus and Rustic use the Forestry name for.honey for the fluid and dropHoney for honey drop. Source:

https://github.com/the-realest-stu/Rustic/issues/62
https://github.com/ForestryMC/ForestryMC/issues/831

@Sunconure11 If you meant something else it helps being as specific as you can. You're being vague.

**Comment by Sunconure11** [comment]
Rustic honey can be made into mead, for one thing. Rustic apiaries also grow plants around them a bit, and require bees in the form of items.

**Comment by Deshiba** [comment]
OreDict should be sufficient for Rustic to use the Animania Honey for mead.
The Rustic apiaries are their own mechanic that provide their own bee item, I see no need for Animania to provide any sort of support for this as there is no interaction between the two different bees...

**Comment by Tschipp** [comment]
I agree. We can do oredict.

**Comment by Pentasis** [comment]
I just noticed that the animania honey seems to overwrite the rustic honey. At least the rustic mead cannot be made if animania is present.

**Comment by Tschipp** [comment]
@EvertX how? Animania's (fluid) honey name is "animania_honey". I can't imagine how that would override rustic honey.

**Comment by Tschipp** [comment]
But oredict has been added.

**Comment by Deshiba** [comment]
Mangoose said that rustic checks for a fluid that has the name honey. I wouldn't know where the exact issue would be. Digging in code I barely understand is not recommended :D
