### ISSUE TITLE
Server Crash: Entity Tick

### ISSUE THREAD

**Issue by Zarl21** [capnkirok/animaniamod#185]
### Expected Behavior
Not crashing

### Actual Behavior
Crashing

### Steps to Reproduce
Unclear. For now I've restarted the server, will keep this issue report updated if it happens again. From the crash report it appears to have been caused by trying to tick a hedgehog and running into a null pointer somewhere along the way. Possibly it despawned? Neither of my players online at the time were doing anything with a hedgehog so we're not sure how to reproduce it.

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2, 1.5.11, Server

### Screenshots encouraged
[crash-2018-10-29_17.42.05-server.txt](https://github.com/capnkirok/animaniamod/files/2527299/crash-2018-10-29_17.42.05-server.txt)

**Comment by Tschipp** [comment]
Please update to the latest version.
