### ISSUE TITLE
Game Continues to Crash 1.6.0.1

### ISSUE THREAD

**Issue by satoboom** [capnkirok/animaniamod#186]
### Expected Behavior
Opening new game and it operates fine

### Actual Behavior
The game crashes after a second of opening a new world

### Steps to Reproduce
I created a new world and the game crashed

### Version of Minecraft, version of Animania, Single Player or Server
1.6.0.1, singleplayer

> The game crashed whilst rendering entity in world
> Error: java.lang.NoClassDefFoundError: com/animania/common/entities/AnimaniaAnimal

**Comment by capnkirok** [comment]
Can you post the full error, or link to it in pastebin? Can't tell what the issue is without the error log.

**Comment by capnkirok** [comment]
I got the full error in my email. Looks like a conflict with Wurmcraft, where it's trying to display something that doesn't exist. Would recommend you contact that author and send the full error.

**Comment by satoboom** [comment]
> I got the full error in my email. Looks like a conflict with Wurmcraft, where it's trying to display something that doesn't exist. Would recommend you contact that author and send the full error.

Oh okay. Um, what author are you referring to?

**Comment by capnkirok** [comment]
Wurmcraft....

**Comment by Tschipp** [comment]
Yeah, we moved an renamed that interface from `com/animania/common/entities/AnimaniaAnimal` to `com.animania.common.entities.interfaces.IAnimaniaAnimal`
