### ISSUE TITLE
Opening Manual in Akashic Tome Turns Akashic Tome into Animania Manual

### ISSUE THREAD

**Issue by DrakoAlcarus** [capnkirok/animaniamod#188]
### Expected Behavior
To open book in Akashic Tome and have all other books still be available

### Actual Behavior
Deletes Akashic tome and leaves it only as Animania manual after opening book. Punching the air does not reset the book, and it's as it's base item.

### Steps to Reproduce
1. Install Akashic Tome
2. Craft Animania manual with Akashic Tome
3. Select book and exit after book is opened

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12.2
Animania 1.6

### Screenshots encouraged
![2018-10-30_01 03 03](https://user-images.githubusercontent.com/12781728/47704878-487c5600-dbe2-11e8-8b82-048cb7a41485.png)
![2018-10-30_01 03 07](https://user-images.githubusercontent.com/12781728/47704881-487c5600-dbe2-11e8-8c67-0b861818c671.png)
![2018-10-30_01 03 26](https://user-images.githubusercontent.com/12781728/47704882-487c5600-dbe2-11e8-99ef-2b6416153d20.png)
![2018-10-30_01 03 38](https://user-images.githubusercontent.com/12781728/47704883-487c5600-dbe2-11e8-97f2-b4eac4bf472a.png)

Might be akashic tome as well, but has no issues with anything else, and no error is logged. So this is here for now.

**Comment by Tschipp** [comment]
This is probably animania, hadn‘t planned for the akashik tome

**Comment by DrakoAlcarus** [comment]
That's fair. Really loving the mod. Almost too much. Thanks for your hard work and great models.

**Comment by Tschipp** [comment]
Was a simple bug to fix, fixed in next release (can't say when that will come though)

**Comment by DrakoAlcarus** [comment]
On another note, my trough has charcoal in it: 
![2018-10-30_04 05 07](https://user-images.githubusercontent.com/12781728/47714080-1c200400-dbf9-11e8-9414-6ee11d861398.png)

Same version and I just poured water into it. Nothing else. Would you like me to make a new issue for this?

**Comment by Tschipp** [comment]
Yes please, it has already been reported, but not here on github

**Comment by DrakoAlcarus** [comment]
Will do what I can tomorrow. It's a bit late for me.

**Comment by Tschipp** [comment]
Alright I'll do it

**Comment by DrakoAlcarus** [comment]
Sorry, m8. I should have done it earlier.

**Comment by Tschipp** [comment]
No worries
