### ISSUE TITLE
Dorper Ram Spawn Uncontrollably

### ISSUE THREAD

**Issue by SnackMix** [capnkirok/animaniamod#19]
### Expected Behavior
Some Dorper Ram here and there.

### Actual Behavior
**DORPER RAM EVERYWHERE**.
They are eating grass or something and breeding uncontrollably.
There's about 200 Dorper Ram in one chunk.

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12.2, 1.4.6, Server

**Comment by Tschipp** [comment]
See, this is currently *not* unintended... we are looking into a possibility to add a breeding limit, so things like this don't happen. Especially since you're playing on a server, if the animals have grass (which they mostly do) and water somewhat nearby they will breed with no limit.

**Comment by capnkirok** [comment]
@lynxvm would recommend your config on the server to manual breeding... and kill off a few of the dorpers. This config option is found under Game Rules. This means you will have to feed your animals by hand to get them to breed.

We have a Spawn Limit in place.. but natural breeding can sometimes lead to huge populations, especially if they are well fed. I am debating switching the default to manual breeding.

**Comment by capnkirok** [comment]
Ok, I've found another option that's going to go into 1.4.7. Animals will breed on their own until their limit is reached... at which point they will stop mating. From this point, there are two ways to make more animals. You can handfeed the animals and they will breed, or you can increase your spawn limits. In practice, this works very well.
