### ISSUE TITLE
[Suggestion] Spawn less animals [Crazy! :O]

### ISSUE THREAD

**Issue by Malrama** [capnkirok/animaniamod#190]
Hello everyone :)

Before we start I would like to say that this is not a bug nor anything gamebreaking. This is just a feedback from my side and is totaly up to personal taste, let's get into it.

Now, I am using the current version of Animania and I really love this mod. It became one of my "must have" mods. Thank you :)

But there is one this that really annoys me: It is the spawn rate of animals. There are just too many animals spawning in one area with up to 30+ within 2 days.

I was actively playing in a 40x40 area and after some time, this area was just full with animals. There has been at least, I am not gonna lie, 50+ animals all over the place.
While I do like the idea of having more animals spawning than vanilla does, it is just too much. After some time it just ended in extreme lag on world loading and playing so that I had to wipe all living creatures in that area. 
I think there should be a system (if not already) checking how many animals are currently present in one chunk/area and then should stop the spawning of new natural animals. It just went crazy.

As I said, I bet there are people loving this overpoulation with animals but for my taste, it is just too much and no longer immersive.

Thank you very much for considering this and have a nice day

**Comment by Tschipp** [comment]
You can configure the spawn rates in the config

**Comment by Malrama** [comment]
I see ... sorry I didn't know it was a thing. But anyway, if the system works as I think it does, it just goes nuts.

Let me get this right: You can set how many animals of each species can spawn in one chunk. So the default system is: 40 pigs per chunk, 40 amphibians per chunk ... and so on for each species. So let me add this up. 12 (diffrent species) * 40 = 480 (!!) Animals per chunk at it's best condition? O_O Well that explains a lot!
I think there should be a config that say "No more than X animals per chunk". I would set it to a max of 15-20 if you ask me. (A chunk is 16x16 blocks right?).
Maybe I am getting this wrong (I am sure I am because else it's just nuts) but 480 Animals (At its best condition) in a 16x16 area shouldn't even be possible.

While I do get that I can change this myself now, I think you guys should really rethink your default settings. As I said, for my taste there shouldn't be more than 15-20 Animals per chunk at max, maybe even less considering they breed themselfs and you can breed them!

Anyway, thank you for your respond :)

**Comment by capnkirok** [comment]
- It's not per chunk, it's per all loaded chunks, so it doesn't work the way you are saying
- Lower the values to your liking in the config (you may have to do some culling)
- Might also suggest you turn 'manual breeding' to true (this slows down repopulation)
- You can also increase the 'gestation period'
- The settings work fine for most people. Interactions with other mods, especially on servers can cause complications.

**Comment by Tschipp** [comment]
I'm gonna increase the max animal range to 30 blocks. That means if the entity count in a 30 block radius of an entity exceeds the config value (20 by default), the animal will not breed.
