### ISSUE TITLE
3D Spawnegg Rendering Bug

### ISSUE THREAD

**Issue by TimGoll** [capnkirok/animaniamod#191]
### Expected Behavior
display items in JEI without changing the screencolour

### Actual Behavior
screen gets dark when animania items are displayed:
![image](https://user-images.githubusercontent.com/13639408/47807039-66110300-dd3b-11e8-8861-a5a862a99725.png)
It only happens since the last animania update and there aren't any problems with other mods

### Steps to Reproduce
searching for @animania in JEI

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft: 1.12.2
Forge: 14.23.5.2768
Animania: 1.6.0.2

**Comment by TimGoll** [comment]
Actually, as soon as I have any animania item in my hand my screen gets dark

Normal:
![image](https://user-images.githubusercontent.com/13639408/47807194-c9029a00-dd3b-11e8-9ff0-a5ba305f61d5.png)


Item in Hand:
![image](https://user-images.githubusercontent.com/13639408/47807206-d029a800-dd3b-11e8-944d-19caa6129ff4.png)

**Comment by TimGoll** [comment]
Update: it only happens with your new fancy 3D spawn "eggs"

**Comment by TimGoll** [comment]
Update: Optifine isn't the problems, the shader I'm using causes these rendering bugs. I'm using [BSL v7.0 ](http://bitslablab.wixsite.com/main/bsl-shaders)

Other than the rendering error, I like the default spawneggs way more than the new 3D ones

**Comment by Tschipp** [comment]
You can turn off the fancy eggs in the config. I’m gonna take a look at the rendering issues.

**Comment by TimGoll** [comment]
Ahh, that's neat. Thank you

**Comment by Avery93** [comment]
Same issue here, but it overlays in bright green. Thought it was one of my mods, but it went away after turning off fancy eggs.

**Comment by Tschipp** [comment]
This is an incompatibility with optifine/shaders, because shaders break everything. Sorry, not fixable
