### ISSUE TITLE
Dependency Cycle (Incompatibility with Better With mods)

### ISSUE THREAD

**Issue by VonZeeple** [capnkirok/animaniamod#192]
### Expected Behavior

Forge loading the mods

### Actual Behavior

Forge stops and display following text:

> A dependency cycle was detected in the input mod set so an ordering cannot be determined
> The first mod in the cycle is FMLMod:animania{1.6}
> The mod cycle involves:
> 	FMLMod:thermalexpansion{5.5.2} : before: [enderio], after: [cofhcore@[4.6.0,4.7.0), thermalfoundation@[2.6.0,2.7.0), codechickenlib@[3.1.7,)]
> 	FMLMod:quark{r1.5-129} : before: [autoreglib], after: []
> 	Dummy Container (AfterAll) @109920591 : before: [], after: []
> 	APIContainer{BetterWithModsAPI:Beta 0.6} : before: [quark], after: [betterwithmods]
> 	Dummy Container (After) @1134600044 : before: [], after: []
> 	FMLMod:animania{1.6} : before: [zawa, thermalexpansion], after: [craftstudioapi, cofhcore, harvestcraft, natura, quark, botania, biomesoplenty, twilightforest, aroma1997sdimension, openterraingenerator, forge@[14.23.2.2638,)]
> 	FMLMod:betterwithmods{1.12-2.3.16-998} : before: [survivalist], after: [traverse, thaumcraft, natura, mantle, tconstruct, minechem, natura, terrafirmacraft, immersiveengineering, mekanism, thermalexpansion, ctm, geolosys, pvj, techreborn]

Note: Quark dependency seems to be the issue, no problem using animania version prior to 1.6 .

### Steps to Reproduce

Mods installed appearing in the cycle:
-Animania 1.6 or above
-Cofhcore 4.6.1.22
-Thermal expansion 5.5.2.39
-codechickenlib 3.2.2.353
-Quark 1.5-30
-Betterwithmods 2.3.16-998
-craftstudiaapi 1.0.0
-harvestcraft 1.12a
-biomes o plenty 7.0.1
-thaumcraft 6.1.BETA26
-immersiveengineering 0.12-86
-mekanism 9.4.13.349
-geolosys 2.1.3.1

### Version of Minecraft, version of Animania, Single Player or Server

Minecraft 1.12.2, Animania 1.6 and above.

**Comment by Tschipp** [comment]
The quark dependency has been in for a while now. My guess is something has changed with quark.

**Comment by VonZeeple** [comment]
Making a quick scheme, it seems that Thermal Expansion dependency added by the "Fancy Egg stuff, Bee stings" commit that causes the problem. I Renamed the issue

**Comment by Tschipp** [comment]
Don't think it's thermal expansion either, my game loads just fine with both quark and thermal expansion installed.

**Comment by VonZeeple** [comment]
I replicated the bug with a fresh install:
Forge 14.23.5.2768
-Animania 1.6.0.2
-AutoRegLib 1.3-20
-Cofhcore 4.6.1.22
-CofhWorld 1.3.0.6
-Thermal expansion 5.5.2.39
-Thermal Dynamics 2.5.3.16
-Thermal Foundation 2.6.1.22
-codechickenlib 3.2.2.353
-Quark 1.5-30
-Betterwithmods 2.3.16-998
-craftstudiaapi 1.0.0
-RedstoneFlux 2.1.0.6

The dependency cycle is solved by disabling Better with mods, or Thermal Expansion.
This is due to the Thermal Expansion and Quark dependencies in Animalia and BWM, so I guess these two mods are now incompatibles.

**Comment by Hubry** [comment]
Animania wants to load before TE and after Quark, BWM wants to load after TE and before Quark. My question is: why does Animania want to load between those mods? 

Looks like the reason for Quark is the dispenser thing, but Quark already disables its dispenser behavior for seeds if Animania is detected. The reason for TE is morbs, but I'm not entirely sure that's actually necessary to declare. I think at least the Quark dependency declaration could be removed without issues.

**Comment by Tschipp** [comment]
Yes, I've been looking into it and I've come to the same conclusion.
