### ISSUE TITLE
Scattered seeds don't break in an FTB Utilities claim

### ISSUE THREAD

**Issue by OreCruncher** [capnkirok/animaniamod#193]
### Expected Behavior
When a chicken feeds off the seeds scattered on the ground the block would break similar to that of an unprotected chunk.

### Actual Behavior
The scattered seed block doesn't break.

### Steps to Reproduce
Scatter seeds in an claim protected chunk and wait for mobs to eat it

### Version of Minecraft, version of Animania, Single Player or Server
MC 1.12.2; Animania 1.5.1.1; Single Player

Question: Is there a fake player that needs to be set somewhere?

**Comment by Tschipp** [comment]
Is this a problem with the latest version? Did you modify the config?

**Comment by OreCruncher** [comment]
It was the one posted before the latest.  And I haven't touched the config.  I will try with the latest posted to CurseForge to see.  Does Animania use a FakePlayer to break the seed block?

**Comment by OreCruncher** [comment]
I tested with 1.6.0.2 and it appears to be working. Hmm is right. :)  Going to close.  If I have any further issues I will let you know.  Thanks!
