### ISSUE TITLE
Client crash when opening manual

### ISSUE THREAD

**Issue by V10lator** [capnkirok/animaniamod#194]
### Version of Minecraft, version of Animania, Single Player or Server
1.12.2
1.6.0.2
Server

### Screenshots encouraged
Crashlog: https://paste.dimdev.org/yazuvemife.mccrash?fbclid=IwAR1ZPTE1W24PjxRFaLhmtaUl04wUlBzKojJDjWadeetO3J9g2DhOrg0SzTA

**Comment by Tschipp** [comment]
Hmm strange, do you remember what the last page of the manual was, when you closed it? To get rid of this issue, I would throw away that manual and craft a new one.

**Comment by V10lator** [comment]
According to the player the book was newly crafted and opened for the first time. Maybe its worth to note that he used a book in single player before joining multiplayer.

**Comment by capnkirok** [comment]
Also curious... do you have any of the Animania animals set to not spawn?

**Comment by Tschipp** [comment]
Did he modify the animania jar in any way?

**Comment by V10lator** [comment]
> Also curious... do you have any of the Animania animals set to not spawn?

No.

> Did he modify the animania jar in any way?

No.
