### ISSUE TITLE
[Suggestion] Cuisine compat

### ISSUE THREAD

**Issue by breadguyyy** [capnkirok/animaniamod#195]
Would love to see some default compatibility with the foods, crops and seeds added by cuisine. I noticed that mods like harvestcraft, biomes o plenty, and simple corn have foods automatically listed in the animania config for things like the trough, foods for different animals, etc. and I think cuisine would make a good addition to that list. I can definitely see it getting more popular in the future and it plays really well with animania from a gameplay perspective (eg. low tech realism, more interesting farming). I know people can add things to those lists manually but I think it would be nice for users to have that out-of-the-box compatibility too. Thanks!

**Comment by Deshiba** [comment]
The config allows you to configure extra items that can be placed in the trough. The defaults are in there for example, you can add your own. Look in your config for the "Food Items that can be placed in the trough" line and add cuisine:[fooditem] to the list.

**Comment by Tschipp** [comment]
Yeah, I agree with Deshiba, I only included Pam's because it's so massive and most commonly used.
