### ISSUE TITLE
[SUGGESTION] Send pregnancy timer only once a second

### ISSUE THREAD

**Issue by V10lator** [capnkirok/animaniamod#196]
Right now the pregnancy timer is shown in ticks (WAYLA). I think (didn't look at the codes) that means there's a packet sendet to nearby clients each tick for each pregnant animal. Why not change the timer to seconds and send the packets each seconds instead? :)

**Comment by Tschipp** [comment]
We are not sending any packets. We are reading the data from the entity that waila gives to us and display it.
