### ISSUE TITLE
99% female animals

### ISSUE THREAD

**Issue by V10lator** [capnkirok/animaniamod#197]
Thre are mostly only female animals, making it hard to breed. This might be connected with bug #167 as it looks like (might be wrong on this) male animals spawn in new chunks only.

//EDIT: To get some numbers:
\> 200 female animals where found.
Only 3 male animals where found.

**Comment by Tschipp** [comment]
Nice catch, this must have slipped by when we updated/rewrote some stuff.

**Comment by Tschipp** [comment]
PR fixes this
