### ISSUE TITLE
Naming inconsistencies

### ISSUE THREAD

**Issue by Deshiba** [capnkirok/animaniamod#20]
Currently there's some naming inconsistencies amongst animals. To summon a chicken or a cow is different.
> /summon animania:chick_plymouth_rock
> /summon animania:rooster_rhode_island_red
> /summon animania:calf_longhorn
> /summon animania:bull_highland

For sanity sake it would be nice if  all entities were created equal. So if it's not a lot of work could the entities be made the same. This would result in the following compared to the examples above.
> /summon animania:chick_plymouth_rock
> /summon animania:rooster_rhode_island_red
> /summon animania:calf_texas_longhorn
> /summon animania:bull_scottish_highland

**Comment by Tschipp** [comment]
The Texas Longhorns used to just be called Longhorns. If we would rename them now, it would cause all existing longhorns and highlands to despawn. So no, I don't think that that's worth it.

**Comment by Deshiba** [comment]
Fair enough
