### ISSUE TITLE
Suggestion:Actually Additions's earthworm

### ISSUE THREAD

**Issue by mser7** [capnkirok/animaniamod#202]
It isn't a mob, but rather, an items, and it sounds more suitable for this mod

**Comment by Tschipp** [comment]
What are you talking about?

**Comment by mser7** [comment]
Here, I love it and it is perfect for this mod, sorry for not specific it is a feature of a mod
https://ftb.gamepedia.com/Worm_(Actually_Additions)

**Comment by Tschipp** [comment]
You should probably ask actually additions about this
