### ISSUE TITLE
Can continously dye sheep with the same dye

### ISSUE THREAD

**Issue by mser7** [capnkirok/animaniamod#203]
### Expected Behavior
Sheeps won't accept any dye with the same color of the their wools

### Actual Behavior
They accept it nonetheless

### Steps to Reproduce
Find a dyeable sheep
Have a stack of dyes
Click and hold right click with that stack on your hand, pointing at the sheep, and the dyes keep getting consumed

### Version of Minecraft, version of Animania, Single Player or Server
MC 1.12.2
Animania 1.6.0.2
SSP

### Screenshots encouraged
May provide later.

**Comment by Tschipp** [comment]
Right, but why would you dye a sheep with the same color multiple times?

**Comment by mser7** [comment]
I was holding down the right click button since I expect them to only take 1 of my dye.

No, actually, it was a test, I was wonder if I apply bone meal, on a natural white sheep would it turn the wools color whiter, since there are custom sheep wools in the mod. It doesn't but then I thought if I discovered a bug and here we are.

**Comment by mser7** [comment]
Updated
