### ISSUE TITLE
animals bug, or something. 

### ISSUE THREAD

**Issue by HentaiHamster** [capnkirok/animaniamod#206]
### Expected Behavior
animals eating and drinking from troughs

also I found that I cant use a lead on baby animals, and some sheep/goats

### Actual Behavior
animals (2 cows and 3 sheep) wont eat or drink from troughs and they would rather stare at my crops and grass growing outside their animal pens I have them in. 

### Steps to Reproduce
idk?
I've had these animals for like 10 minecraft days after installing the mod. 

### Version of Minecraft, version of Animania, Single Player or Server
minecraft - 1.12.2
singleplayer
animania - 1.6.0.2 

### Screenshots encouraged
![2018-11-06_11 46 20](https://user-images.githubusercontent.com/13722387/48079591-ab10bb80-e1b9-11e8-8f4a-43a21922f403.png)

**Comment by PABadger** [comment]
I noticed this happening too. The goats just stood and stared at a water source block outside their enclosure. I fed and watered them by hand, and they moved away, but then they got thirsty again and went back to staring, even with two troughs full of water right next to them.

Also running 1.6.0.2. Behavior exactly as above, just with a water source block. 

I'm running SSP with about forty mods, including Harvestcraft, which I see here. I tested this on a creative world with the same modpacks, and then again with nothing but forge, hwyla, craft api, and animania.

In both cases, I was able to recreate behavior by creating a small enclosure with two troughs, one full of wheat, the other full of water, with no grass inside, within ten blocks of a water source with considerable grass outside, spawning an alpine goat doe and buck, and waiting until they got hungry/thirsty. In one case, one of the animals drank 100 mb water from one of the troughs, and then the other goat climbed on top of the trough and appeared unable to drink. Both animals were hungry and thirsty. In both cases, I waited two minutes, and then broke open the fence. When I broke open the fence, both rushed out to eat the grass and drink from the water source block.
