### ISSUE TITLE
Thirsty Animals Ignore Troughs

### ISSUE THREAD

**Issue by Ophilla** [capnkirok/animaniamod#208]
### Expected Behavior
When animals are hungry/thirsty, they will look for a filled trough and eat/drink.

### Actual Behavior
My cattle, sheep, chickens, and peafowl prefer to eat grass or my nearby crops and drink the nearby lake/waterfall inside my house and they will all crowd into one corner of the corral/barn and will not leave until I put a lead on them and pull them away. Even when I'm holding food or a water bucket, they pay no attention to me, and if I open the gate, they all run out to eat my crops and drink the lake. I have noticed that this mainly happens when an animal is thirsty -- if they are not thirsty, sometimes they will eat food from a trough. If they are thirsty, they fixate on a source of open water and will not eat or drink from a trough.

### Steps to Reproduce
I reproduced it on a single-player map by building corrals with troughs, spawning animals inside, and about 10 blocks away, planting crops and placing water to keep the crops irrigated. I did fill the troughs AFTER placing the water, but the water would always be there first if it were, for example, a river or pond.

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12.2, Animania 1.6.0.2, Server and Single Player

### Screenshots encouraged
In this screenshot, you can see that the cows bunch up in the corner of the shelter to try to get in my house and drink my waterfall instead of drinking from the trough. (server)
![image](https://user-images.githubusercontent.com/16845687/48178349-0ee4d280-e2e7-11e8-9367-bafd9dde172e.png)

In this screenshot, you can see that the goat buck wants to go eat the grass instead of eating from the trough or following the wheat in my hand. The ram in the next corral over is thirsty and wants to go drink the river instead of drinking from the trough.
![image](https://user-images.githubusercontent.com/16845687/48178407-54090480-e2e7-11e8-9862-7ddd9690dd33.png)

ETA:
<details>
  <summary>Mod List (all found on Twitch)</summary>
Animania<br>
AppleSkin (Client-side only)<br>
Backpacks!<br>
Bibliocraft<br>
Block Drops (JEI Addon)<br>
Chameleon<br>
Craftable Horse Armour & Saddle [CHA&S]<br>
CraftStudio API<br>
Creeper Confetti<br>
GraveStone Mod<br>
Hatchery<br>
Horse Debug Info (Client-side only)<br>
Inventory Tweaks (Client-side I think, and I don't see it in the server but just in case)<br>
JourneyMap (I believe this actually only works client-side, but it's currently in the server)<br>
Just Enough Harvestcraft (JEHC)<br>
Just Enough Items (JEI)<br>
Just Enough Resources (JER)<br>
Pam's HarvestCraft<br>
Pam's Llama Milking<br>
Storage Drawers<br>
The One Probe<br>
Tree Chopper<br>
VeinMiner<br>
Zoocraft Discoveries
</details>

**Comment by Ophilla** [comment]
Oops, it appears someone beat me to this. I had this post unfinished for a few days and didn't check for a new post before I submitted it. I suppose it can be deleted.

**Comment by Deshiba** [comment]
There have been several reports on github and on the discord. The issue is being looked into, leave this one up for now. There might be some info in here that isn't in some other reports.

Also, could you add your modlist to this post? It might be a compat issue since this isn't happening for everyone.

**Comment by Ophilla** [comment]
Of course. :) My mod list is added at the bottom.
