### ISSUE TITLE
Straw bed can be replaced like tallgrass

### ISSUE THREAD

**Issue by mser7** [capnkirok/animaniamod#209]
### Expected Behavior
The block will be placed at another space that is not occupied by the bed

### Actual Behavior
When right click a straw bed with a block, it replaces the bed, like tallgrass

### Steps to Reproduce
Just right click the bed with any block

### Version of Minecraft, version of Animania, Single Player or Server
MC 1.12.2
Animania 1.6.0.2
SSP

**Comment by Tschipp** [comment]
This is intended behavior

**Comment by mser7** [comment]
For real? This is very annoying, why? Can't you at least have the block don't delete it if shift clicked?

**Comment by mser7** [comment]
Even tiny blocks such as flowers, carpet, string or wooden button don't follow this behavior.

**Comment by Tschipp** [comment]
Sure, if you find it annoying we can change it.

**Comment by mser7** [comment]
Thank you, having my one piece of wheat deleted really bother me.

**Comment by mser7** [comment]
I will suggest this anyway despite the patch has already been done, why don't you just make the bed item drop if it got replaced by a block, I only hate having my bed being deleted.
