### ISSUE TITLE
Crash on hamster summon

### ISSUE THREAD

**Issue by Deshiba** [capnkirok/animaniamod#21]
I get a crash of minecraft when trying to summon a hamster with a ColorNumber value of double digits, I used the following commands
> /summon animania:hamster 122 1.8 1 {NoAI:1,ColorNumber:10}
> /summon animania:hamster 122 1.8 1 {NoAI:1,ColorNumber:11}

This corrupts the entire world until you remove the entity with something like mcedit. 
https://pastebin.com/3hxFA4ay

When I do the same thing with draft horses it works fine
> /summon animania:foal_draft 122 1.8 1 {NoAI:1,ColorNumber:10}

====Versions====
Minecraft 1.12
Minecraft Coder Pack 9.42
Forge Mod Loader 8.0.99.99
Forge 1.4.23.2.261
CraftStudio API 1.0.0
Animania 1.4.6
Flat Colored Blocks mc1.12-6.6

**Comment by capnkirok** [comment]
I guess I could put some error trapping in there, but there are only 9 colors...

**Comment by capnkirok** [comment]
Ok, error trapping added (like horses)

**Comment by Deshiba** [comment]
Its not a big deal, only people testing in creative would run into this 😅
