### ISSUE TITLE
Animals clipping through walls and suffocating

### ISSUE THREAD

**Issue by Luke616** [capnkirok/animaniamod#210]
### Expected Behavior
Animals do not path into walls and suffocate

### Actual Behavior
Animals keep clipping into walls and suffocating. I've specifically noticed this happening to chickens and cows.

### Steps to Reproduce
Set up a farm and house some cows and chickens near to a wall or corner. Here are some examples of specific places where animals are dying:

![image](https://user-images.githubusercontent.com/3951604/48305274-a586de80-e4f5-11e8-9f58-dee795a82221.png)
This wall

![2018-11-09_00 48 49](https://user-images.githubusercontent.com/3951604/48305280-c2231680-e4f5-11e8-946c-6e342d55cd10.png)
This corner

![2018-11-09_00 46 38](https://user-images.githubusercontent.com/3951604/48305282-c3ecda00-e4f5-11e8-9373-21082a370c24.png)
This corner

### Version of Minecraft, version of Animania, Single Player or Server
Animania 1.6.0.2
Forge 14.23.5.2768
Minecraft 1.12.2
Multiplayer Server

**Comment by Tschipp** [comment]
Yes, noticed this too. You can see this issue if you enable bounding boxes (F3 + B) and rejoin your world. You will see animals shift their hitboxes, which causes them to glitch through the walls

**Comment by mser7** [comment]
this might be a vanilla bug.

**Comment by Tschipp** [comment]
Ok, this one has finally been fixed.
