### ISSUE TITLE
Removing Animania

### ISSUE THREAD

**Issue by ladyGique** [capnkirok/animaniamod#211]
I am trying to remove Animania from my server, but when I remove the mod, my server says : 

> 10.11 12:39:41 [Server] Server thread/ERROR [FML.ModTracker]: This world was saved with mod animania which appears to be missing, things may not work well

And the server will not start. I really would like to get rid of the mod, there certain things we do on this server that won't work with out the animals (specifically chickens) works.

**Comment by Tschipp** [comment]
What exactly do you mean? Can you post the entire log?
