### ISSUE TITLE
pigs and ancient warfare farms

### ISSUE THREAD

**Issue by njtxus** [capnkirok/animaniamod#212]
### Expected Behavior
ancient warfare farms to harvest pigs. 

### Actual Behavior
they are ignored
cows, sheep, and chickens work fine.
### Version of Minecraft, version of Animania, Single Player or Server
12.2 animania 1602

**Comment by njtxus** [comment]
minecolonies is the same way. all other animals are recognized accept the pigs.

**Comment by Tschipp** [comment]
One possible solution for this is to make pigs extend EntityPig @capnkirok

**Comment by njtxus** [comment]
thanks for the fix! great work guys!
