### ISSUE TITLE
Animania Chickens for Extra Utils 2 chicken wing ring

### ISSUE THREAD

**Issue by SlayerTheChikken** [capnkirok/animaniamod#218]
### Expected Behavior
Be able to golden lasso an animania chicken to make the chicken wing ring.

### Actual Behavior
Chicken not recognized.

### Steps to Reproduce
Literally just right click an animania chicken with golden lasso :3

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2 mc 1.6.0.2 animania, both

Issue reference: https://github.com/rwtema/Extra-Utilities-2-Source/issues/29

**Comment by florian-berger** [comment]
Would be great if it will be possible soon.

**Comment by gtokarz** [comment]
temporarly you can use crafttweaker to adjust recipe see attachement
[extrautils-animania.txt](https://github.com/capnkirok/animaniamod/files/2591982/extrautils-animania.txt)

**Comment by Tschipp** [comment]
Our chickens implements EntityChicken. This is sadly not up to us to fix/change.
