### ISSUE TITLE
Problems with feeding animal

### ISSUE THREAD

**Issue by Atomicfruits** [capnkirok/animaniamod#219]
every time I try to feed a hedgehog it crashes and says this

The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Unexpected error

**Comment by Tschipp** [comment]
What are you feeding it with? What is your modlist? Can you post the entire crash? What is your version?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Atomicfruits** [comment]
my mod list is advanced rocketry, carry on, mr cray fish furniture mod, craft studio, just enough items, journey map, Libvulpes, llibray, Minecraft comes alive, optiFine, ANNND radix core, im also using 1.12.2 and im feeding it carrots I dont know if it happens to the others I haven't tried

**Comment by Atomicfruits** [comment]
ok so I dont know if this is all of the code but this is what I found on the crash report also it happens with all the food types

error
	at com.animania.common.entities.rodents.EntityHedgehogBase.func_175505_a(EntityHedgehogBase.java:198)
	at com.animania.common.entities.rodents.EntityHedgehogBase.func_184645_a(EntityHedgehogBase.java:495)
	at net.minecraft.entity.EntityLiving.func_184230_a(EntityLiving.java:1414)
	at net.minecraft.entity.player.EntityPlayer.func_190775_a(EntityPlayer.java:1199)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187097_a(PlayerControllerMP.java:549)
	at net.optifine.override.PlayerControllerOF.func_187097_a(PlayerControllerOF.java:111)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1566)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2253)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2019)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1807)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.animania.common.entities.rodents.EntityHedgehogBase.func_175505_a(EntityHedgehogBase.java:198)
	at com.animania.common.entities.rodents.EntityHedgehogBase.func_184645_a(EntityHedgehogBase.java:495)
	at net.minecraft.entity.EntityLiving.func_184230_a(EntityLiving.java:1414)
	at net.minecraft.entity.player.EntityPlayer.func_190775_a(EntityPlayer.java:1199)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187097_a(PlayerControllerMP.java:549)
	at net.optifine.override.PlayerControllerOF.func_187097_a(PlayerControllerOF.java:111)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1566)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2253)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2019)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['aworldintime'/96, l='MpServer', x=133.93, y=73.00, z=1567.10]]
	Chunk stats: MultiplayerChunkCache: 287, 287
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (138,64,194), Chunk: (at 10,4,2 in 8,12; contains blocks 128,0,192 to 143,255,207), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 33908 game time, 33908 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 55 total; [EntitySpider['Spider'/256, l='MpServer', x=128.60, y=30.00, z=1578.60], EntitySkeleton['Skeleton'/257, l='MpServer', x=128.50, y=30.00, z=1580.50], EntityBat['Bat'/258, l='MpServer', x=134.61, y=29.10, z=1577.45], EntitySkeleton['Skeleton'/259, l='MpServer', x=138.11, y=27.00, z=1578.50], EntitySkeleton['Skeleton'/260, l='MpServer', x=137.49, y=27.00, z=1579.28], EntitySpider['Spider'/261, l='MpServer', x=136.00, y=27.00, z=1571.96], EntitySkeleton['Skeleton'/263, l='MpServer', x=135.09, y=30.00, z=1579.77], EntitySpider['Spider'/264, l='MpServer', x=131.70, y=32.10, z=1579.70], EntityCreeper['Creeper'/266, l='MpServer', x=135.19, y=27.00, z=1580.60], EntityCreeper['Creeper'/267, l='MpServer', x=138.70, y=27.00, z=1577.64], EntityBat['Bat'/268, l='MpServer', x=127.25, y=27.33, z=1572.54], EntityBat['Bat'/269, l='MpServer', x=135.58, y=29.00, z=1579.74], EntityBat['Bat'/270, l='MpServer', x=134.54, y=33.10, z=1578.25], EntityHedgehogAlbino['Albino Hedgehog'/398, l='MpServer', x=178.25, y=66.00, z=1614.75], EntityCreeper['Creeper'/271, l='MpServer', x=131.50, y=35.00, z=1577.50], EntityWagon['Covered Wagon'/399, l='MpServer', x=144.32, y=71.00, z=1593.34], EntityRoosterLeghorn['Leghorn Rooster'/400, l='MpServer', x=169.43, y=71.00, z=1586.12], EntityBat['Bat'/273, l='MpServer', x=136.38, y=33.10, z=1578.66], EntityZombie['Zombie'/274, l='MpServer', x=139.32, y=35.00, z=1576.52], EntitySkeleton['Skeleton'/275, l='MpServer', x=137.64, y=35.00, z=1575.50], EntityMareDraftHorse['Draft Horse Mare'/404, l='MpServer', x=132.96, y=73.00, z=1580.24], EntityMinecartChest['Minecart with Chest'/405, l='MpServer', x=158.50, y=25.06, z=1557.50], EntityHenLeghorn['Leghorn Hen'/408, l='MpServer', x=129.36, y=70.00, z=1615.53], EntitySpider['Spider'/410, l='MpServer', x=139.54, y=31.00, z=1585.30], EntityHenLeghorn['Leghorn Hen'/415, l='MpServer', x=168.38, y=69.00, z=1527.49], EntityMinecartChest['Minecart with Chest'/416, l='MpServer', x=165.50, y=24.00, z=1530.49], EntityMinecartChest['Minecart with Chest'/417, l='MpServer', x=143.50, y=30.06, z=1500.50], EntityCreeper['Creeper'/1058, l='MpServer', x=146.50, y=25.00, z=1556.50], EntityCreeper['Creeper'/1059, l='MpServer', x=142.50, y=25.00, z=1557.50], EntitySowYorkshire['American Yorkshire Sow'/421, l='MpServer', x=135.04, y=71.00, z=1528.82], EntityPlayerSP['aworldintime'/96, l='MpServer', x=133.93, y=73.00, z=1567.10], EntityFrogs['Frog'/328, l='MpServer', x=92.50, y=63.00, z=1620.50], EntityMinecartChest['Minecart with Chest'/330, l='MpServer', x=123.50, y=26.06, z=1556.50], EntityMinecartChest['Minecart with Chest'/331, l='MpServer', x=123.50, y=26.06, z=1561.50], EntityBat['Bat'/333, l='MpServer', x=127.25, y=26.29, z=1559.55], EntitySkeleton['Skeleton'/334, l='MpServer', x=134.38, y=27.00, z=1579.85], EntityBat['Bat'/336, l='MpServer', x=127.25, y=27.10, z=1570.13], EntitySkeleton['Skeleton'/464, l='MpServer', x=126.50, y=14.00, z=1558.50], EntityCreeper['Creeper'/337, l='MpServer', x=118.50, y=35.00, z=1575.50], EntityMinecartChest['Minecart with Chest'/339, l='MpServer', x=122.50, y=30.06, z=1551.50], EntityRoosterLeghorn['Leghorn Rooster'/340, l='MpServer', x=115.64, y=71.00, z=1547.46], EntityZombie['Zombie'/341, l='MpServer', x=83.74, y=57.00, z=1504.48], EntityMinecartChest['Minecart with Chest'/342, l='MpServer', x=102.50, y=35.06, z=1500.50], EntityZombie['Zombie'/343, l='MpServer', x=126.50, y=50.00, z=1510.50], EntityCreeper['Creeper'/344, l='MpServer', x=121.50, y=50.00, z=1515.50], EntityMinecartChest['Minecart with Chest'/345, l='MpServer', x=71.50, y=31.06, z=1490.50], EntityMinecartChest['Minecart with Chest'/346, l='MpServer', x=78.50, y=31.06, z=1498.50], EntitySowYorkshire['American Yorkshire Sow'/348, l='MpServer', x=78.00, y=97.00, z=1519.86], EntityMinecartChest['Minecart with Chest'/349, l='MpServer', x=92.50, y=31.06, z=1500.50], EntityMinecartChest['Minecart with Chest'/350, l='MpServer', x=84.50, y=35.06, z=1489.50], EntitySkeleton['Skeleton'/248, l='MpServer', x=137.50, y=25.00, z=1565.50], EntitySkeleton['Skeleton'/249, l='MpServer', x=137.50, y=25.00, z=1567.50], EntityBat['Bat'/252, l='MpServer', x=145.47, y=26.02, z=1566.13], EntityHedgehog['Hedgehog'/253, l='MpServer', x=132.52, y=73.00, z=1566.44], EntitySkeleton['Skeleton'/255, l='MpServer', x=131.70, y=27.00, z=1574.49]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2740)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 535467608 bytes (510 MB) / 1207959552 bytes (1152 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 Optifine OptiFine_1.12.2_HD_U_E2 16 mods loaded, 16 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                   | Version      | Source                                          | Signature                                |
	|:--------- |:-------------------- |:------------ |:----------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft            | 1.12.2       | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | mcp                  | 9.42         | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | FML                  | 8.0.99.99    | forge-1.12.2-14.23.5.2768.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                | 14.23.5.2768 | forge-1.12.2-14.23.5.2768.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | advancedrocketrycore | 1            | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | libvulpes            | 0.3.0.-44    | LibVulpes-1.12.2-0.3.0-44-universal.jar         | None                                     |
	| UCHIJAAAA | advancedrocketry     | 1.4.1.-111   | AdvancedRocketry-1.12.2-1.4.1-111-universal.jar | None                                     |
	| UCHIJAAAA | craftstudioapi       | 1.0.0        | CraftStudio-1.0.0.93-mc1.12-alpha.jar           | None                                     |
	| UCHIJAAAA | animania             | 1.6.1        | animania-1.12.2-1.6.1.jar                       | None                                     |
	| UCHIJAAAA | carryon              | 1.11.1       | CarryOn+MC1.12.2+v1.11.1.jar                    | None                                     |
	| UCHIJAAAA | cfm                  | 5.12.0       | cfm-5.12.0-mc1.12.2.jar                         | None                                     |
	| UCHIJAAAA | jei                  | 4.13.0.218   | jei_1.12.2-4.13.0.218.jar                       | None                                     |
	| UCHIJAAAA | journeymap           | 1.12.2-5.5.2 | journeymap-1.12.2-5.5.2 (2).jar                 | None                                     |
	| UCHIJAAAA | radixcore            | 1.12.x-2.2.1 | RadixCore-1.12.x-2.2.1-universal.jar            | None                                     |
	| UCHIJAAAA | mca                  | 1.12.2-5.3.1 | MCA-1.12.x-5.3.1-universal.jar                  | None                                     |
	| UCHIJAAAA | llibrary             | 1.7.15       | llibrary-1.7.15-1.12.2.jar                      | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |

	Loaded coremods (and transformers): 
AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.4.1-111-universal.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
llibrary (llibrary-core-1.0.8-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 20.19.15.4642' Renderer: 'Intel(R) HD Graphics 405'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2768
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 405 GL version 4.4.0 - Build 20.19.15.4642, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Clear+Glass+Pack+1.11+or+1.12.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Pentium(R) CPU N3710 @ 1.60GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_E2
	OptiFine Build: 20180728-185429
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.4.0 - Build 20.19.15.4642
	OpenGlRenderer: Intel(R) HD Graphics 405
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by Atomicfruits** [comment]
so turns out that it was just the 1.6.1 version so you might wanna get that fixed

**Comment by lottielu** [comment]
also crashes with ferrets when feeding them eggs

**Comment by Tschipp** [comment]
I am looking into it.

**Comment by ssebberr** [comment]
In addition to what lottielu said, I'm having problems when I feed ferrets as well as hedgehogs any food. Haven't tried hamsters yet
