### ISSUE TITLE
Game crash when feeding hedgehog

### ISSUE THREAD

**Issue by Haybug** [capnkirok/animaniamod#222]
### Expected Behavior
Game would not crash and hedgehog would be tamed

### Actual Behavior
game crashed immediately upon clicking the hedgehog with a food item
note: this did not happen with draft horses, which were the only animal I was able to tame before attempting with the hedgehog.

### Steps to Reproduce
1. spawn hedgehog
2. equip carrot (or food of choice)
3. right-click hedgehog
game crashes

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12.2
Animania 1.12.2
Singleplayer

**Comment by Tschipp** [comment]
Duplicate of #219
