### ISSUE TITLE
[1.6.1] Crafting Milk gives Honey from Pam's Harvestcraft.

### ISSUE THREAD

**Issue by SirChamomile** [capnkirok/animaniamod#223]
### Expected Behavior
Friesian Cow Milk (Animania) -> Cow Milk (Minecraft) 

### Actual Behavior
Friesian Cow Milk (Animania) -> Honey (Pam's Harvestcraft) 

### Steps to Reproduce
Put a bucket of the milk in a crafting table or the player crafting grid. (Pam's recipe doesn't show in JEI recipe previews)

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2 - 1.6.1 - SSP

### Screenshots encouraged
![2018-11-19_16 32 45](https://user-images.githubusercontent.com/23204608/48740029-7c63fd80-ec1b-11e8-88cc-c48267a64da6.png)

![2018-11-19_16 32 48](https://user-images.githubusercontent.com/23204608/48740034-7ec65780-ec1b-11e8-9b39-f5f04767ced8.png)

**Comment by Tschipp** [comment]
Doesn't happen with a normal install of animania and pam's. What are your other mods?

**Comment by SirChamomile** [comment]
|       | minecraft                 | 1.12.2            | minecraft.jar                               | None                                     |
	|       | mcp                       | 9.42              | minecraft.jar                               | None                                     |
	|       | FML                       | 8.0.99.99         | forge-1.12.2-14.23.5.2768.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	|       | forge                     | 14.23.5.2768      | forge-1.12.2-14.23.5.2768.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	|       | dsurroundcore             |                   | minecraft.jar                               | None                                     |
	|       | dsurroundcore             |                   | minecraft.jar                               | None                                     |
	|       | alternatingflux           | 0.12.2-1          | alternatingflux-0.12.2-1.jar                | None                                     |
	|       | animania                  | 1.6.0.2           | animania-1.12.2-1.6.0.2.jar                 | None                                     |
	|       | antiqueatlas              | 4.4.9             | antiqueatlas-1.12.2-4.4.9.jar               | None                                     |
	|       | antiqueatlasoverlay       | 1.2               | antiqueatlas-1.12.2-4.4.9.jar               | None                                     |
	|       | examplemod                | 1.0               | antiqueatlas-1.12.2-4.4.9.jar               | None                                     |
	|       | applecore                 | 3.1.4             | AppleCore-mc1.12.2-3.1.4.jar                | None                                     |
	|       | appleskin                 | 1.0.9             | AppleSkin-mc1.12-1.0.9.jar                  | None                                     |
	|       | astralsorcery             | 1.10.3            | astralsorcery-1.12.2-1.10.3.jar             | None                                     |
	|       | autoreglib                | 1.3-20            | AutoRegLib-1.3-20.jar                       | None                                     |
	|       | baubles                   | 1.5.2             | Baubles-1.12-1.5.2.jar                      | None                                     |
	|       | betterfoliage             | 2.2.0             | BetterFoliage-MC1.12-2.2.0.jar              | None                                     |
	|       | bettermobgriefinggamerule | 1.12.2-7.0.1      | bettermobgriefinggamerule-1.12.2-7.0.1.jar  | None                                     |
	|       | bibliocraft               | 2.4.5             | BiblioCraft[v2.4.5][MC1.12.2].jar           | None                                     |
	|       | binniecore                | 2.5.1.184         | binnie-mods-1.12.2-2.5.1.184.jar            | None                                     |
	|       | botany                    | 2.5.1.184         | binnie-mods-1.12.2-2.5.1.184.jar            | None                                     |
	|       | binniedesign              | 2.5.1.184         | binnie-mods-1.12.2-2.5.1.184.jar            | None                                     |
	|       | extrabees                 | 2.5.1.184         | binnie-mods-1.12.2-2.5.1.184.jar            | None                                     |
	|       | extratrees                | 2.5.1.184         | binnie-mods-1.12.2-2.5.1.184.jar            | None                                     |
	|       | genetics                  | 2.5.1.184         | binnie-mods-1.12.2-2.5.1.184.jar            | None                                     |
	|       | botania                   | r1.10-357         | Botania r1.10-357.jar                       | None                                     |
	|       | chameleon                 | 1.12-4.1.3        | Chameleon-1.12-4.1.3.jar                    | None                                     |
	|       | craftstudioapi            | 1.0.0             | CraftStudio-1.0.0.93-mc1.12-alpha.jar       | None                                     |
	|       | engineersdoors            | 0.8.0             | engineers_doors-1.12.2-0.8.0.jar            | None                                     |
	|       | extraalchemy              | 0.3.8.6.1-release | extraalchemy-0.3.8.6.1-release.jar          | None                                     |
	|       | familiarfauna             | 1.0.10            | FamiliarFauna-1.12.2-1.0.10.jar             | None                                     |
	|       | felling                   | 1.4.0             | felling-1.4.0-1.12.x.jar                    | None                                     |
	|       | forestry                  | 5.8.2.372         | forestry_1.12.2-5.8.2.372.jar               | None                                     |
	|       | forgelin                  | 1.8.0             | Forgelin-1.8.0.jar                          | None                                     |
	|       | geographicraft            | 0.8.7             | GeographiCraft-1.12-0.8.9b.jar              | None                                     |
	|       | growthcraft_apples        | 4.0.4.100         | growthcraft-1.12.2-4.0.4.100.jar            | None                                     |
	|       | growthcraft_bamboo        | 4.0.4.100         | growthcraft-1.12.2-4.0.4.100.jar            | None                                     |
	|       | growthcraft_bees          | 4.0.4.100         | growthcraft-1.12.2-4.0.4.100.jar            | None                                     |
	|       | growthcraft_cellar        | 4.0.4.100         | growthcraft-1.12.2-4.0.4.100.jar            | None                                     |
	|       | growthcraft               | 4.0.4.100         | growthcraft-1.12.2-4.0.4.100.jar            | None                                     |
	|       | growthcraft_fishtrap      | 4.0.4.100         | growthcraft-1.12.2-4.0.4.100.jar            | None                                     |
	|       | growthcraft_grapes        | 4.0.4.100         | growthcraft-1.12.2-4.0.4.100.jar            | None                                     |
	|       | growthcraft_hops          | 4.0.4.100         | growthcraft-1.12.2-4.0.4.100.jar            | None                                     |
	|       | growthcraft_milk          | 4.0.4.100         | growthcraft-1.12.2-4.0.4.100.jar            | None                                     |
	|       | growthcraft_rice          | 4.0.4.100         | growthcraft-1.12.2-4.0.4.100.jar            | None                                     |
	|       | waila                     | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                 | None                                     |
	|       | immersivepetroleum        | 1.1.9             | immersivepetroleum-1.12.2-1.1.9.jar         | None                                     |
	|       | ironchest                 | 1.12.2-7.0.52.837 | ironchest-1.12.2-7.0.52.837.jar             | None                                     |
	|       | jei                       | 4.13.1.222        | jei_1.12.2-4.13.1.222.jar                   | None                                     |
	|       | magipsi                   | 1.3               | MagicalPsi-1.3.jar                          | None                                     |
	|       | magicbees                 | 1.0               | MagicBees-1.12.2-3.1.10.jar                 | None                                     |
	|       | mousetweaks               | 2.9               | MouseTweaks-2.9-mc1.12.2.jar                | None                                     |
	|       | harvestcraft              | 1.12.2z           | Pam's HarvestCraft 1.12.2za.jar             | None                                     |
	|       | psi                       | r1.1-59           | Psi-r1.1-59.jar                             | None                                     |
	|       | quark                     | r1.5-130          | Quark-r1.5-130.jar                          | None                                     |
	|       | xreliquary                | 1.12.2-1.3.4.780  | Reliquary-1.12.2-1.3.4.780.jar              | None                                     |
	|       | sereneseasons             | 1.2.6             | SereneSeasons-1.12.2-1.2.6-universal.jar    | None                                     |
	|       | spartanshields            | 1.4.1             | SpartanShields-1.12.2-1.4.1.jar             | None                                     |
	|       | storagedrawers            | 1.12-5.3.5        | StorageDrawers-1.12.2-5.3.7.jar             | None                                     |
	|       | thaumcraft                | 6.1.BETA26        | Thaumcraft-1.12.2-6.1.BETA26.jar            | None                                     |
	|       | twilightforest            | 3.8.689           | twilightforest-1.12.2-3.8.689-universal.jar | None                                     |
	|       | unidict                   | 1.12.2-2.9.1      | UniDict-1.12.2-2.9.1.jar                    | None                                     |
	|       | veining                   | 1.3.2             | veining-1.3.2-1.12.x.jar                    | None                                     |
	|       | wanionlib                 | 1.12.2-1.8        | WanionLib-1.12.2-1.8.jar                    | None                                     |
	|       | wawla                     | 2.5.264           | Wawla-1.12.2-2.5.264.jar                    | None                                     |
	|       | waystones                 | 4.0.67            | Waystones_1.12.2-4.0.67.jar                 | None                                     |
	|       | dsurround                 | 3.4.10.2          | DynamicSurroundings-1.12.2-3.4.10.2.jar     | None                                     |
	|       | presets                   | 3.4.10.2          | DynamicSurroundings-1.12.2-3.4.10.2.jar     | None                                     |
	|       | immersiveengineering      | 0.12-86           | ImmersiveEngineering-0.12-86.jar            | None                                     |

**Comment by Tschipp** [comment]
Try removing (make a backup) anything bee/honey related and check if the error persists.

**Comment by Deshiba** [comment]
I suspect unidict might be an issue, since the centrifuge is mainly for honey.

Other then that the bee stuff you have are growthcraft_bees, forestry and harvestcraft. Might be more but try with at least those 3.

**Comment by SirChamomile** [comment]
The plot thickens. Got it to be correct after removing Growthcraft. I'll see if I can't track down what's causing it in Growthcraft. UniDict wasn't actually affecting the recipe either way.

![2018-11-21_15 54 55](https://user-images.githubusercontent.com/23204608/48871186-3fc60c80-eda9-11e8-81cb-a29197a0fa1d.png)

Looks like it has already been reported: https://github.com/GrowthcraftCE/Growthcraft-1.12/issues/48 You could consider closing this unless you want people to see this redirect.

**Comment by Tschipp** [comment]
Ok, will close this.
