### ISSUE TITLE
[FEATURE] DesirePaths compat

### ISSUE THREAD

**Issue by V10lator** [capnkirok/animaniamod#226]
It would be great if animals would see DesirePath grass worn untill a specified level (around 3 to 4 maybe?) as grass and then as dirt. That would i.e. allow them to eat slightly worn grass.

Further mod intercompatibility could even let them set the block from (worn) grass to fully worn grass (IIRC level 6) instead of dirt when eating, so it uses DesirePaths regrow algorithm instead of vanilla. Ofc. there should be fallback to current behaviour if DesirePaths is not installed.

**Comment by Tschipp** [comment]
Sure. I added IGrowable to the default edible blocks.

**Comment by Tschipp** [comment]
Nevermind, read it wrong. Implemented it correctly now.
