### ISSUE TITLE
Version 1.6.2 announces 1.6.0.2 is now available

### ISSUE THREAD

**Issue by instinxx** [capnkirok/animaniamod#228]
### Expected Behavior
1.6.2 has the confidence to stand on its own.

### Actual Behavior
Text chat announces that 1.6.0.2 is available with a download link.

### Steps to Reproduce
Install version 1.6.2 > start game > look in chat

### Version of Minecraft, version of Animania, Single Player or Server
MC1.12.2
Animania 1.6.2
Both SP/MP

### Screenshots encouraged
I have failed to capture this.

**Comment by capnkirok** [comment]
Fixed.
