### ISSUE TITLE
[Feature] Sleeping animals and Item to analyse

### ISSUE THREAD

**Issue by DcNdrew** [capnkirok/animaniamod#23]
Hi!

I think the animals should go to sleep at night. It would be realistic and look cool.

The other thing: You said Waila and so tell you what's up with your animals. Actually I hate those cheap "I know everything about everything just by looking at it" stuffs. I don't use them. I like things to be believable. I'd like to see a tool what can tell you the age of the animals, their needs and stuffs like that. If an animal pregnant and so.

Thank you!

**Comment by capnkirok** [comment]
The sleeping animals feature is on our list, and yeah, we had an idea for something like an Animal Analyzer or an Animal Tag...

**Comment by capnkirok** [comment]
Sleeping animals is added in next release. My god that was hard.

**Comment by capnkirok** [comment]
I'm going to close this. We have an idea for the analysis tool, I just haven't implemented. Thanks again for the suggestion.
