### ISSUE TITLE
Question:How to remove status that shows above animals(water bucket for thirsty,wheat for hungry etc)

### ISSUE THREAD

**Issue by TheFamousPro** [capnkirok/animaniamod#231]
Basically the title says it all I was using animania for some weeks but one day there were water buckets and wheats above the animals head just to inform me what the animals need,but I want to disable that feature.How can I disable it?
![screenshot_2](https://user-images.githubusercontent.com/45349900/48997380-6775f580-f158-11e8-800b-1818d4b0a505.png)

**Comment by Tschipp** [comment]
This is a feature of Dynamic Surroundings, not Animania
