### ISSUE TITLE
[Suggestion] Zebras

### ISSUE THREAD

**Issue by EpicGoldenPig** [capnkirok/animaniamod#24]
Hi, I am here to request an animal - Zebras

Abilities: 
- Spawn in Savanna and Grassland
- Give player 0.5 - 1 heart attack when hitting them
- Drops zebra hide
- Can be tamed same as taming horses, tamed zebra can help player carrying items like vanilla donkeys and mules, tamed zebra will not attack player
- Spawn in herd

Thanks and this is just an idea 😄

**Comment by capnkirok** [comment]
Zebras are on the list (way down there), but I really want to add them :)

**Comment by EpicGoldenPig** [comment]
Can I see the list?

**Comment by Deshiba** [comment]
@capnkirok Maybe it's an idea to put every suggestion that you want to implement on the wiki?
