### ISSUE TITLE
Honey disapearing from beehives when away from them

### ISSUE THREAD

**Issue by jano1221** [capnkirok/animaniamod#244]
### Expected Behavior
Honey is slowly produced in bee hives and it is stored there forever, so i can grab it when i need it.

### Actual Behavior
Honey is produced and stored when somebody is near beehives, when chunks are not loaded all honey disapears.

### Steps to Reproduce
-Put beehive on the ground 
-Wait some time to fill up the hive
-Go somewhere far away from beehive
-Come back to hive and find out that its empty :(

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft ver. 1.12.2
Animania ver. 1.6.2
Server Forge ver. 14.23.5.2772

**Comment by Tschipp** [comment]
On a server?

**Comment by jano1221** [comment]
Yes, it happens on a server. Didnt tried to reproduce it on single player.

**Comment by Fortist** [comment]
Same for single player, btw.
