### ISSUE TITLE
Squids not spawning

### ISSUE THREAD

**Issue by pawelik001** [capnkirok/animaniamod#245]
Hello. I created new world, then i suspected i don't have squids, so I enabled spawning squids in Animania mod config in Minecraft. It enabled, but the squids isn't spawning. In cfg folder in .minecraft it enabled too. In new world squids is spawning, but i don't want to create new world.
In new chunks squids spawning, but chunks i have discovered before i clicked to spawn squids in fresh water, they are not spawning.
Greeting
Paweł

**Comment by pawelik001** [comment]
In new chunks squids spawning, but chunks i have discovered before i clicked to spawn squids in fresh water, they are not spawning.

**Comment by capnkirok** [comment]
Unfortunately, that's the way things work in Minecraft. The initial spawn is when most entities are populated in to chunks (once a player moves into that chunk). There is a mechanism that replenishes entities, but that takes some time (as in many mc days).

**Comment by pawelik001** [comment]
Meh, thank you anyway. :)
