### ISSUE TITLE
[Suggestion] Dohs

### ISSUE THREAD

**Issue by grillo78** [capnkirok/animaniamod#246]
I would like ser mor dogs un Minecraft antes mods like doggy Styles and copious diga didn't get an update for newer versions. If you can make some new dogs for Minecraft will be very nice (sorry for my english)

**Comment by Deshiba** [comment]
Dogs are already planned as an add-on. Keep your eyes open, it might be here one day ;)

**Comment by grillo78** [comment]
Nice,  I'm so excited
