### ISSUE TITLE
IChild API imports but does not use EntityPigletBase

### ISSUE THREAD

**Issue by noobanidus** [capnkirok/animaniamod#247]
Version: current HEAD of the main branch 1.12.

There's an import statement for EntityPigletBase in the IChild class, while the class itself does not use it. While I'm new to the concept of using APIs, I presume this would cause me problems were I to include the API code without the rest of it.

**Comment by Tschipp** [comment]
Yes, you're right, that import is redundant. If you include the api code, just remove the import. I will do the same.
