### ISSUE TITLE
Peafowl don't eat from Trough.

### ISSUE THREAD

**Issue by Kitsufoxy** [capnkirok/animaniamod#25]
### Expected Behavior
Peafowl will eat from trough filled with seeds.

### Actual Behavior
Peafowl remain hungry despite access to a full trough.

### Steps to Reproduce
Please peafowl near full trough. Wait.

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft: Single player, 1.12.2
Animania: 1.4.6

**Comment by zhouyu47** [comment]
Can confirm this is still true in latest release. ( Also with peahens )

**Comment by capnkirok** [comment]
Yeah, just haven't added this yet.
