### ISSUE TITLE
Suggestion:Animal care taker addon

### ISSUE THREAD

**Issue by mser7** [capnkirok/animaniamod#250]
Its just occur to me that most mods with mobs that can take care of animals only focus on vanilla animals(LittleMaidMobs, that-popular-villager-mod), then I suggest an addon, that add in a mob, that will feed and harvest secondary products from Animania animals. The mob itself should be human, or humanoid, it could be a villager, with their big head, when they are idling, they fold their arms, and when do work, unfold it, like Illagers. It shears sheeps, milks cows, collect feathers, eggs from chickens, peacocks, and maybe find truffles with pigs. It could get its work tools and foods for the animals by the player, handling to it via a GUI, the player can also take out the harvests for themself that way.

**Comment by Tschipp** [comment]
Out of scope for the mod, even as an addon. We add animals, not ways for exctracting every resource from those animals.
