### ISSUE TITLE
Serverside Crash nullpointerexception

### ISSUE THREAD

**Issue by Freebi85** [capnkirok/animaniamod#252]
hello :)
This is a Crash Report from a player on my server.

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12.2/ Animania 1.6.2 Serverside

https://hastebin.com/ufizatesey.nginx

**Comment by Tschipp** [comment]
Crash report is somehow empty?

**Comment by Tschipp** [comment]
Closing this...
