### ISSUE TITLE
Hand Feeding Delay Needed

### ISSUE THREAD

**Issue by erebus42** [capnkirok/animaniamod#253]
### Expected Behavior

1. A single right click of the mouse with appropriate food in hand feeds the animal 1 item.
2. Holding right click continuously feeds the animal. (Which I think is the design)

### Actual Behavior

1. A single right click of the mouse with appropriate food in hand feeds the animal 2 items.
2. Holding right click continuously feeds the animal.

I think the issue is that there is not enough of a delay after feeding the animal before it accepts the next item, such that a single right click feeds multiple items.

### Steps to Reproduce
Right click Animania animal with appropriate food in hand.

### Version of Minecraft, version of Animania, Single Player or Server
Currently running:
Minecraft 1.12.2
FTB Revelations 2.6.0
Animania 1.6.2
Single player.

**Comment by erebus42** [comment]
Seems to only happen with wheat. Seeds seem just fine.
My test animals were cows and chickens.

**Comment by Tschipp** [comment]
what animal were you feeding?

**Comment by erebus42** [comment]
So far it just seems to be cows, sheep, and goats. In all three cases I was using wheat.

Draft Horses with wheat though are fine. Chickens with seeds also works as expected.
