### ISSUE TITLE
Animania mobs not spawning in Traverse biomes

### ISSUE THREAD

**Issue by MJRamon** [capnkirok/animaniamod#257]
### Expected Behavior
Mobs in all biomes

### Actual Behavior
Even after cranking up spawn rates, a lot of mobs are spawning in Vanilla biomes, but none in Traverse

### Steps to Reproduce
Install Traverse mod

### Version of Minecraft, version of Animania, Single Player or Server
MInecraft 1.12.2, Animania 1.12.2-1.6.2, Traverse 1.12.2-1.6.0-69, single player

**Comment by capnkirok** [comment]
In order for Animania to recognize Traverse biomes, Traverse needs to be loaded after Animania. I can force this in the code, but also Traverse can do the same, so you might want to bug that author.

**Comment by MJRamon** [comment]
> In order for Animania to recognize Traverse biomes, Traverse needs to be loaded after Animania. I can force this in the code, but also Traverse can do the same, so you might want to bug that author.

Well, looks like it would be great for you to do this!

**Comment by sadad26** [comment]
can you tell me how to do this？please

**Comment by ArkenorOakshadow** [comment]
It would very much be appreciated if this could be done. Traverse biomes are not at all popular when they don't have your animals!

**Comment by Zwikkry** [comment]
This issue is still present. I've been toying with the source code and added it to the dependency list in Animania (with before: and after:) but both don't give the expected result. Is there any way to force Traverse to register these mobs for spawning? The 1.12 version for Traverse has been discontinued so I doubt they will fix it.

**Comment by Asmidus** [comment]
If you can force whatever you need to do in the code for this mod, why not do it? It's been months and this is still a problem and the other mod author has stopped development

**Comment by Asmidus** [comment]
I've also made custom builds of traverse that force it to load before and after animania with no success :/
