### ISSUE TITLE
Vanilla cows don't properly transform into Animania cows

### ISSUE THREAD

**Issue by PT400C** [capnkirok/animaniamod#258]
### Expected Behavior
Every vanilla cow / mushroomcow spawned with a spawnegg will automatically transform into an Animania animal.

### Actual Behavior
Some of the animals transform into Animania animals, but the majority just doesn't spawn (The idle sound plays once so the entity is instanciated by the code).

### Steps to Reproduce
1. Install the latest Animania version
2. Place a cow / mushroomcow with a vanilla spawnegg

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12.2, Animania 1.12.2-1.6.2, Singleplayer

**Comment by capnkirok** [comment]
Actually, what's happening is that if you hit the spawn limit in the config, the animals stop spawning from spawn eggs.

**Comment by Tschipp** [comment]
this feature was removed
