### ISSUE TITLE
Rabbits don't drink from water trough

### ISSUE THREAD

**Issue by Kitsufoxy** [capnkirok/animaniamod#26]
### Expected Behavior
Rabbits will drink from water trough.

### Actual Behavior
Rabbits ignore access to a water trough and remain thirsty.

### Steps to Reproduce
Place rabbit in pen with water trough, wait.

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft Single Player 1.12.2, Animania 1.4.6

**Comment by capnkirok** [comment]
Well, it was debatable whether they should or not. Because we were going to add bowls... but still, I think it's ok for them to drink from troughs.
