### ISSUE TITLE
Liquid in Trough Causes Tile Entities(?) To Render Transparent

### ISSUE THREAD

**Issue by Exorno** [capnkirok/animaniamod#261]
### Expected Behavior
Solid textures on chests/troughs/etc

### Actual Behavior
When water/slop/other liquids (does not happen with Wheat) are in a Trough, nearby troughs, chests, even mud on pigs, will turn transparent when viewed at specific angles (i cannot reproduce a certain angle requirement)

### Steps to Reproduce
Place Trough
Use bucket to put water or slop in trough
Look at Trough from various angles until it turns transparent.

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12.2
Animania 1.12.2-1.6.2 (all 1.6 versions, did not happen in 1.5.1.1)

### Screenshots encouraged
![chest](https://user-images.githubusercontent.com/6111147/50890926-c5853200-13c0-11e9-9231-e0085c0f65c1.jpg)
![pig](https://user-images.githubusercontent.com/6111147/50890927-c5853200-13c0-11e9-8700-200958c0f4aa.jpg)
![trough](https://user-images.githubusercontent.com/6111147/50890929-c5853200-13c0-11e9-8534-9f1240006487.jpg)

**Comment by Exorno** [comment]
I have tested with/without Optifine and with/without my texture pack.  Neither affected the outcome.

**Comment by Exorno** [comment]
The pig mud thing seems to happen whenever it wants to, as well.  With or without a liquid-full trough nearby.

Edit:  apparently rain can fill troughs and i didn't notice it, so this comment might not be accurate

**Comment by Tschipp** [comment]
This is really strange... it has been observed several times, even by myself, but I've never been able to identify any patterns... They seem to appear and go transparent randomly... Did you notice any pattern?

**Comment by Exorno** [comment]
The only pattern I noticed was being nearby, and any nearby trough having liquid in it.  Didn't happen with Seeds or Wheat.    Once I noticed it happening I could zero in on where to look to make it happen, but there wasn't a pattern to where that angle would be.

**Comment by Sandriell** [comment]
Had this happen as well, but it was the wheat trough that was going transparent.

![2019-02-18_02 54 41](https://user-images.githubusercontent.com/10704907/52935922-ba5ee380-3328-11e9-822c-cd5da17e7edc.png)

**Comment by Skrinkus** [comment]
Same issue.

I'm trying to pinpoint it as well as it's very jarring. So far I have only been able to produce this on my server and NOT my singleplayer world.

Things like lightning, [MAGE](https://minecraft.curseforge.com/projects/mage) and [CTM](https://minecraft.curseforge.com/projects/ctm?gameCategorySlug=mc-mods&projectID=267602) seem to exacerbate the problem, but even with those disabled, I still get the render bug, just not as frequently.

not sure if it's render related or even related to this bug, but in certain, seemingly random spots, placing a trough would result in an invisible half block instead.

**Comment by Graywaren** [comment]
I also have this issue, but it isn't just limited to troughs. Chests too etc. And sometimes things just blink in and out to invisible as well (animals will do this but not be transparent). I have a ton of similar visual glitch bugs like this that I've been unable to pinpoint as well. Doesn't seem to be related to optifine.

Note, that I do see this on a single player world... though I do open it to LAN. I'm pretty sure it happens either way though. I also haven't been able to figure out a pattern. The next thing on my list of trying to pin it down is field of view and texture packs. I'm using better vanilla. Anyone else having this issue also using tex packs or not?

**Comment by katubug** [comment]
![unknown](https://user-images.githubusercontent.com/20935286/58424165-703e7a00-805c-11e9-84f6-8473927d3fd2.png)

Same issue. This has happened over several versions and is still present in the current one. The blinking seems to have little rhyme or reason, and the items change from translucent to visible when I move. I do not have OptiFine or a texture pack.

Here are my mod versions:
animania-1.12.2-1.6.2
CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha
forge-1.12.2-14.23.5.2838-universal

Modlist: 
[mods.txt](https://github.com/capnkirok/animaniamod/files/3224016/mods.txt)

**Comment by Tschipp** [comment]
I still can't narrow this down. Has anyone encountered this with *just* animania and craftstudio api?

**Comment by katubug** [comment]
Tested it right now with *only* Animania and CraftStudioAPI, using my previously stated forge version (2838). Fresh install of Animania/CSA so all configs are default.

Started a new creative singleplayer world, gave myself some troughs and placed them down. Everything was fine until I filled one with water, at which point the transparency happened at certain camera angles. I broke that trough, filled another with slop - same issue.

Let me know if there's anything else I can do to help. I could do a screen record if you need video, or if you want any logs or any other information, feel free to ask. I'll do my best to help you nail this down.

**Comment by capnkirok** [comment]
@katabug do you happen to have “fancy spawn eggs” set to true? I think that is currently default. If so, can you turn it off and test again?

**Comment by katubug** [comment]
It is set to false by default, it seems. In any case, it was set to false during my previous test. In the interest of testing, I changed it to "true" and the issue persists.

Edit: Just to be absolutely 100% certain, I changed the config back to false again and restarted the game, created a new world - issue persists.

Edit 2: Here are my configs, if it helps - 
animania.cfg: https://pastebin.com/AT6esp0q
forge.cfg: https://pastebin.com/V33fGYNf

Edit 3: Sorry, one more thing. For what it's worth: during my tests here I've noticed that when I leave the camera in place (with the transparency occurring) and tab out, they will flicker back to opaque after a few minutes, and then sometimes back to transparent after a few minutes more. Idk if that's at all helpful, but more information can't hurt, probably?

**Comment by katubug** [comment]
Here's some basic diagnostic information about my system:
- Windows 7, 64 bit, SP1.
- 16gb RAM, ~7gb allocated to minecraft.
- I have lots of other programs running, including Chrome and Discord.
- I have a NVIDIA gpu (GTX 970, driver version 26.21.14.3136)
- Here's my options.txt: [options.txt](https://github.com/capnkirok/animaniamod/files/3562983/options.txt)

**Comment by Tschipp** [comment]
Thank you for the details. I think I've been able to fix it, but I can't say for sure as I have never been able to reproduce it reliably.

**Comment by katubug** [comment]
Fingers crossed! I saw your ping in discord about the new build, I'll test it out when I can!
