### ISSUE TITLE
Ambiance Mode cows still thirsty

### ISSUE THREAD

**Issue by Fortist** [capnkirok/animaniamod#262]
So, I had turned on Ambiance mode because I was experiencing the "Wont drink water" bug, and I just want better animal models.
But it turns out Cows and calves, at least, still require water. Calves on their own, and Cows when milked.
I havent really checked other animals at this moment
![2019-01-09_10 16 55](https://user-images.githubusercontent.com/5784537/50909318-9a6b0480-13f9-11e9-8ae5-8d6913022e98.png)

**Comment by capnkirok** [comment]
Thanks, will take a look this weekend.

**Comment by Fortist** [comment]
Oh and Goats become thirsty after being milked as well.

Also, in my short modlist they still become thirsty, so Im unsure if it's some mod interaction with one of those mods or ambiance mode actually isnt ambiance mode. Unless after some time the cows become not thirsty, (which after a few hours, didnt happen. at least, calves were stunted.) Pigs seem to work just fine, as they multiply like crazy. Goats too, but when I had milked one for the first time It became thirsty.
