### ISSUE TITLE
Animania serious world blocks ID mess up

### ISSUE THREAD

**Issue by Adam-R-Kaminski** [capnkirok/animaniamod#264]
### Expected Behavior
Not messing up blocks' id's on the server after removal

### Actual Behavior
Messed up blocks id's on the world on the server after removal, even some tree trunks got removed (dynamic trees)

### Steps to Reproduce
Installing this modpack: https://drive.google.com/open?id=1juVv1P7cwBl6Qune3TeXsPNRSHxXVyZv
Making sure that config/embassy/ that there is no file here
Making sure animania is intalled
Making sure modpack is instlaled on forge 2806 1.12.2
Generating a world WITH animania
Closing the world
Removing animania
Entering the world again, tree leaves will be somehow replaced by yellorium blocks and other blocks

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2 forge 2806, animania 1.6.2

### Screenshots encouraged

![2019-01-15_01 57 46](https://user-images.githubusercontent.com/34427698/51179363-87f33e00-18c5-11e9-8e1c-9ecd0cdacbca.png)

![2019-01-14_19 53 45](https://user-images.githubusercontent.com/34427698/51179427-ba04a000-18c5-11e9-9763-6b622c13fe10.png)

PS: Barteks2x, developer of CubicChunks mod says that there is some serious performance issue in this part of the code. Because basically we removed animania from out CubicChunks modpack server becaue it was causing MASSIVE tps drops constantly. After some time of playing server went from 20 to 2-3 tps. And after checking multiple solutions, we removed animania and problem fixed itself.
![zrzut ekranu 288](https://user-images.githubusercontent.com/34427698/51179559-2aabbc80-18c6-11e9-8bac-a855a10cfaab.png)

**Comment by capnkirok** [comment]
Animania does not change BlockIDs, and that problem has not once been raised after 1.5 years of gameplay and > 2mm downloads, so I'm going to guess there's some other mod interaction happening here. 

As for the performance issue, it looks like the EntityAIFindMud is indeed using the old search method, and missed the recent round of optimization, so will update.

**Comment by Adam-R-Kaminski** [comment]
Okay, the issue of blocks replacing was found and should no longer be your concern. Let me know when the issue with performance gets fixed because we'd want to use your mod in our modpack really much, it's awesome!

**Comment by Tschipp** [comment]
I think performance should be a lot better, so I'm closing this.
