### ISSUE TITLE
Honey Issues

### ISSUE THREAD

**Issue by Fortist** [capnkirok/animaniamod#266]
1) Honey disappears even in single player, for both the Hive (nest) and Apiary (hive)
#244
2) You cannot pick up honey with a bottle from any fluid containers.
Ceramic's Barrels, Charset's Tank, this mod's Hive and Apiary.
Though, an odd interaction, when clicking on a Charset tank with enough honey in it, it fills a bucket.

3) Trying to bottle In-world fluid honey gives water bottles.

**Comment by hron84** [comment]
These are actual issues with the honey in the latest version. Also, it should be compatible with Forestry and Rustic, otherwise being fluid is useless. Currently I have no way to get the honey bottles.

**Comment by capnkirok** [comment]
Yes, definitely a bug. Thx.
