### ISSUE TITLE
Cow doesnt give me milk

### ISSUE THREAD

**Issue by Mimiokish** [capnkirok/animaniamod#269]
### Expected Behavior
giving a bucket of milk to me

### Actual Behavior
still an empty bucket

### Steps to Reproduce
feed cow, giving water to the cow, icon says well fed

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12.2 | Animania 1.6.2 | on Server

**Comment by Mimiokish** [comment]
I have water and food for the cow. when right click it gives me nothing. I also have harvestcraft installed. Would that be the problem?

**Comment by capnkirok** [comment]
The cows in Animania don't give milk until they have given birth (like real cows). You can change this in the config if you want.

Is that the problem?

**Comment by Mimiokish** [comment]
> The cows in Animania don't give milk until they have given birth (like real cows). You can change this in the config if you want.
> 
> Is that the problem?

oh, i see. i think that's it. thanks man
