### ISSUE TITLE
Draft mares and stallions summon bug

### ISSUE THREAD

**Issue by Deshiba** [capnkirok/animaniamod#27]
### Expected Behavior
I expect stallions and mares to float in the air like all other animals summoned with the {NoAI:1} tag.

### Actual Behavior
The stallions and mares drop from the sky, foals behave as mentioned above.

### Steps to Reproduce
Summon a stallion or mare in the air without AI
> /summon animania:stallion_draft ~ ~ ~ {NoAI:1}

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12
Animania 1.4.6
Craftstudio 1.0.0.93
Flatcoloredblocks 1.12-6.6

### Screenshots encouraged
![2018-03-21_09 59 05](https://user-images.githubusercontent.com/10565800/37701484-7a530266-2cef-11e8-81dd-8e8af2fe4ce9.png)
![2018-03-21_10 05 22](https://user-images.githubusercontent.com/10565800/37701473-748ce900-2cef-11e8-8358-8158bad7dc9b.png)

**Comment by capnkirok** [comment]
Lol. Horses.

**Comment by Tschipp** [comment]
@capnkirok This: 
```
if (this.isBeingRidden() && !this.isAIDisabled())
{
	this.setNoAI(true);
}
else
{
	this.setNoAI(false);
}
```

In onLivingUpdate. Dunno why it's there so I remvoed it.

**Comment by capnkirok** [comment]
There's a reason for this.... has to do with the custom AI being fired while you are riding an Animania horse. But I should have handled this in the AI and not here.

**Comment by Deshiba** [comment]
I can finally complete my photo booth next patch!
No more horse rain?! 

YES!!!!
