### ISSUE TITLE
Overpopulation without Feeeding

### ISSUE THREAD

**Issue by BigKid1973** [capnkirok/animaniamod#270]
### Expected Behavior
I would not expect animania mobs to overpopulate a chunk without me actively feefing them.
(I:spawnLimitXY=20 for all animals)

### Actual Behavior
Somehow the animal population on my dedicated server with a custom ftb modpack does explode.
It seems to be influenced by the number of animanina animals present. There more there are the worse it's getting. It started with some "wild sheeps" (spawned) and ended with 50+ in the same area.
Once I started breeding other animals it started there too...
Other strange things it that after the last restart of the server there seemed to be almost only male animals left.

### Steps to Reproduce
Unsure. Probably keeping a chunk with some animals of the same kind (male and female) chunkloaded with FTB lib and then also by restarting the server some times.

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12.2
Animania 1.6.2
Dedicated (Forge) Server

**Comment by BigKid1973** [comment]
As a side note: I have the same strange thing going on with gardens from pams hc. Is there probably a bug with entity checking in forge/minecraft/whatever lib is iused?

**Comment by Freebi85** [comment]
Can confirm this too. Especially on servers any config seems to be ignored.
And without FTB Lib.

**Comment by capnkirok** [comment]
On servers, it appears that the spawn limits are being ignored. To be clear, this has to do with spawning, not breeding.

**Comment by BigKid1973** [comment]
Well - activating manual breeding in the config seems to have improved it...  and that would be logical because exceeding the spawn limit should “switch” the animals to manual breeding -  shouldn't it ? Which doesn’t seem to happen automatically (probably because limits are ignored) ? Would that be a possible explanation ?

**Comment by caver115** [comment]
![image](https://user-images.githubusercontent.com/4971734/52058688-91092e00-259a-11e9-9f26-ec2aaa608cbd.png)
Locust, locust everywhere !

**Comment by Freebi85** [comment]
This is a really serious problem. This makes this mod completely unusable for servers.

**Comment by MJRamon** [comment]
Was it fixed?
