### ISSUE TITLE
Oddball crash encountered by a player of my pack

### ISSUE THREAD

**Issue by Sunconure11** [capnkirok/animaniamod#272]
https://paste.dimdev.org/anizadokak.mccrash

Since I don't know how they caused it, this is all I can give.

**Comment by Sunconure11** [comment]
It appears to have some vague connection to TaN, based on experimentation. I will send my current config over shortly.

**Comment by Sunconure11** [comment]
Check this github issue for more info on an attempt at conquering it: https://github.com/Sunconure11/compitum-magia-issues/issues/10

**Comment by Tschipp** [comment]
Don't know about this, closing this
