### ISSUE TITLE
Add in Ducks

### ISSUE THREAD

**Issue by Derpitron** [capnkirok/animaniamod#276]
I have created a farm in my Minecraft world, modelled after one of my childhood bedtime stories. In the stories, there are chickens, cows, pigs, dogs, and ducks. I have the first four sorted out, but Mo' Creatures doesn't really add in any good ducklings. I don't wanna come off as rude or bossy, but may you please consider it? For practical use, you could add in certain eggs, etc. Thanks!

**Comment by HatcheryRoosters** [comment]
There is an animania addon called feathercraft which aims to do that

**Comment by HatcheryRoosters** [comment]
https://discord.com/invite/KsTTJRe

**Comment by Derpitron** [comment]
Hey, just saw the comment now. Thanks for this!

**Comment by HatcheryRoosters** [comment]
There is also Fauna and Ecology (They add genders)

**Comment by HatcheryRoosters** [comment]
Guess what I just found! https://mcreator.net/modification/75625/realfarm

**Comment by Tschipp** [comment]
mcreator mods are bad and should not be used

**Comment by HatcheryRoosters** [comment]
Not all of them are, that one is only a few weeks old, but it has gendered ducks, so this friend will finally have his dream

**Comment by 1235788998753568hfjfu** [comment]
@HatcheryRoosters How can I download feathercraft？thank you!

**Comment by HatcheryRoosters** [comment]
You can't, it's cancelled.

**Comment by HatcheryRoosters** [comment]
Here's my concept for a ducks addon:

Pekin, found in Plains
Rouen, found in Forests
Pormerians, found in Swamps
Opringtons, found in Jungles
Gold, don’t spawn naturally, spawn eggs must be found.

Duck Exclusive Behavior:
* Love to swim around

Other than that, they have generic bird behavior.

Textures are right here:
[ducks.zip](https://github.com/capnkirok/animaniamod/files/7921244/ducks.zip)
