### ISSUE TITLE
Can't obtain special chickens from Chickens with Animania chickens

### ISSUE THREAD

**Issue by mser7** [capnkirok/animaniamod#277]
### Expected Behavior
Installed both Chickens and Animania, when right-clicked on any adult rooster or hen with a special item(book, cake...), the mob transform into the special chicken from Chickens mod, corresponding to the item used(smart, chickenosto...)

### Actual Behavior
Nothing happened

### Steps to Reproduce
Provided above

### Version of Minecraft, version of Animania, Single Player or Server
MC 1.12.2
Animania 1.6.2
SSP

**Comment by mser7** [comment]
https://github.com/setycz/ChickensMod/issues/141

**Comment by Tschipp** [comment]
Animania Chickens extend EntityChicken. There's nothing more that we can do.
