### ISSUE TITLE
Help: OreDictionary for Config

### ISSUE THREAD

**Issue by ElsaTheHobo** [capnkirok/animaniamod#279]
### Version of Minecraft, version of Animania, Single Player or Server
1.12.2, 1.6.2

Hello! Just used the mod for the first time today, and it's awesome! I have a question though: how would I go about using OreDictionary names for animal food in the config? I tried to edit peafowl and chicken food to be much more expansive, but instead they decided that eating is for losers bc I think I broke the config, lol. (I'm not sure about peafowl but chickens are true omnivores. I fed my real life pet chickens pinky mice yesterday and they loved it. I've also seen them attempt to catch rodents in my backyard.)

Here's their entry in the config: (same for chickens)
```
# Food Items that peacocks can eat (use # for meta)
S:peacockFood <
	ore:listAllseed
	ore:listAllfruit
	ore:listAllveggie
	ore:listAllgrain
	ore:listAllberry
	ore:listAllmeatraw
	ore:listAllmeatcooked
	ore:listAllfishcooked
	ore:listAllfishraw
	ore:listAllfishfresh
	ore:listAllnut
	minecraft:melon
	ore:bread
	ore:foodBread
 >
```

Is it not supported, or am I doing something wrong?

Thank you!

**Comment by capnkirok** [comment]
Sorry to say that OreDictionary is not supported here. Right now, you have to type the items in manually....

**Comment by ElsaTheHobo** [comment]
Dang, hope it gets added soon! Good work on the mod, the animals are all
adorable!

**Comment by Graywaren** [comment]
Yea, I really want to see oredict support in the config. When you have lots of mods and items and want to create varied diets for the animals having to put in every item manually makes it extremely time consuming and tedious. I love being able to feed all my animals a variety of items from pam's etc, but it'd be so much easier to do via oredict
