### ISSUE TITLE
[1.12.2-1.4.6] illegal argument exception

### ISSUE THREAD

**Issue by kreezxil** [capnkirok/animaniamod#28]
### Crash Report ###
https://pastebin.com/c61ReCt2

### Expected Behavior
client not to crash when planting a seed

### Actual Behavior
client crashed when planting a seed

### Steps to Reproduce
sadly it's a one-off the player has been unable to reproduce it

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft: 1.12.2-14.23.2.2631
Animania: 1.12.2-1.4.6
Mode: Multiplayer

### Notes ###
Waila which is Hwyla seems to factor heavily into this particular crash, the crash is client side and not server side. I will cross post to Hwyla just in case.

**Comment by TehNut** [comment]
Am I good to close this on my side then?

**Comment by capnkirok** [comment]
Yes @TehNut you can close. Thanks again for the assist.
