### ISSUE TITLE
Crash - Ticking Entity / Salt Lick

### ISSUE THREAD

**Issue by scotty9090** [capnkirok/animaniamod#285]
Crash report is here:

https://paste.dimdev.org/zoxexewaxe.mccrash

MC: 1.12.2
Animania: 1.6.2
Forge:  14.23.5.2807

**Comment by crazygmr101** [comment]
I have had the exact same problem. It was on an aternos server, so I wasn't able to get a crash report.
MC: 1.12.2
Mod: 1.6.2
Forge: 14.23.4.2766

Other Mods:
- Chisel 0.2.1.34
- CraftStudio API universal 1.0.1.95
- Immersive Engineering 0.12-82

**Comment by capnkirok** [comment]
Thanks guys, will take a look. Looks like I need a null check.

**Comment by katubug** [comment]
I had the same issue. I was attacking a Twilight Forest Deer when it happened, not sure if that's related.

animania-1.12.2-1.6.2
forge-1.12.2-14.23.5.2825-universal

https://hastebin.com/eseyeyiwuh.rb
