### ISSUE TITLE
Carry On + Animania Hedgies, Ferrets, Hamsters not working

### ISSUE THREAD

**Issue by Graywaren** [capnkirok/animaniamod#286]
I've posted this to Carry On, but wanted to also post it here

Carry On doesn't seem to be working with these three animania animals. I can pick up animals smaller than them and similar to them, but I can't pick up these three animals which seems wrong to me. They're quite literally animals I can pick up/be pets in real life.... I can't actually pick up a draft horse with my bare hands in real life but I can do it with carry on! Any chance of a fix for this? I love both of these mods and especially the ferrets and hedgies, so being able to move them around easily was something I was looking forward to.

### Expected Behavior
Pick up the ferret/hamster/hedgehog

### Actual Behavior
Does nothing

### Steps to Reproduce
Find an animania ferret/hamster/hedgiehog in world or spawn one, [keybind]+click to attempt to pick up with carry on

### Version of Minecraft, Carry On, Forge
1.12.2, Forge b2805, carry on 1.12.1, animania 1.6.2

Here's the link to the post on CO's github:
https://github.com/Tschipp/CarryOn/issues/155

**Comment by Tschipp** [comment]
Answered on https://github.com/Tschipp/CarryOn/issues/155
