### ISSUE TITLE
Unusual lags with gathering of animals.

### ISSUE THREAD

**Issue by claw4oo** [capnkirok/animaniamod#288]
### Expected Behavior
Not lag/not overbreed

### Actual Behavior
A lot of mobs are occuring in one area, and producing a large amount of server demand

### Steps to Reproduce
Unsure, a lot of mobs in a small area, or several in an area that appears to be isolated from grass/water may be related

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2 Server
1.6.2 Animania

### Screenshots encouraged
https://gyazo.com/9705f13daed245671e51232a90d92077

Attached is the most recent crash lag due to the server falling behind too far.
[crash-2019-02-10_20.46.15-server.txt](https://github.com/capnkirok/animaniamod/files/2849656/crash-2019-02-10_20.46.15-server.txt)

**Comment by claw4oo** [comment]
This may actually be a continuation on a previous post I have, where mobs stuck in small naturally generated ponds generate a lot of lag, and just replicate themselves.

**Comment by Freebi85** [comment]
yes I used the mod one my pack and can confirm that. For some reason the animals ignore the spawn configs and spawn or breed infinitely. 
Completely unplayable for weaker servers
