### ISSUE TITLE
Question: More Spawn Control?

### ISSUE THREAD

**Issue by Graywaren** [capnkirok/animaniamod#289]
I'm wondering if there is a way to blacklist biome types or specific bioimes etc for spawn? For example, being able to say all forests except snowy forests or such. Or to do it by specific biome? Sorry if this has been answered somewhere, but I couldn't find it. If this isn't a current feature, I'd love to see it in the future! Love this mod.

**Comment by BlueCreeper160** [comment]
I see that option in the config file of the mod, but instead of blacklist is whitelist.

**Comment by Tschipp** [comment]
Just use the whitelist config.
