### ISSUE TITLE
[Feature Request] Options to actually replace vanilla animals instead of removing them

### ISSUE THREAD

**Issue by MauveCloud** [capnkirok/animaniamod#29]
Checking in Animania 1.4.7, the options "replaceVanillaChickens", "replaceVanillaCows", etc. say in their descriptions that they actually _remove_ the mentioned animals.  However, there are a few situations, such as Millenaire farms (see https://gitlab.com/Millenaire/Public/issues/70 ), where it would be helpful to have them be replaced instead.  Could we please get this added, either as separate options, or as more advanced options than pure booleans?

**Comment by capnkirok** [comment]
Well, there are two variables that control this:

replaceVanillaCows under GameRules actually removes them (hence the text). I would rename the variables, but then it would throw modpacks etc. off. May do it anyway.

spawnAnimaniaCows under Spawn actually puts the Animania cows int he world.

I used to replace the animals, but this one of the root causes of Over Spawning Armageddon... MC keeps trying to meet the minimum quota of MC animals on so keeps spawning them... which then get replaced etc.

**Comment by MauveCloud** [comment]
Really?  I thought since most of your animals extend the classes of vanilla animals they'd still count towards the passive-mob quota.

**Comment by Tschipp** [comment]
The problem is, that if Millenaire spawns a EntityCow, and those are replaced with animania, it won’t spawn a EntityAnimaniaCow, even though that one extends EntityCow.

**Comment by darthvader45** [comment]
Maybe it needs to be implemented on Millenaire's side, so that it can check if Animania is installed, and if so, use a separate method that spawns Animania animals in the farms.

**Comment by MauveCloud** [comment]
@capnkirok I'm willing to set up a Merge Request for Millenaire to handle it on that side, but I could use a little help.  See edit to previous comment.

**Comment by MauveCloud** [comment]
Okay, I figured this out on my own and set up a Merge Request for Millenaire, so I'm closing this now.

**Comment by capnkirok** [comment]
Thank you for the follow-up. I have been super busy in my new job lately, finally starting to catch up.
