### ISSUE TITLE
Picking up a vanilla animal with Carry On and putting it down spawns an Animania animal

### ISSUE THREAD

**Issue by DogResidue** [capnkirok/animaniamod#290]
### Expected Behavior
I expected that when I picked up a vanilla animal and put it down, it would just be the vanilla animal.

### Actual Behavior
When I pick up a vanilla animal with Carry On and put it down, it both places the vanilla animal and spawns an Animania animal. For example, when I pick up a vanilla baby Mooshroom and put it down, it spawns a Friesian cow.

### Steps to Reproduce
1. Pick up a vanilla animal with Carry On.
2. Place it back down.
The vanilla animal will be there as well as an Animania animal of the same kind.

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12.2
Animania 1.6.2
Carry On 1.12.1
Single Player

### Screenshots encouraged
The baby Mooshroom
![2019-02-13_13 49 44](https://user-images.githubusercontent.com/32424783/52735826-6bb2f180-2f96-11e9-8f7a-0049a860774a.png)
Picking it up
![2019-02-13_13 49 49](https://user-images.githubusercontent.com/32424783/52735827-6bb2f180-2f96-11e9-86d7-0a97f4a652d5.png)
After placing it down, the Mooshroom is there as well as an Animania cow (don't mind the particles)
![2019-02-13_13 49 54](https://user-images.githubusercontent.com/32424783/52735828-6c4b8800-2f96-11e9-882b-b2a8e4d07d52.png)

**Comment by Deshiba** [comment]
I've never had this issue and I've moved lots of mooshroom calfs with carryon. This might be a compatibility issue with another mod, can you include your modlist?


Also that's a baby mooshroom from animania, not so much vanilla.

**Comment by Tschipp** [comment]
Yes, please include a modlist. And yes, it is a vanilla mooshroom.
