### ISSUE TITLE
Animals sleeping AI is messed up

### ISSUE THREAD

**Issue by mser7** [capnkirok/animaniamod#291]
I tried to turn on sleeping, but the night come and I suffer from the usual tick lag, so I turn it off, and when I visit my chicken coop at noon the next day, I see them, still sleeping

MC 1.12.2
Animania 1.6.2
SSP

![2019-02-14_23 34 08](https://user-images.githubusercontent.com/22555489/52803735-3c46d680-30b5-11e9-90f8-6b4494af8c02.png)
![2019-02-14_23 34 40](https://user-images.githubusercontent.com/22555489/52803737-3c46d680-30b5-11e9-962b-3e16c2664c77.png)9-02-14_23.34.40.png…]()

**Comment by mser7** [comment]
Not only those two, but the test of them were day sleeping too

**Comment by Tschipp** [comment]
If you turn off sleeping while they're sleeping, they won't wake up. Punch them to wake them up.
