### ISSUE TITLE
Animals won't spawn

### ISSUE THREAD

**Issue by Darkblazemaster** [capnkirok/animaniamod#294]
I downloaded a version of the mod that according to Curseforge was compatible with 1.11 (I made the world a while ago and have steadily been adding mods and I'm cautious about putting the world on a new version with newer mods)  but the game didn't launch properly, saying it was an incompatible version and now mobs do not spawn in any of the worlds I have, naturally or from eggs, mobs from other mods work just fine though. I'm new to modding and just kind of throw things together that say they're compatible so I'm not sure what to do so sorry if this is a stupid question.

Thanks

**Comment by BlueCreeper160** [comment]
well, the animals just only spawn in chunks loaded after the mod was installed, you can create a new world, load new chunks or remove the loaded chunks removing mca files (if you don´t know of mca files, don't delete anything)

**Comment by Tschipp** [comment]
We don't support 1.11 anymore.
