### ISSUE TITLE
Having hard time to unified milk with crafttweaker

### ISSUE THREAD

**Issue by MeedoWorld** [capnkirok/animaniamod#295]
Hello , I'm trying to unified all milk to be normal vanilla milk with crafttweaker if you can add an option that we can all animals give Vanilla milk it will be very helpful especially for skyblock type modpacks when vanilla milk is very important to spawn slimes with barrel filled with milk + mushrooms omg i think i got idea could work! while typing this issue lol why we not adding animalia milk to barrel recipes lol
anyway great mod keep good work!

**Comment by capnkirok** [comment]
Well, you can already put a bucket of animania milk into a crafting table and it becomes a bucket of vanilla milk.

In addition, the milks are listed in OreDictionary using the same naming conventions as HarvestCraft (e.g., listAllMilk).

Let me know if your idea works.

**Comment by MeedoWorld** [comment]
Thanks for your reply , I know i tried that vanilla bucket works but clay bucket( ceramic mod) filled with animania milk doesn't work in addition animalia milk doesn't have a OreDictionary names forge lists it as NBT tags and I don't know how to list an NBT tagged item  clay bucket milk under new Oredictinoary name , i solved it with going to Ex nihilocreato mod config files and added all animalia milk to barrel to be able to create slime .. i suggest is to add options for skyblock type modpack such as all animals produce vanilla milk and add baits (same as Ex Compressum mod) so player be able to spawn animalia mobs in Void easily i am still working on how make animalia fits perfectly in my skybloock modpack..
i will let you know more if i find more issue ... thanks for your time

**Comment by MeedoWorld** [comment]
Thanks for your reply , I know i tried that vanilla bucket works but clay bucket( ceramic mod) filled with animania milk doesn't work in addition animalia milk doesn't have a OreDictionary names forge lists it as NBT tags and I don't know how to list an NBT tagged item  clay bucket milk under new Oredictinoary name , i solved it with going to Ex nihilocreato mod config files and added all animalia milk to barrel to be able to create slime .. i suggest is to add options for skyblock type modpack such as all animals produce vanilla milk and add baits (same as Ex Compressum mod) so player be able to spawn animalia mobs in Void easily i am still working on how make animalia fits perfectly in my skybloock modpack..
i will let you know more if i find more issue ... thanks for your time
