### ISSUE TITLE
Soft Compat/ Maven Repo

### ISSUE THREAD

**Issue by Justen-N** [capnkirok/animaniamod#296]
### Expected Behavior
Alright, I've been working on compatibility issues from Minecolonies end, and it comes down to not having a soft dependency available for us to build from. We don't want to force everyone who downloads Minecolonies to also have Animania. Is it all possible for you to set up a Maven repo? Or Raycoms, one of our senior devs, has offered to let you use our build system, which includes a maven repo. Either way, We'd like to work with you on this.

**Comment by Tschipp** [comment]
We have plans to set up a maven repo, we just haven't had the time. The mod is gonna be heavily restructured, so it will probably happen after that.

**Comment by Tschipp** [comment]
Thanks to Jared, we now have Animania on maven: https://maven.blamejared.com/com/animania/
