### ISSUE TITLE
Doesn’t show mob drops with Just Enough Resources

### ISSUE THREAD

**Issue by Dimentive** [capnkirok/animaniamod#298]
I’m using Animania (v1.6.2) and [Just Enough Resources](https://minecraft.curseforge.com/projects/just-enough-resources-jer) (v0.8.10.50), playing the [Enigmatica 2](https://minecraft.curseforge.com/projects/enigmatica2) modpack (Minecraft 1.12.2).

When clicking on a mob drop from Animania, it doesn’t tell me what mobs drop it, which Just Enough Resources is supposed to do. I’m not sure if this is an issue on JER’s end or Animania’s end.

**Comment by MizuNomy** [comment]
JER's end

**Comment by Tschipp** [comment]
As SuperPawmaple said.
