### ISSUE TITLE
How to Configurate what animals drop

### ISSUE THREAD

**Issue by Surac** [capnkirok/animaniamod#299]
### Expected Behavior
I expect to find a section in the config file where i can list what is droped by each animal

### Actual Behavior
There is no hint in the config how to config what is droped

### Steps to Reproduce
just install, run and look in the config file

### Version of Minecraft, version of Animania, Single Player or Server
MC 1.12.2 
Animania animania-1.12.2-1.6.2.jar
Single and Multiplayer

**Comment by Surac** [comment]
found this in the code :(

```
	@Config.LangKey("Animania")
	public static CommonConfig.GameRules gameRules = new CommonConfig.GameRules();
//	public static CommonConfig.Drops drops = new CommonConfig.Drops();
        public static CommonConfig.Spawn spawn = new CommonConfig.Spawn();
```

**Comment by Graywaren** [comment]
Agreed. Documentation references an ability that isn't there.

**Comment by zerafox** [comment]
I just went looking for this option myself, didn't find it either.

**Comment by MizuNomy** [comment]
Hello, there is currently no configuration to that. I think its good to recommend that on the discord server for Animania.

**Comment by Tschipp** [comment]
The documentation is heavily outdated currently. You can configure the drops by editing the loottable. It works like a vanilla loottable.
