### ISSUE TITLE
Animania babies don't grow up when in The Midnight

### ISSUE THREAD

**Issue by PurpleHel** [capnkirok/animaniamod#303]
### Expected Behavior
Baby Animals grow up regardless of dimension

### Actual Behavior
Baby animania animals growing timer doesn't update in at least one other dimension, The Midnight. https://minecraft.curseforge.com/projects/the-midnight
I didn't test in other dimensions.

### Steps to Reproduce
Go to The Midnight
Find a baby animal
check its grow timer
wait a few
check grow timer again

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12.2
Animania 1.6.2
Singleplayer

### Screenshots encouraged
Will edit when I have screenshot.

**Comment by Tschipp** [comment]
This is a known compat issue, because animals only grow during the day. This also happens in twilight forest.

**Comment by capnkirok** [comment]
I had no problem growing Animania animals in the midnight. I think you might using a version of HWYLA that shows a Minecraft growth timer. Animania does not show a growth timer and doesn't use Minecraft's timer.

To test this for yourself, go into the Care and Feeding config, and change the childGrowthTick value to something like 5 or 6. Then spawn a baby animal in the midnight and you'll see it grow in front of you.
