### ISSUE TITLE
Frame lag when looking at sleeping sheep

### ISSUE THREAD

**Issue by crazygmr101** [capnkirok/animaniamod#304]
### Expected Behavior
Normal frame rate when looking at sheep.

### Actual Behavior
Frame rate drops from ~60(capped) to 10-15, sometimes lower.

### Steps to Reproduce
Get a lot of sheep, wait till night, then look at them.

### Version of Minecraft, version of Animania, Single Player or Server
Animania 1.6.2
Forge 1.12.2 14.23.4.2766
8GB RAM Allocated
Server

**Comment by capnkirok** [comment]
Will take a look. There's a ton of animation happening here, but that shouldn't drop frame rate by that much.

Noting that this is a Server.

**Comment by Tschipp** [comment]
Not able to replicate
