### ISSUE TITLE
Exception ticking world crash when raining on trough

### ISSUE THREAD

**Issue by vediis** [capnkirok/animaniamod#306]
### Expected Behavior
Trough collects rainwater

### Actual Behavior
Crash

### Steps to Reproduce
Have trough placed with water while raining

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12.2, Animania 1.3.6, Forge 2387 server

[crash-2019-04-07_21.44.46-server.txt](https://github.com/capnkirok/animaniamod/files/3052653/crash-2019-04-07_21.44.46-server.txt)

**Comment by capnkirok** [comment]
This was fixed in version 1.3.6.1 which was a looooooong time ago :)
