### ISSUE TITLE
Baby animals not growing up at all

### ISSUE THREAD

**Issue by PlayingDino** [capnkirok/animaniamod#307]
### Expected Behavior
baby animals to grow

### Actual Behavior
staying babies

### Steps to Reproduce
???

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2, 1.12.2, single player

### Screenshots encouraged
![2019-04-23 (1)](https://user-images.githubusercontent.com/49927583/56624487-108d2300-6607-11e9-9837-5af361e185fa.png)

**Comment by MizuNomy** [comment]
Hello, the version of what u stated needs to be renew as Animania now only support 1.12.2 version and there are multiples update so far. Hwyla is a mod you can sneak and see animals growth (Ticks).

**Comment by Tschipp** [comment]
Can't reproduce.

**Comment by crazyirishwrencher** [comment]
I am having similar issue but only with chicks. Time to grow never changes. Happens with chicks that spawn from nest eggs and from the spawn random chicken item.

**Comment by capnkirok** [comment]
Time to grow is a Minecraft data point, not used by Animania. You are using some tooltip mod that is showing you useless/wrong info. The chicks are growing fine :)
