### ISSUE TITLE
Request: Compat with Quark Poisonous Potato Baby Animal Tweak

### ISSUE THREAD

**Issue by Graywaren** [capnkirok/animaniamod#308]
I adore animania and really enjoy having wee babies around on my farm. There are times, esp when trying to avoid overcrowding by managing breeding, where I'd really like to have a permanent baby animal. Quark has a tweak where you can feed a poisonous potato to a baby animal and if it becomes poisoned by the potato it will stop growing. I've tested it with animania babies and while a baby animal will show that it takes damage when the potato works (it's some percent chance of happening so sometimes it takes a bunch of potatoes) the animal still continues to grow. I'd really love if animania animals could be compatible with this. Let me know if this is a thing where it's quark that'd need to add the compatibility and I'll head over to that forum with the request.

**Comment by Tschipp** [comment]
This is on quark to implement.
