### ISSUE TITLE
Why are there so many Rabbits in my server? 

### ISSUE THREAD

**Issue by SihenZhang** [capnkirok/animaniamod#309]
**Minecraft Version**: 1.12.2
**Forge Version**: 14.23.5.2836
**Mod Version**: 1.6.2
**Singleplayer/Multiplayer**: Multiplayer
**Description**:
There are **so many rabbits** in my server which cause lag, reduce tps and crash the server.
Here is the crash report: https://paste.ubuntu.com/p/M2bSdkffBP/
Also, I use Sampler Mod to export sampling data, Here are [the first one](https://drive.google.com/open?id=1HZugBEU6QmhIfRYejjgdQ-UWfrNoO_Oi) and [the second one](https://drive.google.com/open?id=1jvwHsRp0eZZD02ywTVBVHxWS4dDilR1z). 
![image](https://user-images.githubusercontent.com/20498895/56858241-944d6380-69a9-11e9-915e-09ea61b62636.png)
![image](https://user-images.githubusercontent.com/20498895/56858236-84ce1a80-69a9-11e9-9420-f45969c5c9c4.png)

**Comment by Tntdruid** [comment]
Thats a lot of 🐰

**Comment by Freebi85** [comment]
Same problem with all kinds of animals. Depends on the Biome.
I'm not sure that's ever fixed. It's been reported for months.
https://github.com/capnkirok/animaniamod/issues/270

**Comment by MizuNomy** [comment]
Hello, Please go to configuration and test? Are you installing this mod only?


Updated: This has something to do with the coding of this mod. (Spawning Issue) (Bug)

**Comment by capnkirok** [comment]
We found a problem with rabbits in particular. It was a code issue. That doesn't explain the other animals overspawning, but Rabbits will spawn more reasonably in the next update.

**Comment by capnkirok** [comment]
So, fixed in next release
