### ISSUE TITLE
pls make it in Dutch languege

### ISSUE THREAD

**Issue by Kippenkomeet** [capnkirok/animaniamod#31]

**Comment by Deshiba** [comment]
There is a Dutch .lang file...

**Comment by MauveCloud** [comment]
I think something went wrong with the Dutch .lang file.  I don't understand Dutch myself, but look at https://github.com/capnkirok/animania/blob/master/nl_NL.lang and compare with https://github.com/capnkirok/animaniamod/blob/1.12/src/main/resources/assets/animania/lang/nl_NL.lang

**Comment by Kippenkomeet** [comment]
how to instal?

**Comment by capnkirok** [comment]
I’ll have to fix it in the next update..

**Comment by Deshiba** [comment]
I'll see if I can update the langfile before then (its outdated)

**Comment by capnkirok** [comment]
@Deshiba I removed the HTML garabage that was in there and replaced with the latest file I had, but still needs updating:
https://github.com/capnkirok/animaniamod/blob/1.12/src/main/resources/assets/animania/lang/nl_NL.lang
