### ISSUE TITLE
Feature request: Ability to confine mammals to small areas in ambient mode

### ISSUE THREAD

**Issue by Derpitron** [capnkirok/animaniamod#311]
I've created a model farm, but my animals keep wandering all around the place, and I can't keep track of them! I've set the config to ambience mode so that they don't need to eat or drink, but I can't tie the animals to a lead all the time. I could definitely do something like this with custom NPCs, but I would like a better solution. I know it goes against the core purpose of the mod, but I would like it for the sake of creative mode farms. Thanks!

**Comment by Tschipp** [comment]
Use... fences?
