### ISSUE TITLE
Animania breaks Mob spawning for Latest ZAWA (1.6.0)

### ISSUE THREAD

**Issue by JoelZBub** [capnkirok/animaniamod#313]
### Expected Behavior
I wanted to use Animania 1.6.2 and ZAWA 1.6.0 together in a modpack and both would retain their spawn weights and biomes as configured in their respective config files. (ZAWA's spawn mechanics were recently reworked and tested extensively prior to release.) 

### Actual Behavior
When Animania is installed, some Zawa mobs that have very low weights and MaxGroup values spawn out of control. Here are pics of the entity zawa:hawksbillseaturtle (which during beta testing was found to spawn very sparsely) spawning wildly. 

ZAWA's broken code has been reworked for 1.6.0 and spawn rates test to work correctly by itself.

### Steps to Reproduce
Install Animania 1.6.2, CraftStudio 1.0.1.95-1.12beta, Biomes O Plenty 7.0.1.2419, zawa 1.6.0, and Bookworm 2.2.0(1.12.2)
Savanna biome is the easiest to see the issue.  Swampland is another.

### Version of Minecraft, version of Animania, Single Player or Server
Forge 1.12.2 -14.23.5.2816 or similar
Animania 1.12.2

### Screenshots encouraged
World loaded with Biomes O Plenty and ZAWA:
![2019-05-04_17 26 02](https://user-images.githubusercontent.com/12024500/57186371-d1cf5680-6eab-11e9-9d2a-08506303a447.png)

Fresh world, same seed, loaded with Animania, Biomes O Plenty and ZAWA:
![2019-05-04_17 08 04](https://user-images.githubusercontent.com/12024500/57186375-ec093480-6eab-11e9-84ed-489e559acc31.png)

**Comment by JoelZBub** [comment]
I know it's unlikely this will get addressed. This report is here for all the people that keep reporting this as an issue to zawa.

`public static final String DEPENDENCIES = "required-after:craftstudioapi;before:zawa;`

**Comment by viveleroi** [comment]
Are there any work-arounds other than: removing either mod or disabling specific creatures (`zawa:hawksbillseaturtle` is a huge problem for us too, murdering FPS and requiring `/kill` )?

From what I've read the mods just blame each other and appear unwilling to fix.

**Comment by JoelZBub** [comment]
~~Currently the only solutions are those stated above, until Animania resumes development of their project.~~  SEE BELOW
Whatever caused Animania to decide to add zawa to their DEPENDENCIES list in their code has most likely been re-worked on zawa's end. (The prior zawa water spawn code was broken, as stated in my original post.)
At this point, in the absence of a response from Animania, little can be done to resolve compatibility.

**Comment by JoelZBub** [comment]
UPDATE:
This issue has the following workaround:
In animania.cfg set `B:spawnFreshWaterSquids=true`
In ZAWASpawnConfigurations.cfg remove all land biomes for `hawksbillseaturtle`

**Comment by viveleroi** [comment]
Interesting, do you know why that's a workaround?

**Comment by StarGlade** [comment]
> UPDATE:
> This issue has the following workaround:
> In animania.cfg set `B:spawnFreshWaterSquids=true`
> In ZAWASpawnConfigurations.cfg remove all land biomes for `hawksbillseaturtle`

THANK YOU SO MUCH. I made an account for the sole purpose of thanking you, because you saved my sanity. I never would have figured that out on my own. Works perfectly.

**Comment by capnkirok** [comment]
Finally going through these bugs. The solution makes absolutely no sense to me. Why on earth would these two things fix the spawning rate of Zawa creatures? 

What would Animania have anything to do with Zawa spawning? Any insights?

**Comment by Tschipp** [comment]
> `public static final String DEPENDENCIES = "required-after:craftstudioapi;before:zawa;`

I don't even remember putting that there... I have no idea how these things conflict...

**Comment by JoelZBub** [comment]
Keep an eye out for ZAWA 1.7.0 
It Appears that SoggyMustache has adjusted his code and this is resolved. 
I'll leave this open until an actual release.

**Comment by Tschipp** [comment]
Good to hear.

**Comment by capnkirok** [comment]
I've removed the 'dependency' on Zawa. It's actually not a dependency... I just wanted it to load after Zawa bc custom entity mods mess with NBT Data, which was causing crashed at some point long ago, but that has been fixed. 

In next release.
