### ISSUE TITLE
Ghost entity?

### ISSUE THREAD

**Issue by washinoboku** [capnkirok/animaniamod#315]
I have this 2x2 area that i tried to fill up with dirt but I can't. I can stand in the spot where I cannot place blocks. I can place blocks next to this spot, above this spot, and below this spot but not in this spot. I can have gravel and sand drop into the spot, and I can remove the gravel and sand as usual, but I can't place dirt, wood, stone or any other solid block. I can place both lava and water in the spot and remove the liquid with a bucket, but not by replacing the source block with a solid block except by dropping sand or gravel. If I let sand or gravel down and unload the area, when I come back few minutes after some cows are suffocating under the fallen blocks. If I let the spot empty some cows spawn back and leave the spot but I can't place blocks either.

Animania 1.6.2, Minecraft 1.12.2 on small custom modpack

**Comment by MizuNomy** [comment]
It sounds more like a glitch randomly happened

**Comment by capnkirok** [comment]
@washinoboku is this running on a server?

**Comment by Tschipp** [comment]
Never encountered anything like this... please press F3 + B to see hitboxes of entities and tell me if an entity is there.

**Comment by washinoboku** [comment]
It was a glitched cow that I solved with MCEdit. Just deleted the block who glitch the cow and the cow itself. I think was a bad mod interactions.
Never try to reproduce it, but I remeber filling an area with the construction wand from extrautilities 2 and suddenly at the same time, a cow walk directly in the space was filled with the wand. The cow dies suffocated and everytime the chunk was loaded, the cow returns and dies.

**Comment by Tschipp** [comment]
I'm going to close this as a one-off weird issue that isn't really reproducible.
