### ISSUE TITLE
[1.6.2] 'B:showUnhappyParticles=false' does not work

### ISSUE THREAD

**Issue by ilvrak** [capnkirok/animaniamod#316]
### Expected Behavior
needs-icons above animals are not displayed

### Actual Behavior
config option 'B:showUnhappyParticles=false', but needs-icons above animals still displayed.

### Steps to Reproduce
load minecraft with 'B:showUnhappyParticles=false'
spawn animania animals with spawn-eggs
wait until animals become unhappy
see above unhappy animals

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2, 1.6.2, SP

### Screenshots encouraged
![image](https://user-images.githubusercontent.com/16130834/57620943-c6231480-75bc-11e9-925a-4e08de305c05.png)

**Comment by ilvrak** [comment]
Addon 'Mob-Info' is not installed

**Comment by MizuNomy** [comment]
Dynamic Surrounding is recreating that I think :?

**Comment by ilvrak** [comment]
Oh, thank you! it turns out dsurround was a config for this, but I did not know!
