### ISSUE TITLE
Trailmix conflict

### ISSUE THREAD

**Issue by Explode007** [capnkirok/animaniamod#317]
### Expected Behavior
Animania pig would fly out of trailmix launchers

### Actual Behavior
Spawns 2 pigs and launcher stops working, no effects

### Steps to Reproduce
Trail mix mod
Animania
Use launcher, Expect flying pigs
Get normal pig spawns

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12 both single player and server
Latest forge verion 14.23.5.2838
Animania latest - 1.6.2
Trail Mix - 7.0.0

**Comment by capnkirok** [comment]
You can set 'Replace Vanilla Pigs' to false in the config under Game Rules for this one to work.
