### ISSUE TITLE
Bugged texture of some placeable objects

### ISSUE THREAD

**Issue by HonzaVinCZ** [capnkirok/animaniamod#318]
### Actual Behavior
Some models has bugged texture. The bugged texture appears just from some angles.

### Steps to Reproduce
I just placed objects on the ground and then moved around, objects texture was glitching.

### Version of Minecraft, version of Animania, Single Player or Server
- 1.12.2 SP
- Animania 1.12.2 1.6.2
- CraftStudioAPI universal 1.0.1.95 mc1.12 alpha
- Forge 14.23.5.2768
- OptiFine 1.12.2 HD U E3

### Screenshots encouraged
[
![2019-05-21_12 23 37](https://user-images.githubusercontent.com/29098779/58089618-8f08c080-7bc5-11e9-974f-b9b27da75478.png)

![2019-05-21_12 23 39](https://user-images.githubusercontent.com/29098779/58089619-8fa15700-7bc5-11e9-8a42-140104d0603d.png)

![2019-05-21_12 23 54](https://user-images.githubusercontent.com/29098779/58089621-8fa15700-7bc5-11e9-94b6-c40869428630.png)

![2019-05-21_12 24 22](https://user-images.githubusercontent.com/29098779/58089623-8fa15700-7bc5-11e9-9b35-0b82fb748298.png)

](url)

**Comment by MizuNomy** [comment]
It is a bug. Think it will be confirmed soon.

**Comment by Tschipp** [comment]
It's a mod incompatibility with *some* other mod. But I don't remember what mod, please post your modlist.

**Comment by katubug** [comment]
Hi, I'm not the original poster but I am also having this issue. Here is a link to my pack's modlist: http://enthusiasticraft.cf/modpack-update-1-5-0/#modlist
