### ISSUE TITLE
Food Not Appearing

### ISSUE THREAD

**Issue by Nightfire731** [capnkirok/animaniamod#319]
This issue is happening on a 1.12.2 server - for some reason, meats specific to animal breeds aren't appearing - Raw Pork (Duroc), for instance, doesn't appear, but Raw Prime Pork and other Prime meats do show up. We've checked all the configs, but aren't sure why this is happening; I assume they are still part of the mod and cannot find anything in changelogs where they were removed.

**Comment by MizuNomy** [comment]
Hello, currently the mod has both raw porkchop and raw prime pork for any pig drops. Raw porkchop only happens to drop for certain pig. And yes Raw Prime Pork is for Duroc pig. A few updates agi specific meat drop has been removed to reduce complication.  (before 1.6.1)

**Comment by capnkirok** [comment]
@SuperPawmaple is correct, we phased breed specific meats out a few versions ago
