### ISSUE TITLE
[1.12] Chickens not reading NBT properly after Interaction w/Carry On

### ISSUE THREAD

**Issue by Tschipp** [capnkirok/animaniamod#32]
When chickens are picked up with CarryOn and placed down again, they become thirsty. Something about the readNBT is wrong. 
From https://github.com/Tschipp/CarryOn/issues/89

**Comment by capnkirok** [comment]
Bug was here... one of those WTF was I thinking when I wrote this code moments:
![image](https://user-images.githubusercontent.com/9628379/38435595-6215cf90-39d2-11e8-8d06-c1856aeb2a99.png)
