### ISSUE TITLE
Does disabling animania Horse spawn disables all horses?

### ISSUE THREAD

**Issue by Nemeruis** [capnkirok/animaniamod#322]
I didnt want to use animanias horses. Does disabling their spawn affects minecraft horses too?

**Comment by Nemeruis** [comment]
btw the reason is animanias horses dont have animations look a bit weird

**Comment by MizuNomy** [comment]
Hello, from what I know Animania Draft horse does not replace Vanilla Horse at all. If you would like to see more Vanilla horse. I think configure your config for the mod is a solution! ;)

Yes. Animania Draft Horse does not have complex animation for jumping and running :3 But sleeping yes and its beautiful.
