### ISSUE TITLE
JEI+Chocapic shader+Animania = white screen

### ISSUE THREAD

**Issue by DcNdrew** [capnkirok/animaniamod#324]
### Expected Behavior
Normal JEI

### Actual Behavior
https://imagebin.ca/v/4lpWywsuSyRr
Well, it's even worse, because I saw the whole screen white.

### Steps to Reproduce
Install Animania, JEI and Chocapic's medium Shader, but I didn't try without the last.

**Comment by MizuNomy** [comment]
Could be JEI or Chocapics?

**Comment by Tschipp** [comment]
And this is an animania issue how?

**Comment by capnkirok** [comment]
Our build space includes JEI, so it's not JEI.  It's an interaction with the Shader and the fancy spawn eggs. If you want to use this shader, I'd recommend turning Fancy Spawn Eggs to false in the config. Or you can report this to the shader dev.
