### ISSUE TITLE
Texture is not loading; crashing after a while (Multiplayer Server)

### ISSUE THREAD

**Issue by WickyPlays** [capnkirok/animaniamod#328]
As the title says, my client just got crashed after joining the Animania server. I previewed the log, it might be something about Rendering Exception. It works really fine on Singleplayer 

I'm using 1.12.2 and I do have CraftStudioAPI too (both are in the latest version)

Here is the log:
[crash-2019-07-11_20.33.54-client.txt](https://github.com/capnkirok/animaniamod/files/3382278/crash-2019-07-11_20.33.54-client.txt)

**Comment by MizuNomy** [comment]
I think it has nothing to do with the mod at all.

**Comment by capnkirok** [comment]
This is not animania related, has to do with mods not matching on server and client
