### ISSUE TITLE
[REQUEST] Profile the mod and nuke lag once and for all

### ISSUE THREAD

**Issue by Sunconure11** [capnkirok/animaniamod#329]
As lag is a known issue with this mod, I would suggest you run it through VisualVM or something similar, and take it from there.

**Comment by Sunconure11** [comment]
https://github.com/capnkirok/animaniamod/issues/165

**Comment by capnkirok** [comment]
I've profiled it many times before. Needs another sweep, tho. Sleep and Water both problems on servers in particular.

**Comment by capnkirok** [comment]
Just out of curiosity, are you using a WorldBorder?

**Comment by Sunconure11** [comment]
No, I am not using a world border.

**Comment by Tschipp** [comment]
Gonna close this as we have improved performance a lot lately and I haven't heard many more issues with this
