### ISSUE TITLE
Cheese Mold/Milk Entity causes server to fail to launch

### ISSUE THREAD

**Issue by wolfgangrumpf** [capnkirok/animaniamod#33]
Hey, using the latest 1.12 Forge and had everything working great. Then on the latest system maintenance, the server wouldn't start up again, and it appears to have something to do with animania and cheese molds, or maybe milk? Here's the crash report

---- Minecraft Crash Report ----

WARNING: coremods are present:
AppleCore (AppleCore-mc1.12.2-3.1.0.jar)
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 4/3/18 3:16 PM
Description: Ticking block entity

java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class com.animania.common.blocks.BlockCheeseMold$EnumType, values=[empty, holstein_milk, holstein_cheese, friesian_milk, friesian_cheese, goat_milk, goat_cheese, sheep_milk, sheep_cheese, water, salt, jersey_milk, jersey_cheese]} as it does not exist in BlockStateContainer{block=projecte:collector_mk2, properties=[facing]}
at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)
at com.animania.common.tileentities.TileEntityCheeseMold.func_73660_a(TileEntityCheeseMold.java:134)
at net.minecraft.world.World.func_72939_s(World.java:1832)
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Server thread
Stacktrace:
at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)
at com.animania.common.tileentities.TileEntityCheeseMold.func_73660_a(TileEntityCheeseMold.java:134)

-- Block entity being ticked --
Details:
Name: minecraft:tileentitycheesemold // com.animania.common.tileentities.TileEntityCheeseMold
Block type: ID #855 (tile.pe_collector_MK2 // moze_intel.projecte.gameObjs.blocks.Collector)
Block data value: 1 / 0x1 / 0b0001
Block location: World: (184,51,94), Chunk: (at 8,3,14 in 11,5; contains blocks 176,0,80 to 191,255,95), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Actual block type: ID #855 (tile.pe_collector_MK2 // moze_intel.projecte.gameObjs.blocks.Collector)
Actual block data value: 1 / 0x1 / 0b0001
Stacktrace:
at net.minecraft.world.World.func_72939_s(World.java:1832)
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)

-- Affected level --
Details:
Level name: world
All players: 0 total; []
Chunk stats: ServerChunkCache: 625 Drop: 0
Level seed: 6681740261224929173
Level generator: ID 00 - default, ver 1. Features enabled: true
Level generator options:
Level spawn location: World: (256,64,200), Chunk: (at 0,4,8 in 16,12; contains blocks 256,0,192 to 271,255,207), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Level time: 11756661 game time, 11871696 day time
Level dimension: 0
Level storage version: 0x04ABD - Anvil
Level weather: Rain time: 62333 (now: false), thunder time: 58046 (now: false)
Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
Minecraft Version: 1.12.2
Operating System: Linux (amd64) version 4.4.0-116-generic
Java Version: 1.8.0_162, Oracle Corporation
Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 5767164328 bytes (5499 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
JVM Flags: 13 total; -Xms6G -Xmx6G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=99 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:InitiatingHeapOccupancyPercent=10 -XX:G1MixedGCLiveThresholdPercent=50 -XX:+AggressiveOpts -XX:+AlwaysPreTouch
IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
FML: MCP 9.42 Powered by Forge 14.23.2.2611 48 mods loaded, 48 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

| State     | ID                | Version                  | Source                                      | Signature                                |
|:--------- |:----------------- |:------------------------ |:------------------------------------------- |:---------------------------------------- |
| UCHIJAAAA | minecraft         | 1.12.2                   | minecraft.jar                               | None                                     |
| UCHIJAAAA | mcp               | 9.42                     | minecraft.jar                               | None                                     |
| UCHIJAAAA | FML               | 8.0.99.99                | forge-1.12.2-14.23.2.2611-universal.jar     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
| UCHIJAAAA | forge             | 14.23.2.2611             | forge-1.12.2-14.23.2.2611-universal.jar     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
| UCHIJAAAA | craftstudioapi    | 1.0.0                    | CraftStudio-1.0.0.93-mc1.12-alpha.jar       | None                                     |
| UCHIJAAAA | animania          | 1.4.5                    | animania-1.12.2-1.4.5.jar                   | None                                     |
| UCHIJAAAA | applecore         | 3.1.0                    | AppleCore-mc1.12.2-3.1.0.jar                | None                                     |
| UCHIJAAAA | blockarmor        | 2.4.11                   | BlockArmor-1.12.2-2.4.11.jar                | None                                     |
| UCHIJAAAA | extendedrenderer  | v1.0                     | coroutil-1.12.1-1.1.24.jar                  | None                                     |
| UCHIJAAAA | coroutil          | 1.12.1-1.1.24            | coroutil-1.12.1-1.1.24.jar                  | None                                     |
| UCHIJAAAA | configmod         | v1.0                     | coroutil-1.12.1-1.1.24.jar                  | None                                     |
| UCHIJAAAA | earthworks        | 1.3.4.3                  | Earthworks-1.12-1.3.6.jar                   | None                                     |
| UCHIJAAAA | fastleafdecay     | v14                      | FastLeafDecay-v14.jar                       | None                                     |
| UCHIJAAAA | waila             | 1.8.24                   | Hwyla-1.8.24-B39_1.12.jar                   | None                                     |
| UCHIJAAAA | inventorytweaks   | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                    | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
| UCHIJAAAA | jei               | 4.8.5.147                | jei_1.12.2-4.8.5.147.jar                    | None                                     |
| UCHIJAAAA | journeymap        | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                 | None                                     |
| UCHIJAAAA | lycanitesmobs     | 1.19.3.5 - MC 1.12.2     | LycanitesMobsComplete+1.19.3.5+[1.12.2].jar | None                                     |
| UCHIJAAAA | arcticmobs        | 1.19.3.5 - MC 1.12.2     | LycanitesMobsComplete+1.19.3.5+[1.12.2].jar | None                                     |
| UCHIJAAAA | demonmobs         | 1.19.3.5 - MC 1.12.2     | LycanitesMobsComplete+1.19.3.5+[1.12.2].jar | None                                     |
| UCHIJAAAA | desertmobs        | 1.19.3.5 - MC 1.12.2     | LycanitesMobsComplete+1.19.3.5+[1.12.2].jar | None                                     |
| UCHIJAAAA | elementalmobs     | 1.19.3.5 - MC 1.12.2     | LycanitesMobsComplete+1.19.3.5+[1.12.2].jar | None                                     |
| UCHIJAAAA | forestmobs        | 1.19.3.5 - MC 1.12.2     | LycanitesMobsComplete+1.19.3.5+[1.12.2].jar | None                                     |
| UCHIJAAAA | freshwatermobs    | 1.19.3.5 - MC 1.12.2     | LycanitesMobsComplete+1.19.3.5+[1.12.2].jar | None                                     |
| UCHIJAAAA | infernomobs       | 1.19.3.5 - MC 1.12.2     | LycanitesMobsComplete+1.19.3.5+[1.12.2].jar | None                                     |
| UCHIJAAAA | junglemobs        | 1.19.3.5 - MC 1.12.2     | LycanitesMobsComplete+1.19.3.5+[1.12.2].jar | None                                     |
| UCHIJAAAA | mountainmobs      | 1.19.3.5 - MC 1.12.2     | LycanitesMobsComplete+1.19.3.5+[1.12.2].jar | None                                     |
| UCHIJAAAA | plainsmobs        | 1.19.3.5 - MC 1.12.2     | LycanitesMobsComplete+1.19.3.5+[1.12.2].jar | None                                     |
| UCHIJAAAA | saltwatermobs     | 1.19.3.5 - MC 1.12.2     | LycanitesMobsComplete+1.19.3.5+[1.12.2].jar | None                                     |
| UCHIJAAAA | shadowmobs        | 1.19.3.5 - MC 1.12.2     | LycanitesMobsComplete+1.19.3.5+[1.12.2].jar | None                                     |
| UCHIJAAAA | swampmobs         | 1.19.3.5 - MC 1.12.2     | LycanitesMobsComplete+1.19.3.5+[1.12.2].jar | None                                     |
| UCHIJAAAA | mantle            | 1.12-1.3.1.21            | Mantle-1.12-1.3.1.21.jar                    | None                                     |
| UCHIJAAAA | radixcore         | 1.12.x-2.2.1             | RadixCore-1.12.x-2.2.1-universal.jar        | None                                     |
| UCHIJAAAA | mca               | 1.12.2-5.3.1             | MCA-1.12.x-5.3.1-universal.jar              | None                                     |
| UCHIJAAAA | mercurius_updater | 1.0                      | MercuriusUpdater-1.12.2.jar                 | None                                     |
| UCHIJAAAA | natura            | 1.12.2-4.3.2.42          | natura-1.12.2-4.3.2.42.jar                  | None                                     |
| UCHIJAAAA | clayspawn         | 1.12a                    | Pam's+ClaySpawn+1.12a.jar                   | None                                     |
| UCHIJAAAA | projecte          | 1.12-PE1.0.0             | ProjectE-1.12-PE1.2.0.jar                   | None                                     |
| UCHIJAAAA | redstoneflux      | 2.0.1                    | RedstoneFlux-1.12-2.0.1.2-universal.jar     | d4f1503fbacd9b9fb767720420c5395104239ec9 |
| UCHIJAAAA | roguelike         | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar          | None                                     |
| UCHIJAAAA | rustic            | 0.4.8                    | rustic-0.4.8.jar                            | None                                     |
| UCHIJAAAA | simplecorn        | 2.3.7                    | SimpleCorn1.12-2.3.7.jar                    | None                                     |
| UCHIJAAAA | spiceoflife       | 1.3.11                   | SpiceOfLife-mc1.12-1.3.11.jar               | None                                     |
| UCHIJAAAA | tconstruct        | 1.12.2-2.9.1.65          | TConstruct-1.12.2-2.9.1.65.jar              | None                                     |
| UCHIJAAAA | tinker_io         | release 2.6.0a           | tinker_io-1.12.2-release+2.6.0a.jar         | None                                     |
| UCHIJAAAA | vefluids          | 0.8.0.10                 | VE-FluidHandling-1.12-0.8.0b10.jar          | None                                     |
| UCHIJAAAA | woodenbucket      | 0.2.0.10                 | WoodenBuckets-1.12-0.2.0b10.jar             | None                                     |
| UCHIJAAAA | zombieawareness   | 1.12.1-1.11.11           | zombieawareness-1.12.1-1.11.11.jar          | None                                     |

Loaded coremods (and transformers): 
AppleCore (AppleCore-mc1.12.2-3.1.0.jar)
squeek.applecore.asm.TransformerModuleHandler
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
invtweaks.forge.asm.ContainerTransformer
Pulsar/natura loaded Pulses:
- NaturaCommons (Enabled/Forced)
- NaturaOverworld (Enabled/Not Forced)
- NaturaNether (Enabled/Not Forced)
- NaturaDecorative (Enabled/Not Forced)
- NaturaTools (Enabled/Not Forced)
- NaturaEntities (Enabled/Not Forced)
- NaturaOredict (Enabled/Forced)
- NaturaWorld (Enabled/Not Forced)

Pulsar/tconstruct loaded Pulses: 
	- TinkerCommons (Enabled/Forced)
	- TinkerWorld (Enabled/Not Forced)
	- TinkerTools (Enabled/Not Forced)
	- TinkerHarvestTools (Enabled/Forced)
	- TinkerMeleeWeapons (Enabled/Forced)
	- TinkerRangedWeapons (Enabled/Forced)
	- TinkerModifiers (Enabled/Forced)
	- TinkerSmeltery (Enabled/Not Forced)
	- TinkerGadgets (Enabled/Not Forced)
	- TinkerOredict (Enabled/Forced)
	- TinkerIntegration (Enabled/Forced)
	- TinkerFluids (Enabled/Forced)
	- TinkerMaterials (Enabled/Forced)
	- TinkerModelRegister (Enabled/Forced)
	- wailaIntegration (Enabled/Not Forced)

Profiler Position: N/A (disabled)
Player Count: 0 / 20; []
Is Modded: Definitely; Server brand changed to 'fml,forge'
Type: Dedicated Server (map_server.txt)

**Comment by wolfgangrumpf** [comment]
Updating to the latest version fixed it in future worlds....

**Comment by Deshiba** [comment]
@capnkirok Last update was June with the message that it's fixed? I think you need some closure 😅.
