### ISSUE TITLE
Suggestion: Animals to drop fertilizer

### ISSUE THREAD

**Issue by seftikara651** [capnkirok/animaniamod#330]
I was wondering if it is possible for you to implements some new behavior to item drops of animals including:

### Expected Behavior
1. **animal producing manure which we can use to fertilize farmland**.
2. **animal drop bone when killed**.

### Actual Behavior
animal doesn't drop bone, it may be the basic problem to realism. (for me)

### Steps to Reproduce
1. on my opinion, it could be liquid or solid manure. and the blocks will behave like any liquid _- for liquid manure -_, and/or behave like snow _- for solid manure, snow have small height and is stack-able -_. uses bucket to store the item. animals may have a special block to drop their manure (toilet kind, stable, or something).
2. increasing the basic recipe needed to make bone meal, to make game stable. (enabling this feature make bone meal usable in peaceful difficulty.)

i hope you consider to add one of them, or both to the game. or at least something like thread #299 .
thank you.

**Comment by MizuNomy** [comment]
You re welcome to throw your ideas onto the Official Animania Discord Server! Thank you!
https://discord.gg/Cnj4sZA

**Comment by seftikara651** [comment]
@SuperPawmaple thanks for the redirection.
