### ISSUE TITLE
no prime meats?

### ISSUE THREAD

**Issue by CharleeToombs** [capnkirok/animaniamod#332]
### Expected Behavior
Animania meats expected from animania animals

### Actual Behavior
no animania meats, only vanilla pork/beef/chicken (even with looting 3 and a serious Ferisian cow overcrowding issue!

### Steps to Reproduce
uncertain

### Version of Minecraft, version of Animania, Single Player or Server
Technic Launcher used, modpack "Tekxit 3 (official)"by slayer5934 1.12.2, Modpack version 0.92
I checked the config, everything looks right?

**Comment by capnkirok** [comment]
Friesian cows drop vanilla meats. Currently you need to slaughter a beef cow (Black Angus, Hereford, or Texas Longhorn) for prime meats.
