### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by mxnmnm** [capnkirok/animaniamod#334]
### Expected Behavior
No Crash

### Actual Behavior
Crash

### Steps to Reproduce
I was killing a bunch of cows and I crashed

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2
animania 1.6.2
single player

https://paste.dimdev.org/madonaheka.mccrash

**Comment by capnkirok** [comment]
This crash is caused when a cow is trying to look at another entity and suddenly the entity doesn't exist. Hard to reproduce. But I can put some error trapping in.
