### ISSUE TITLE
[Bug] Sleeping makes mobs pass trough a block

### ISSUE THREAD

**Issue by thegamerx1** [capnkirok/animaniamod#335]
When an animal ends sleeping he wakes up and then suffocates inside a block but they get to pass trough the fences
### Version of Minecraft, version of Animania, Single Player or Server
Single Person Minecraft 1.12.2
Latest version? Downloaded mod some days ago

### Screenshots
https://imgur.com/a/vyJvkho

**Comment by Tschipp** [comment]
Can you show any proof of suffocation? The hitbox doesn't/shouldn't change when they are sleeping

**Comment by thegamerx1** [comment]
I stopped playing Minecraft time ago and deleted that world but I think that it happend when they where sleeping and you move them into a block and when they wake-up they suffocate.

**Comment by ghost** [comment]
I'm seeing something similar, where I'll be walking around in another part of the chunk and suddenly see "<animal> suffocated in a wall". I can't confirm it's due to them sleeping, but there's definitely something strange going on here.
