### ISSUE TITLE
[Mod Support] CarryOn

### ISSUE THREAD

**Issue by thegamerx1** [capnkirok/animaniamod#336]
**Can't replicate**  ~~When leaving a mob on the floor they fly for a second and get stuck into a block easily~~ 

When taking troughs they get no texture and the hitbox is like a small preassure plate when breaking and placing again gets fixed

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12.2 
Lastest version
Single Player

Curseforge: https://www.curseforge.com/minecraft/mc-mods/carry-on
Github: https://github.com/Tschipp/CarryOn

**Comment by Tschipp** [comment]
Troughs shouldn't be able to be picked up. Due to a bug with carry on's config, it can still be picked up. Will fix in carry on. In the meantime, add "animania:invisiblock" to your block blacklist config in carry on.
