### ISSUE TITLE
troughs crash when attempting to fill with water

### ISSUE THREAD

**Issue by WittyOneliner** [capnkirok/animaniamod#337]
### Expected Behavior
trough gets filled with water

### Actual Behavior
game crashes

### Steps to Reproduce
take a bucket of water and right-click a trough and the game crashes 

Error: com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: mcjty/theoneprobe/api/ProbeMode
### Version of Minecraft, version of Animania, Single Player or Server

minecraft ver. 1.12.2 animania ver. 1.6.2

**Comment by capnkirok** [comment]
Hmm... that's a tooltip crash issue from another mod (TheOneProbe), looks like the server is trying to grab client info. Let's see if there's anything we can do.

**Comment by capnkirok** [comment]
Does this crash happen all the time? Or did it just happen this once. Can you post your full crash log here?

**Comment by Tschipp** [comment]
Going to close this... feel free to comment if it needs reopening

**Comment by WittyOneliner** [comment]
hello, sorry i haven't been active. ive figured out the issue. 
apparently this mod and the mod "mo bends" seemed to have a conflict of interest. 
mo bends had a custom animation for dumping water from a bucket to a cauldron and i believe it wasn't sure weather to identify the trough as a cauldron, so it just gave up and crashed the game.

**Comment by Tschipp** [comment]
That is very strange indeed. Sounds like a problem on MoBends' side.
