### ISSUE TITLE
Animania Animals bypassing shield

### ISSUE THREAD

**Issue by DoomRater** [capnkirok/animaniamod#338]
### Expected Behavior
Shields intercept _all_ physical damage when pointed in the right direction.  This includes creepers.

### Actual Behavior
Animania Bull bypassed the shield and dealt damage anyway.

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12.2, Animania 0.6.3, tested on server

**Comment by Tschipp** [comment]
Bull damage bypasses armor, which seems to include shields. But yeah, that seems quite unreasonable. Fixed in next release

**Comment by DoomRater** [comment]
A bit late on a suggestion, but I recently noticed Vindicators were disabling the shield when they hit with their axes.  I just looked up to see if this is vanilla behavior and apparently it is on Java Edition.  Maybe bulls could trigger that too?
