### ISSUE TITLE
[Request] mobs pick up tiles

### ISSUE THREAD

**Issue by matthewfcarlson** [capnkirok/animaniamod#339]
Hey- I recently wrote a mod for my brothers and I that added hunger and a food seeking mechanism to cows specifically (to allow for automated breeding by hopper). I came across your extension just now and it's incredible. 

The only thing that my mod does that your doesn't is have cows try to eat wheat tiles on the floor (or really any wheat tiles). They overrode the canPickUpLoot function and "equipped" the food, only for it to be deleted.

Would you be open to a PR augmenting the GenericAiSearchBlock class to include searching for tile entities?

**Comment by Tschipp** [comment]
Hi, GenericAISearchBlock is already able to look for TileEntities, thanks to shouldMoveTo.
GenericAIFindFood already does this:
https://github.com/capnkirok/animaniamod/blob/1.12/src/main/java/com/animania/common/entities/generic/ai/GenericAIFindFood.java#L116-L132

**Comment by Tschipp** [comment]
I think I misunderstood. I think you are talking about "Item Entities" not Tile Entities, so dropped items on the ground. Am I correct?
