### ISSUE TITLE
[1.12] Some goats seem to have infinite milk.

### ISSUE THREAD

**Issue by laserlemons** [capnkirok/animaniamod#34]
### Expected Behavior
I'd assume you aren't supposed to be able to get infinite buckets of milk one after another.

### Actual Behavior
Right-clicking some goats give infinite milk.

### Steps to Reproduce
For me, I found two goats in the wild that I could milk infinitely. Both were Angora goats. I don't know if they gave birth in the wild or not, but not all Angora goats did it, only two that I found. I did not manually feed or water the goats.

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12.2, Animania 1.4.7, Forge 14.23.2.2654, both single player and server.

### Screenshots encouraged
![2018-04-05_13 54 29](https://user-images.githubusercontent.com/6501298/38391428-07dfca02-38d9-11e8-81d4-20f0267f984a.png)

**Comment by laserlemons** [comment]
After testing more, it looks like all female Angora goats are giving me infinite milk as long as they don't have the unhappy particles.

**Comment by capnkirok** [comment]
Looks like it's all goats. I fixed a shearing bug that is now causing this.

**Comment by capnkirok** [comment]
Yup. Typo. Fixed in next release. Only a problem on 1.12.

**Comment by SakuraWuhen** [comment]
@capnkirok Hello, there will still be the problem of unlimited milking in the latest version. Whether it is sheep, goats or cows, as long as they are given water during the lactation period, they can be milked indefinitely.
Is this a deliberate setting, or is it a bug?

The version numbers are all up to date 
![image](https://user-images.githubusercontent.com/45621850/120593868-acd6b480-c472-11eb-9ad8-371e00430cb8.png)

**Comment by Tschipp** [comment]
That is intended. As long as they are watered and have children, they can be indefinitely milked.
