### ISSUE TITLE
Trough Still Doesn't Work?

### ISSUE THREAD

**Issue by BiNonJay** [capnkirok/animaniamod#342]
### Expected Behavior
Animals should go to full troughs when thirsty/hungry and drink/eat.

### Actual Behavior
I have yet to test on all other animals, but with the draft horse I currently have in my modded map, it refuses to drink or eat from the troughs I have placed for it. Sometimes it will get stuck near the trough and start spinning rapidly.

### Steps to Reproduce
Place troughs, fill troughs, and either spawn in or lead a draft horse to them.

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12.2, Animania 1.6.2, Single Player

I know a few other people had this issue before and it was, from what I can tell, supposed to be fixed with the version I have, but it is definitely still not working right for me.

**Comment by Tschipp** [comment]
Should be fixed in next release
