### ISSUE TITLE
Cow milk disappearing from bucket

### ISSUE THREAD

**Issue by G1R-Productions** [capnkirok/animaniamod#343]
### Expected Behavior
Functioning way to acquire milk from cows via buckets.

### Actual Behavior
Milk disappearing from bucket after interacting with bucket in inventory or attempting to place milk in the world.

### Steps to Reproduce
Milk a cow then click the milk bucket in inventory or right click with milk bucket in world.

### Version of Minecraft, version of Animania, Single Player or Server
minecraft 1.12.2
animania 1.6.2

**Comment by Tschipp** [comment]
Can't reproduce

**Comment by G1R-Productions** [comment]
This is on a MP server. Sorry forgot to mention that.

What are the exact steps in order to get a cow to produce milk? From my understand it needs to not be thirsty or hungry and has to be happy. When I milk the cow the bucket will appear to be full of milk but when I go to move the bucket around my inventory the bucket of milk will revert to an empty bucket.

**Comment by Tschipp** [comment]
The cow needs to be fed and watered and have children to give milk. I can't reproduce it in my dev environment, but I've rewritten all children/milking code so I suppose it's fixed.
