### ISSUE TITLE
Crash on ticking entity

### ISSUE THREAD

**Issue by rlnt** [capnkirok/animaniamod#345]
### Expected Behavior
Game should continue

### Actual Behavior
Game crashes

### Steps to Reproduce
No actual reproduction possible since it crashed after playing for a while

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft: 1.12.2
Animania: 1.6.2
Forge: 14.23.5.2847
Multiplayer Server

### Log
https://pastebin.com/bgJpt66g

**Comment by Tschipp** [comment]
That's a bloodmagic issue
