### ISSUE TITLE
Crash on startup after update to 1.7.1 - also - Great work guys!! 

### ISSUE THREAD

**Issue by tolerus** [capnkirok/animaniamod#348]
Crash report:
https://paste.dimdev.org/oqafekavug.mccrash

### Version of Minecraft, version of Animania, Single Player or Server

Minecraft forge-1.12.2-14.23.5.2768 Server
Animania 1.7.1

I hope y'all're receiving due accolades for your work on this mod! We've been excited to see this release for use on our server :)

**Comment by Tschipp** [comment]
Use latest forge, thanks
