### ISSUE TITLE
Truffle Soup gives regeneration effect when potion effects are disabled in config.

### ISSUE THREAD

**Issue by laserlemons** [capnkirok/animaniamod#35]
### Expected Behavior
Regeneration effect should be disabled. It does not show up in the tooltip but it still gives it to you when you eat it.

### Actual Behavior
Truffle soup gives regeneration 2 when eaten.

### Steps to Reproduce
Disable potion effects in the config and then eat truffle soup.

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12.2, Animania 1.4.7, Forge 14.23.2.2654, both single player and server.

### Screenshots encouraged
![2018-04-05_13 59 00](https://user-images.githubusercontent.com/6501298/38391725-e25b797e-38d9-11e8-87ac-aa36e5ac704a.png)

**Comment by capnkirok** [comment]
Thanks @laserlemons good catch.

**Comment by capnkirok** [comment]
Only on 1.11 & 1.12, Fixed in next release (1.4.8)
