### ISSUE TITLE
"Potential Error" When Loading Up Minecraft 1.12.2 Bug/Error

### ISSUE THREAD

**Issue by iiSavierii** [capnkirok/animaniamod#350]
### Expected Behavior

Load up the game, and let me play. (Duh, lol)

### Actual Behavior

When all my mods are done loading, It will show up something saying, "This could be a Potential Error." It also says it is impossible to open minecraft with this error, so I just took off the mod.

### Steps to Reproduce

Take it out of your mods folder until they fix it...

### Version of Minecraft, version of Animania, Single Player or Server

Animania-1.12.2-1.7.1
Forge: 1.12.2-14.23.4.2705
Singe Player

### Screenshots encouraged
(It just says what I said above.)

**Comment by iiSavierii** [comment]
Please fix this! I really want to play around with the animals on Animania!

**Comment by Tschipp** [comment]
Use latest forge.
