### ISSUE TITLE
Dog record

### ISSUE THREAD

**Issue by kihgy** [capnkirok/animaniamod#352]
Animania should add in dog records, on par with cat

**Comment by Tschipp** [comment]
what?

**Comment by kihgy** [comment]
There is an unused song in MC by C418 called "dog", it sound similar to "cat", but only "cat" got made into a record in-game, while dog doesn't, but in the Xbox version, I am asking if Animania could add in an extra record for "dog", since this mod will overhaul cats and dogs. The song can be found on Youtube.

**Comment by Tschipp** [comment]
out of scope
