### ISSUE TITLE
Crash when loading into world/saving world/other random occurrences (Morb Bug)

### ISSUE THREAD

**Issue by tst5000** [capnkirok/animaniamod#357]
### Expected Behavior
I should be able to save or quit without the game freezing.

### Actual Behavior
The game freezes (but only sometimes) when I load into a world, save and quit from that world, or sometimes at random times. The game log also spits out an error regarding a duplicate stat id, which always happens to be an entity from Animania.

### Steps to Reproduce
1. Play Enigmatica 2: Expert v.1.68 (I have added some mods, and will post a file containing all the mod names)
2. Save or quit from game (or wait some undetermined amount of time in-world)

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft: 1.12.2, Singleplayer
Animania: 1.7.1

### Screenshots encouraged
(none needed, log files posted)
Log: [2019-09-26-2.log](https://github.com/capnkirok/animaniamod/files/3659911/2019-09-26-2.log)
Mod list:  [list.txt](https://github.com/capnkirok/animaniamod/files/3659951/list.txt)

**Comment by Tschipp** [comment]
This is a bug related to our "hack" that we used to bring compatibility for thermal expansion morbs... This feature has caused more pain than benefit, I think I will just completely remove it in the next update.

**Comment by tst5000** [comment]
Thank you for your quick response. I will update this when the update comes out to verify if the issue has been fixed.

**Comment by zacski1** [comment]
I'm also having the same issue here, crashing mainly on world exit. Hoping this gets resolved at some point.

**Comment by Tschipp** [comment]
I am sorry about your troubles. I currently don't have time to do an update that fixes this until february, but I will get one out then.

**Comment by Peavii** [comment]
Is the update still coming? I'm having the same issue on world exit with IndustrialCraft 2 (I think)...
