### ISSUE TITLE
Ocelot and others animal from Mods don't spawn?

### ISSUE THREAD

**Issue by xMrCaosx** [capnkirok/animaniamod#360]
Is possible this mod delete all natural vanilla spawn animals?.
I understand this mod replaced Cows, Sheeps, Horse, etc for Animania Mods (And replace the Vanilla).

But these is a problem i see. The ocelot dont spawn on the Jungle. And another mob i add "Foxes" from Outfox dont spawn too in Naturally biomes designed.

I check this with "Nature compass (Another mod)" in Various worlds in the Jungle and Forest Biomes and nothing happen.

 I'm playing the 1.12.2

**Comment by Tschipp** [comment]
We don't interfere with spawning of other animals. There exists a (vanilla) peaceful mob cap which will fill up quickly with animania installed. You will probably see much less of other mob spawns.
