### ISSUE TITLE
Torchmaster - Dreadlamp does not hinder Animania horses to spawn in 1.7.2

### ISSUE THREAD

**Issue by Kolerath** [capnkirok/animaniamod#361]
### Expected Behavior
Dreadlamp from Torchmaster mod should prevent passive animal spawns such as horses from Animania

### Actual Behavior
After the update to 1.12.2-1.7.2 I experienced that the Dreadlamp from Torchmaster does not prevent Horse spawns on plains, even if the Biome is removed and the Torchmaster config file is specifically configured to override their spawn.

(I am running the Dungeons, Dragons and Space Shuttles modpack)

### Steps to Reproduce
I could reproduce this by creating a superflat world where the whole world is a Plains biome and all I need to do is find a area where horses spawn (Sort of like a sweetspot) and put up the Dreadlamp from Torchmaster and then proceed to kill everything with the kill @e command. Afterwards I can see the horses starts spawning.

### Version of Minecraft, version of Animania, Single Player or Server
MC: 1.12.2
Animania: 1.12.2-1.7.2

Both SP and MP

### Screenshots encouraged
If needed I can provide screenshots.

**Comment by Tschipp** [comment]
I assume we're talking about animania horses here?

**Comment by Kolerath** [comment]
Yes this is Animania horses, I haven't seen any other animals force spawning.

**Comment by Tschipp** [comment]
Ok, I have an idea what could be causing this...
