### ISSUE TITLE
1.12.2-1.7.2 Prompts Download of 1.6.2

### ISSUE THREAD

**Issue by DonTheBreton** [capnkirok/animaniamod#363]
### Expected Behavior
Only suggest download of newer version.

### Actual Behavior
1.7.2 Suggests download of 1.6.2 upon entering game.

### Steps to Reproduce
Launch. Enter game. Read chat.

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2 Minecraft
1.12.2-1.7.2 Animania
Single Player

### Screenshots encouraged
http://prntscr.com/pf9pq1

**Comment by capnkirok** [comment]
Fixed the update file. All good now.
