### ISSUE TITLE
Rendering error

### ISSUE THREAD

**Issue by Sunconure11** [capnkirok/animaniamod#365]
User of a modpack for one of my servers encountered this, don't know the exact cause so I'll just dump it here.

https://pastebin.com/zy1GyqHQ

**Comment by Sunconure11** [comment]
Encountered this while trying to place Wildewheet from Roots 3 in a trough, since I had set it in the configs to do so.

https://paste.dimdev.org/kokiqetele.mccrash

**Comment by Tschipp** [comment]
So this turned out to be Roots 3, but I added a safety check anyway
