### ISSUE TITLE
Animania Crazy Spawn at 0,0,0

### ISSUE THREAD

**Issue by Isla-Liu** [capnkirok/animaniamod#367]
### Expected Behavior
Animals should spawn at correct position when new chunks generate

### Actual Behavior
when new chunks generate,the animal all generate at xyz(0,0,0) makes lot lag then freeze

### Steps to Reproduce
Install modpack DDSSv6.2
go loaded Chunks or use Pregen
/pregen gen startradius square 0 0 100
then animal will crazy spawn together in xyz(0,0,0)

### Version of Minecraft, version of Animania, Single Player or Server

Minecraft version: 1.12.2
Forge version: forge-1.12.2-14.23.5.2836-universal
Modpack version (links to current modlist): [6.2](https://www.curseforge.com/minecraft/modpacks/dungeons-dragons-and-space-shuttles/files/2801746)
Mod versions: Animania 1.7.2, CraftStudioAPI 1.0.1.95

### Screenshots encouraged

![](https://cdn.discordapp.com/attachments/333684705373454346/630651943848771594/unknown.png)

**Comment by katubug** [comment]
I do not play DDSS but I figured I'd do some testing to see what could be causing the issue. I made a fresh install with just Animania/CraftStudioAPI and Zoesteria. I was able to replicate the issue a few times, but not every time. I was not able to replicate the issue with only Animania/CraftStudioAPI and Traverse. Additionally, I tried another entity-spawning mod (ZAWA) with Zoesteria, and could not replicate the issue, even when using the same seeds the issue occurred in previously. So, my theory is that there's some miscommunication between Zoesteria and Animania regarding how spawning should work.

**Mods and versions**:
animania-1.12.2-1.7.2
CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha
Zoesteria Public Alpha 1.4.10
When using Traverse: Traverse v1.6.0 build69 for 1.12.2
When using ZAWA: zawa-1.12.2-1.7.0.

I tested on forge 2836 and 2838 just in case that was the issue, but saw no difference between them.

Replicated:
- Seed -1994555203772886380
- Spawned in Bush Biome

Replicated:
- Seed 4819391118352641278
- Spawned in Plains Biome

Just as a note, I did some testing with earlier Animania versions (forge 2836). I could replicate this issues with 1.7.0-1.7.2, but 1.6.2 seemed to be fine. I tested both seeds reported in my issues at the Zoesteria and DDSS githubs, as well as an additional randomly generated world, and in none of those worlds did animals seem to spawn at 0x 0y 0z.

Hopefully this is able to be nailed down soon. :)

**Comment by draeath** [comment]
I think af02a36717a1a732fc52bd5a468e695f8353d868 is what broke this. Notably in `src/main/java/com/animania/common/events/SpawnHandler.java` where `replacementEntity` was implemented.

The old method took in some coordinates from the spawn event and set the new entity coordinates. Eg, there seems to be no equivalent to the `entity.setPosition(event.getX(),event.getY()+1, event.getZ());` lines that were removed.
