### ISSUE TITLE
Laser lasso duplication

### ISSUE THREAD

**Issue by grugasaurus** [capnkirok/animaniamod#371]
### Expected Behavior
Capture mob or kill mob

### Actual Behavior
Capture mob *and* kill mob, producing drops and infinitely repeatable using the captured mob

### Steps to Reproduce
Plustic laser in offhand (I used refined flowstone medium, alumite handle (linked to chest), netherrack pipe piece, manyullen battery), golden lasso in main hand. Right click animania mob (I used a chicken). The mob will die, drop items, and be in the lasso, which you can use to spawn a new one and repeat ad infinitum.

### Version of Minecraft, version of Animania, Single Player or Server
Dungeons dragons and space shuttles release 6.2

**Comment by Tschipp** [comment]
This has nothing to do with Animania. This probably happens for every other mob as well. Please test this.
Also, if this is the case, you need to report this to the mod with the golden lasso, this is on their end
