### ISSUE TITLE
[1.12.2] WAILA doesn't show rabbit buck's gender

### ISSUE THREAD

**Issue by ghost** [capnkirok/animaniamod#374]
### Expected Behavior
Spawn in a Lop Buck with a Spawn Egg.
Actually has a gender and a purpose

### Actual Behavior
Lop Buck is actually spayed/neutered and is therefore genderless.

### Steps to Reproduce
Spawn a Lop Buck
Shift over a Lop Buck with HWYLA 
Profit??

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12.2
Animania 1.7.2
Any- Singleplayer & Server

### Screenshots encouraged
![image](https://user-images.githubusercontent.com/44342726/67059397-c36eb180-f150-11e9-8231-2e83b6c2e566.png)
![image](https://user-images.githubusercontent.com/44342726/67059404-c79acf00-f150-11e9-9c6c-94aef3dbe0e9.png)

**Comment by Tschipp** [comment]
What? How can you even tell if it‘s neutured? It doesn’t show anything in TOP or WAILA

**Comment by ghost** [comment]
Well what I was trying to get at is they cannot breed. Like neutered/spayed bunnies/rabbits irl.

Can you confirm this is a bug?

**Comment by Tschipp** [comment]
Can't recreate this, be buck bred just fine

**Comment by ghost** [comment]
Spawn a buck with the Buck spawn egg, ctrl over it with HWYALA and it will be genderless.

> Spawn a Lop Buck Shift over a Lop Buck with HWYLA Profit??

**Comment by Tschipp** [comment]
Again. If it's neutered has nothing to do with what shows up on WAILA/TOP

**Comment by Tschipp** [comment]
But yes, the gender flag didn't show up correctly on bucks for WAILA.
