### ISSUE TITLE
[Suggestion] Serene Seasons Support

### ISSUE THREAD

**Issue by Omegapsychosis** [capnkirok/animaniamod#377]
I was wondering if it would be possible to get support for the Serene Seasons mod, to allow animals to have a set breeding season?

I just think this could be a neat feature for modpacks that tend towards a more realistic feel.

**Comment by VinterNacht** [comment]
Yes PLEASE.

**Comment by CalaMariGold** [comment]
I love this! Animals could become cold in the winter if they don't have proper shelter.
