### ISSUE TITLE
Dupe with Rats

### ISSUE THREAD

**Issue by mxnmnm** [capnkirok/animaniamod#380]
### Expected Behavior
Animania Milk to go into a cauldron and make cheese

### Actual Behavior
Animania Milk to goes into the cauldron and makes cheese but it also gets place in the world

### Steps to Reproduce
Step 1: Get cauldron
Step 2: Get animania milk bucket
Step 3: Right click animania milk bucket on cauldron
Step 4: ???
Step 5: Profit

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2
Animania 1.7.3
Rats 3.1.0
Single Player

### Screenshots encouraged
https://imgur.com/a/Zvbfl18

**Comment by mxnmnm** [comment]
Alex said he couldn't fix the issue so I'm guessing maybe you could fix it on your end

**Comment by Tschipp** [comment]
Why can't he fix the issue? We don't do anything special with the bucket, we use the forge universal bucket. That cauldron behavior is not vanilla, we can't handle it.

**Comment by mxnmnm** [comment]
He mentioned animania being closed source so he wasn't sure how to fix it because it would just be a shot in the dark.

**Comment by Tschipp** [comment]
Well it obviously isn’t anymore.

**Comment by mxnmnm** [comment]
Ye I guess I'll close this issue since there isn't much else you can do
