### ISSUE TITLE
Salt lick extends to the skies

### ISSUE THREAD

**Issue by Sorathesec** [capnkirok/animaniamod#382]
### Expected Behavior
Salt lick should look like a small cube when placed

### Actual Behavior
The salt lick block seems to be 20 blocks tall 

### Steps to Reproduce
Unsure, I couldn't reproduce outside of my current server. When I originally placed a salt lick it looked normal. A few days later I tried to move it and this happened

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12
Animania 1.7.3
Server - Forge 8.0.99
See link for other mods in modpack - curseforge.com/minecraft/modpacks/magic-and-madness

### Screenshots encouraged
![image](https://user-images.githubusercontent.com/14876453/69303543-4496e980-0bd2-11ea-843f-c0ca3607aa9d.png)
![image](https://user-images.githubusercontent.com/14876453/69303551-4eb8e800-0bd2-11ea-910e-d1a76378ce69.png)

**Comment by Tschipp** [comment]
Move? As in, with Carry On?

**Comment by Sorathesec** [comment]
No, just by breaking and replacing. It now happens with every salt lick I place  on that server
