### ISSUE TITLE
[Suggestion] Stop animals from standing on troughs

### ISSUE THREAD

**Issue by ghost** [capnkirok/animaniamod#384]
It seems like every time my sheep or cows go to eat or drink from troughs, they climb up on top of them. Functionally there's nothing wrong with this, but it looks really silly and kinda breaks immersion a bit. It would be nice if there could be a config toggle or something of the sort to stop larger animals from climbing on top of troughs to eat/drink.

**Comment by Tschipp** [comment]
This is already the case. If mobs push eachother onto the trough there's not much I can do about that.
