### ISSUE TITLE
Animania animals block right click functions on tools

### ISSUE THREAD

**Issue by DoomRater** [capnkirok/animaniamod#385]
### Expected Behavior
Right clicking on Animania cows and bulls with Runic Shears should be able to produce Fey Leather.  Same with horses.

### Actual Behavior
Cows and bulls ignore the attempt, and horses neigh angrily as if you are trying to mount them with something or offer them something they do not want.  It seems they are overriding the right click behavior of any tools.

### Steps to Reproduce
0. Add Animania Animals to Runic Shears recipes via CraftTweaker. My file: https://pastebin.com/biiwwbWT
1. equip Runic Shears
2. spawn a cow, bull, or horse of any gender
3 right click on the animal with Runic Shears
### Version of Minecraft, version of Animania, Single Player or Server
Animania 1.7.2
Roots 3.0.17

**Comment by Tschipp** [comment]
This is not on our end.

**Comment by DoomRater** [comment]
https://github.com/capnkirok/animaniamod/blob/a273bdef8510566da3716f2748a6b574121acf8c/src/main/java/com/animania/manual/components/EntityComponent.java#L165

You were saying?

**Comment by Tschipp** [comment]
> https://github.com/capnkirok/animaniamod/blob/a273bdef8510566da3716f2748a6b574121acf8c/src/main/java/com/animania/manual/components/EntityComponent.java#L165
> 
> You were saying?

What? That is completely unrelated to the issue. That is a gui component that is used for the Manual.
However, I looked into our code again and saw this: 
https://github.com/capnkirok/animaniamod/blob/0dccf729b45fc6cf86c5842670d0cf502326a66a/src/main/java/com/animania/common/entities/cows/EntityAnimaniaCow.java#L213
Yet, that statement is only called when right clicking mooshrooms with shears, so I don't think it relates to your issue. 
That means, it's calling this line:
https://github.com/capnkirok/animaniamod/blob/0dccf729b45fc6cf86c5842670d0cf502326a66a/src/main/java/com/animania/common/entities/cows/EntityAnimaniaCow.java#L247
Which will return false for GenericBehavior.interactCommon, thus calling super.processInteract().
The rest is handled by vanilla cows. I assume that roots is calling an event to check for shears, which must be EntityInteract I suppose. The only EntityInteract event that we have is here:
https://github.com/capnkirok/animaniamod/blob/880a43bc6cde0ce1a91535dee7578ea4770a1b92/src/main/java/com/animania/common/events/InteractHandler.java#L144,
and shears are mentioned nowhere, nor do we cancel it or something. 
I really don't think this is on our end.

**Comment by DoomRater** [comment]
Actually I do need to apologize.  I sorted out the issue and it was indeed with the config options of Roots.  Roots dev is adding something to clarify what went wrong if someone were to try writing the config the way I did.
