### ISSUE TITLE
Horses disable ANY right click function of main hand

### ISSUE THREAD

**Issue by DoomRater** [capnkirok/animaniamod#386]
### Expected Behavior
When I right click to activate a bow, I expect to be able to pull the bow back.  This should happen regardless of whether the bow is in primary or secondary hand.

### Actual Behavior
Aiming at cows and bulls and right clicking with a bow produces the desired response.
Aiming at horses and right clicking causes the horse to neigh disagreeably, blocking the right click function of the tool entirely when it is in the main hand.  Once the item is placed into the off hand, and the main hand is empty, the horse becomes mountable on right click.

### Steps to Reproduce
1. Obtain Shield, place in main hand
2. right click on horse
3. Swap item to off hand
4. right click on horse

### Version of Minecraft, version of Animania, Single Player or Server
Animania 1.7.3

**Comment by Tschipp** [comment]
I'm willing to bet that this is the case for vanilla too, but not 100% sure

**Comment by Tschipp** [comment]
Yes, in fact I was right.
