### ISSUE TITLE
Animania Lag Problem

### ISSUE THREAD

**Issue by Avocado-Boi** [capnkirok/animaniamod#388]
Animania causes a lot of lag, it is a huge problem for me every time and it is frustrating

minecraft version - 1.12.2  singleplayer
animania version - 1.7.3
craftstudioapi version - 1.0.1.95

in this screenshot I have 3 different kinds of chickens, cows, pigs, and rabbits, 2 females and 1 male
when I turn away from the farm the frames are between 50 and 70, but when I turn to the animals it drops to 20 or lower.

![2019-12-28_23 37 53](https://user-images.githubusercontent.com/59325784/71552524-c564b480-29cc-11ea-988f-6173112616e6.png)

![2019-12-28_23 39 05](https://user-images.githubusercontent.com/59325784/71552526-ce558600-29cc-11ea-9977-1bab19431bf4.png)

![2019-12-28_23 40 07](https://user-images.githubusercontent.com/59325784/71552536-d6adc100-29cc-11ea-9896-cb300f3db26b.png)

In this world I only have animania, craftstudio, and optifine.

**Comment by Tschipp** [comment]
What are your pc specs? How does this compare to vanilla (1.12.2) with vanilla animals?

**Comment by Avocado-Boi** [comment]
RAM is 8.00 GB, system is x64
my processor is intel(R) core(TM) i5-8300H

this is the normal vanilla 1.12.2 world

![2019-12-31_22 54 30](https://user-images.githubusercontent.com/59325784/71637992-4c11cf80-2c21-11ea-9ff9-daffcf4a9e28.png)

**Comment by Tschipp** [comment]
To be honest if this is your performance with vanilla this doesn't really surprise me. Animania animals *are* heavier because they do more. You can try to disable sleeping and enable ambiance mode so animals won't need to eat.
