### ISSUE TITLE
Chicken eggs won't hatch

### ISSUE THREAD

**Issue by BitBite112** [capnkirok/animaniamod#389]
### Expected Behavior
Chickens lay eggs in nest, rooster come and somehow fertilize them and then the chicks pop out.

### Actual Behavior
Chickens lay eggs in nest, eggs do not hatch. I've come back one time from a trip and there were
quite a few chickens, all fully grown, but after that I've only seen 2 chicks roaming about and then nothing. That was after DAYS too. Now I've only gotten nests brimming with eggs. I've got plenty of space, too.
### Steps to Reproduce
![image](https://user-images.githubusercontent.com/21090151/71556348-da2a6200-2a37-11ea-9c7b-7323bf692f87.png)

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2, using modpack Dungeons, Dragons and Space Shuttles

**Comment by Tschipp** [comment]
Looks like this is the mobcap actually working. Increase the limit in the config if you want more.
