### ISSUE TITLE
Calf (Friesian) falls through the floor (And other Phasing)

### ISSUE THREAD

**Issue by Fortist** [capnkirok/animaniamod#39]
I made a custom skyblock.
I had a few calves and they'd disappear after a while, so, after watching some closely it seems that at a certain age they'd sink into the floor. Most of the time they die, but one I picked up (Carry on) and placed back down, ran around a bit and sank into the floor again. 
What I noticed is the age thing, and they'd usually graze the grass before sinking. Probably do more indepth testing later.

In a semi related note, my pigs phase through fences, so thats a thing.

oh ye, Ver 1.4.7, 1.12, latest forge and what have you.

**Comment by Fortist** [comment]
Seems like every calf does it at a certain age.

**Comment by capnkirok** [comment]
Thanks for that. It's either related to the transition to adulthood (technically they die and are replaced by an adult), or because they increase in size and somehow are shifting down.

What 'material' is your floor made of? Can you share exact block? Screenshot of your setup would be great, too.

**Comment by Fortist** [comment]
Honestly it's just a bunch of cobblestone, I thought they would just phase through one layer, but it seems they keep going to suffocate.
https://i.imgur.com/qV1yoLa.png

In my testworld, which is quartz on layered wool, all the calves spawned in sunk into the ground and suffocated, after falling down another block.

**Comment by Deshiba** [comment]
I tested this on a voidworld with just animania, they don't glitch trough the block as of yet. I let it run for 5 hours and it still hasn't happened.

**Comment by Fortist** [comment]
Probably some mod shenanigans, Ill figure it out later I guess.
