### ISSUE TITLE
Riding Crops Don't Work

### ISSUE THREAD

**Issue by SafsoufaS** [capnkirok/animaniamod#390]
**Expected Behavior:**
Using the riding crop on a well-fed and watered draft horse should be able to let me ride it without a saddle and right-clicking again should speed the horse up.

**Actual Behavior:**
Riding crop doesn't work at all. I can sit on the horse with an empty hand or with any item but with a riding crop nothing is different

**Steps to Reproduce:**
1. Feed and water the draft horse.
2. Right-click with a riding crop.
3. Attempt to ride it.

**Version of Minecraft, version of Animania, Single Player or Server:**
1.12.2 forge Minecraft and 1.7.3 Animania. Both Single Player and Server.

I didn't provide screenshots for there is no use for it.

**Comment by Echoweaver** [comment]
@SafsoufaS Hmm. Not sure this issue page is being monitored.

As far as I can tell, the riding crop functionality has been replaced by craftable saddles, but I can't find any place in the documentation this is stated. It's discussed in posts on some Minecraft forums, and I'm pretty sure I remember the release notes when this change was made. (I read a lot of release notes.)
