### ISSUE TITLE
Clef and Mo'creatures bug

### ISSUE THREAD

**Issue by Dnksh** [capnkirok/animaniamod#395]
### Expected Behavior
Every item should have it's texture, not pink-black and other colours

### Actual Behavior
Some item's from mo'creatures and growthcraft don't have their own texture. It happens whenever clef and animania are installed, uninstalling animania reverts only some textures.

### Steps to Reproduce
what

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2     1.7.3      either single player and server

### Screenshots encouraged
![74101713-1d024e00-4b3d-11ea-959d-b15accf80dca](https://user-images.githubusercontent.com/42710750/74238724-a5682680-4cd6-11ea-906e-e9113e5fbca3.png)

**Comment by Dnksh** [comment]
I've written already on clef issues but i think it should be here too.

**Comment by Tschipp** [comment]
If it still happens when animania it not installed, it clearly isn't an animania issue.
