### ISSUE TITLE
Baby Vanilla Pigs Spawning

### ISSUE THREAD

**Issue by KingNexes** [capnkirok/animaniamod#396]
![2020-02-14_16 09 34](https://user-images.githubusercontent.com/60949137/74547761-8bcc1680-4f44-11ea-993e-86ef0f42bfce.png)
### Expected Behavior
Vanilla mobs shouldn't spawn naturally, only through 'manual' spawning

### Actual Behavior
Once loading onto the server I went to my animania animals; chickens, peacocks, cows, sheep, and there are baby vanilla pigs with them as if some of the animals had been replaced with vanilla pigs (not confirmed). 
I found that ocelots were spawning in the jungle, I golden lassoed 2 of them and left them in a pen. left the area and came back a while later and the ocelots had gone and some vanilla pigs were there.
Any animania animal seems to pop out some baby pigs either instead of their own young or aswell as their own. 

Is there any mod conflicts perhaps. 

### Steps to Reproduce
as far as I can tell just let them spawn or have animals breed together

### Version of Minecraft, version of Animania, Single Player or Server
MC - 1.12.2 Animania - 1.7.3 Server

**Comment by Tschipp** [comment]
It seems like you have many mods. I can't really tell from this what is going on. It could be that some random mod interaction is spawning the pigs, rather than natural spawning. Have you experienced the spawning outside of your "enclosure"?

**Comment by KingNexes** [comment]
> 
> 
> It seems like you have many mods. I can't really tell from this what is going on. It could be that some random mod interaction is spawning the pigs, rather than natural spawning. Have you experienced the spawning outside of your "enclosure"?

We do have about 109 I believe. I believe it is only vanilla pigs that are spawning and yes they spawn everywhere, they spawn with animania animals too so I often see an animania pig with a baby vanilla pig. Thank you for your reply.

**Comment by Tschipp** [comment]
Hmm, do you have a mod that somehow relates to pigs?

**Comment by KingNexes** [comment]
> Hmm, do you have a mod that somehow relates to pigs?

Not that we know of no. I could add a list of our mods of you would like.

**Comment by Tschipp** [comment]
Yeah a modlist would be good, but I don't have the time to go through 109 mods and find out which one is causing the conflict

**Comment by KingNexes** [comment]
> Yeah a modlist would be good, but I don't have the time to go through 109 mods and find out which one is causing the conflict

Alright then I can add the main mods for you. Yea no worries I understand. Thank you.
