### ISSUE TITLE
Can't uninstall Animania

### ISSUE THREAD

**Issue by imytan** [capnkirok/animaniamod#397]
### Expected Behavior

I can't uninstall the mod, since it says I have the entities in the world and I don't know what to do to remove them.

### Actual Behavior

I have uninstalled the settings and the mod of the folder where it belongs, but it also does not let me start the server ... The problem is that the server is one with a contracted host and I cannot have it closed for a long time or allow me to create a new world, How can I delete the entities?

### Version of Minecraft, version of Animania, Single Player or Server

1.12.2 version for server

**Comment by Tschipp** [comment]
When you remove mods it will obvioulsy remove entities from the world as well. 
Usually it helps if you read the console when checking for erros. There it will say to type /fml confirm (or something along those lines). When you do that, the server starts.
