### ISSUE TITLE
Cows and bulls are not breeding

### ISSUE THREAD

**Issue by aforre** [capnkirok/animaniamod#398]
### Expected Behavior
The bulls and cows should breed, I have fed them stacks with wheat and flowers. They have a nearby water source and lots of troughs filled with wheat and water. Their habitat is large with at least 25 blocks in length. They are all well fed.

### Actual Behavior
When I feed them hearts show, but they don’t react or interact with each other. They only stand there wanting more food. When I put the food away they go back to doing their own business. And not breeding/kissing. When hovering over the females it says they are fertile, never pregnant.

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft version 1.12.2, with the latest animania version. Single player. I have serene seasons installed with some other mods if it matters.

**Comment by Tschipp** [comment]
How many animals do you have? Due to constant lag complaints we force quite a tight spawn limit that also applies to breeding. You can increase that limit in the config.

**Comment by aforre** [comment]
I have 12 cows/bulls, and the spawn limit for breeding was set to 15 in the config.

**Comment by aforre** [comment]
That was it! Thanks for the help :)

I didn’t think it would resolve it because I really only have 12 cows but I also had 2 goats.

**Comment by Tschipp** [comment]
Yeah, the new system overcompensates because we were getting so many reports of lag. If you pc can handle it, feel free to turn up this limit.

**Comment by aforre** [comment]
Do you know how much each creature affects fps? Do you think i would experience any problems with a GTX 1660 and 6 ram allocated? Thanks anyways! :)

**Comment by Tschipp** [comment]
I don't have a figure, it's all very system dependent. Minecraft basically only runs on the cpu though, so the graphics card doesn't really matter
