### ISSUE TITLE
Invisible Animals

### ISSUE THREAD

**Issue by Ommetaphilliac** [capnkirok/animaniamod#40]
### Expected Behavior
Visible animals

### Actual Behavior
All animals are invisible, when spawn egg is used I hear the animal but it is invisible.

### Steps to Reproduce
Created multiple worlds with same result.

### Version of Minecraft, version of Animania, Single Player or Server

12.2

**Comment by capnkirok** [comment]
Hey @Ommetaphilliac 

Some questions back:
- Which version of Animania are you using?
- Which spawn eggs... Vanilla or Animana, and which animal?
- Are you on Server or Client
- Can you send me a screenshot of your world? (so I can see how many animals you have)

PC
