### ISSUE TITLE
Cows not breeding

### ISSUE THREAD

**Issue by Jigbashmop** [capnkirok/animaniamod#404]
### Expected Behavior
When happy, cows will breed.

### Actual Behavior
Cows will not breed, even when happy.

### Steps to Reproduce
Set up a pen with any breed of cow, feed, water, and wait. I have five mooshrooms; one bull and four cows. The config has been set to allow one male to mate with multiple females. The cow spawn limit is 40, and I've cleared out any nearby cows.

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft: 1.12.2
Animania: 1.7.3 (It should be noted that reverting to 1.7.2 solves my problem)

**Comment by Tschipp** [comment]
The spawn limit doesn't matter in the case of breeding. You need to change the entityBreedingLimit in the Care & Feeding tab
