### ISSUE TITLE
[1.12.2] Milk disappearing from buckets in survival multiplayer

### ISSUE THREAD

**Issue by 346184** [capnkirok/animaniamod#405]
These earlier issues seem to be about the same problem, but were closed due to being "probably fixed in the meantime":
https://github.com/capnkirok/animaniamod/issues/343
https://github.com/capnkirok/animaniamod/issues/136

I'm still running into the issue with the latest Animania version on 1.12.2 on our survival multiplayer server.

**Comment by Tschipp** [comment]
I'll check this out again

**Comment by 346184** [comment]
FWIW, it happens everytime for everyone of us on our server.

Animania sheeps giving milk seems to work fine however.

**Comment by Tschipp** [comment]
That is interesting information, thanks

**Comment by 346184** [comment]
Seems I spoke too soon - it also happens sometimes with the sheep. Couldn't spot a pattern yet :(

**Comment by kil0byt3** [comment]
Also occurring in our modpack for many players (1.12). Any updates here? https://github.com/CalaMariGold/Rebirth-Of-The-Night/issues/139
