### ISSUE TITLE
Mobs dont spawn

### ISSUE THREAD

**Issue by CeratoRaptor** [capnkirok/animaniamod#407]
### Expected Behavior
I expected to see the animania creatures.

### Actual Behavior
Nothing there :|

### Steps to Reproduce
Start a new world, and explore a bit.

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2, animania 1.7.3, single player world.

**Comment by DonTheBreton** [comment]
Sounds like you may have not enabled spawning in the config. Have you installed Forge? Did you choose the correct installation from your launcher?

**Comment by capnkirok** [comment]
Animania does not replace animals in an existing world.

**Comment by Tschipp** [comment]
Closing this...
