### ISSUE TITLE
Opal Peahen Has Taupe Peahen Texture

### ISSUE THREAD

**Issue by RaliaTheWolf** [capnkirok/animaniamod#41]
**Expected Behavior**
Purple peahens have the purple peahen texture

**Actual Behavior**
Purple peahens have the taupe peahen texture

**Steps to Reproduce**
Spawn a purple peahen

**Version of Minecraft, version of Animania, Single Player or Server**
MC version 1.12.2; Animania version 1.4.7; Singleplayer

**Comment by RaliaTheWolf** [comment]
Okay so I just realized that there are two Animania GitHubs? This one called animaniamod and the other one just called animania... For future reference, which one should I post things to? I didn’t even realize that I clicked on this one until after I made the report... XD

**Comment by capnkirok** [comment]
This one is the correct one now :)

**Comment by capnkirok** [comment]
Hmmm... I think your description is wrong. You say the Opal is Taupe, but then description mentions purple.

However, when I look at them in game, they are all different, though Opal is similar to Taupe. 

![2017-09-23_19 22 18](https://user-images.githubusercontent.com/9628379/38957066-d154973e-4359-11e8-8886-2b3c83372ea7.png)

**Comment by RaliaTheWolf** [comment]
Ah okay! I’ll post here from now on then!

Oh I might have thought they were the same... Hold on let me spawn some really quick ^^;

**Comment by RaliaTheWolf** [comment]
Oh that’s embarrassing... I guess I thought the Opal was a bit more colorful... XD Sorry bout that!
