### ISSUE TITLE
Horse Teleporting

### ISSUE THREAD

**Issue by DonTheBreton** [capnkirok/animaniamod#410]
### Expected Behavior
Horses traverse landscape in a logical manner.

### Actual Behavior
While being ridden, horse and player occasionally rapidly teleport into the air. Chunks appear to unload and reload during this process.

### Steps to Reproduce
1. Place saddle on Draft Horse.
2. Ride draft horse.
3. Experience may vary.

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft v. 1.12.2
Forge: 14.23.5.2847
Animania: 1.12.2-1.7.3

Modpack for reference: https://www.curseforge.com/minecraft/modpacks/solstice/files
version: 0.3.2

### Screenshots encouraged
Video example: https://clips.twitch.tv/CuriousWrongOwlOneHand

**Comment by Tschipp** [comment]
This does definitely not happen just with animania. Is this on a server?

**Comment by DonTheBreton** [comment]
Yes, this is on a server using the Solstice Modpack that I linked. No other mods are designed to change the functionality of horses though. So I'm stumped as to what could be causing it. I'll continue to investigate.

**Comment by capnkirok** [comment]
There has been a longstanding bug in the vanilla MC code which can cause horses to teleport, which is what I've always assumed this is (since our horses extend the vanilla class). I've also seen teleportation into the void (you can ask Darkosto about that one). Might be worth another look.
