### ISSUE TITLE
New animal ideas

### ISSUE THREAD

**Issue by HatcheryRoosters** [capnkirok/animaniamod#411]
The Old Jerseys should be bought back as Simmental (Milk and Meat), and the Horned Angus as Fighting Cattle (Meat). And then there was some image on Twitter stealing your models, and there's a Rhode Island red Rooster but Yellow instead, (I have No clue what breed it should be but I cropped it so it's just the rooster), and then Razzleberry's MC Pig she made, you could add it as a Landrace (Regular Meat breed).
![Fighting Cattle](https://user-images.githubusercontent.com/36781707/78722198-fb340600-78f6-11ea-8232-fa9b49ad70d7.png)
![LandRace 2](https://user-images.githubusercontent.com/36781707/78722204-00915080-78f7-11ea-8110-aa8d83420e3c.jpg)
![LandRace](https://user-images.githubusercontent.com/36781707/78722205-00915080-78f7-11ea-84ff-3632f7c71137.jpg)
![Unknown Golden Rooster](https://user-images.githubusercontent.com/36781707/78722214-04bd6e00-78f7-11ea-974d-e8bb708421bc.jpg)
![Old Jersey:Simmental](https://user-images.githubusercontent.com/36781707/78722232-0b4be580-78f7-11ea-9354-b920ce2b8525.png)
Please respond, thanks!

**Comment by Tschipp** [comment]
The yellow rhode island rooster and the jersey maybe, but the others are basically the same as animals we already have.

**Comment by HatcheryRoosters** [comment]
Vanilla Pigs are landraces

**Comment by Tschipp** [comment]
vanilla pigs are vanilla pigs. We are not adding vanilla pigs.

**Comment by HatcheryRoosters** [comment]
How about red Holsteins instead in exchange for Landraces
