### ISSUE TITLE
[1.12.2] Dispenser seed placement conflict with Botania

### ISSUE THREAD

**Issue by Sewef** [capnkirok/animaniamod#412]
### Expected Behavior
The Dispenser should place seed on the ground

### Actual Behavior
The item is dropped
![SeedDispenser](https://user-images.githubusercontent.com/27089398/79052371-58e98a80-7c36-11ea-935b-21f10a198dbb.gif)

### Steps to Reproduce
1. Install Botania
2. Enjoy

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12.2
Animania 1.7.3
Botania 1.10-363

I know it should be handled by https://github.com/capnkirok/animaniamod/blob/1.12/src/main/java/com/animania/common/handler/DispenserHandler.java
But it seems to be broken :(

**Comment by Tschipp** [comment]
I don't see what could be causing this. What is your config?

**Comment by Sewef** [comment]
Default one
botania.cfg : https://pastebin.com/a2M1Sjxe
animania.cfg : https://pastebin.com/pvkbLFXW
