### ISSUE TITLE
Suggestion: Longer Range Cattle Attacks

### ISSUE THREAD

**Issue by RexOrbis** [capnkirok/animaniamod#416]
This may seem quite the minor complaint, but just seeing as your mod is already really great and basically my favourite choice for an animal overhaul, I just thought I might give the only suggestion I had about it in order to make it that bit better.

I really like how you added that cattle are now essentially neutral and will attack enemies that strike them, which I think is a great improvement towards their previous behaviour. My only critique is that in order to do damage, it seems to me that the cattle have to essentially enter the enemy's model to land a hit, which I think is a bit close. Generally, vanilla mobs have a bit more clearance between themselves and their melee quarries, and by testing a fight between a zombie and a bull, I find that the zombie continually wins by just having superior reach despite doing less damage, which seems unintentional to me. I'd suggest upping the range a bit so it looks more like a gore attack instead of a ram.

Thanks for your time!

**Comment by Tschipp** [comment]
Hey, we've had many people complain that the range is already too big, so I won't be making it any bigger, sorry!
