### ISSUE TITLE
Test Build Bugs?

### ISSUE THREAD

**Issue by RaliaTheWolf** [capnkirok/animaniamod#418]
I'm using the newest test build (the one with the base, farm, and extra, I believe that is 2.0) and I have found a few bugs I think.

-Hamsters and hedgehogs teleport to the player if they are not sitting (thus far this has not happened with my ferrets, but they won't walk around anyway) (according to in-game manual this is not supposed to happen)
-Hamsters, hedgehogs, and ferrets cannot be picked up by the player to sit on their shoulder
-Butcher knife no longer neuters rabbits (I haven't tested it with other animals yet)
-Animals in the in-game manual no longer spin (not sure if that's intentional, although they're stuck facing forward and are hard to see coloring and whatnot as they are)

I can add more details (if I have any...) or open other issue things if some of these are not supposed to happen and you need more info.

**Comment by RaliaTheWolf** [comment]
Update: Tried the butcher knife neuter thing with the other animals. Draft horses, cattle, pigs, goats, and sheep also don't work. I didn't try it with peacocks or roosters because that wasn't a thing (although it could be a nice thing to add?). As for animals that have previously been neutered before this update, I haven't checked to see if they still don't breed since I created a new world just for testing this update.

If it helps at all, everything I've done has been in singleplayer creative mode (this goes for the above comment too).

Also, calves float when they sleep... Cows and bulls do not, nor do any other animals (adult or otherwise) from what I've seen.
![2020-04-21_21 31 27](https://user-images.githubusercontent.com/28816115/79934241-b3919c00-8417-11ea-8833-db4ab90972b8.png)

Also also, baby fainting goats don't faint (I don't remember if they did in the first place though).

Also also also, the dorper lamb egg has the same texture as the jacob sheep eggs.
![2020-04-21_21 44 29](https://user-images.githubusercontent.com/28816115/79934934-51399b00-8419-11ea-84d1-6c82f768aa07.png)

**Comment by Tschipp** [comment]
You are right about the fainting goats, the hamsters teleporting and the floating calves. Can't reproduce the other issues though...

**Comment by RaliaTheWolf** [comment]
Hmm... I'll try the new test versions you uploaded in a new world and delete the config again and try it all again and see if it's still being weird.

**Comment by Tschipp** [comment]
It looks like the fainting goat children never fainted... but I added that because why not

**Comment by RaliaTheWolf** [comment]
Lol sounds good!

**Comment by Tschipp** [comment]
Oh and it looks like the pet teleportation works... are you sure you set the config to false?

**Comment by RaliaTheWolf** [comment]
There's a config option for that?? I hadn't touched the config. I can see what it was set to when I get my laptop out later. Is it set to true on default?

**Comment by Tschipp** [comment]
Yes

**Comment by RaliaTheWolf** [comment]
Huh I'll double check then. In the manual ingame it says they don't
teleport so I guess I figured there wasn't a config for it. I'll let
you know what it was set to.

**Comment by Tschipp** [comment]
I'll adjust the manual
