### ISSUE TITLE
Animania conflict with spongeforge

### ISSUE THREAD

**Issue by AiMLESS2k** [capnkirok/animaniamod#422]
Hey everybody.
So i came across a strange bug where i can't join my server.
I had some pigs in my base and everytime i connected to my server, my whole game was freeze forever. After looking into the log from the Server i saw it had to do something with the pigs.
After my base mate removed the pigs from our base i was able to connect again and it worked just fine. There is no known way to reproduce this since everybody else on the server (even my base mate) could connect with no problems.

reported this bug also to sponge.

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft: 1.12.2
Animania: animania-1.12.2-1.6.2
Minecraft Forge: 14.23.5.2847
Single Player or Server: Server

Latest.log and error: https://gist.github.com/GermanY1337/b561c52691935b3386b2b87c699b38f8

**Comment by Tschipp** [comment]
You are using an ancient version of animania, and your config file is also full of ancient stuff. Please update to the latest and refresh/regenerate your config
