### ISSUE TITLE
[Bug] Vanilla Animals Still Spawn [Test Build]

### ISSUE THREAD

**Issue by RaliaTheWolf** [capnkirok/animaniamod#425]
I made a new world to test the test build and vanilla animals spawned in it, even though the config is set to replace them. I had deleted my previous config (and hadn't touched the new one) and like I mentioned, this is a brand new world. Animania ones spawned too but there were mostly vanilla animals.

**Comment by RaliaTheWolf** [comment]
I'm also still unable to neuter my animals...

**Comment by Tschipp** [comment]
What kind of animals? How are you trying to neuter them?

**Comment by RaliaTheWolf** [comment]
My bulls and I also tried my draft horse. I'm using the butcher knife. Or carving knife? The Animania knife

**Comment by Tschipp** [comment]
Okay, and just to be sure, you are right clicking them, right?

**Comment by RaliaTheWolf** [comment]
Yes I'm right clicking

**Comment by HatcheryRoosters** [comment]
As of Animania 2.0, vanilla animals that spawned will not convert, and you can still use eggs to spawn them

**Comment by Tschipp** [comment]
Still cannot reproduce this... Not the issues with sterilisation or with spawning...

**Comment by RaliaTheWolf** [comment]
Hmm... I'll do some more testing when I get my laptop fixed and see if I
can recreate the issue.
