### ISSUE TITLE
Inspired by discord 

### ISSUE THREAD

**Issue by HatcheryRoosters** [capnkirok/animaniamod#428]
A couple months ago I saw some animal models on discord, these models are not mine But I think they would be pretty excellent animals.
[Animania.zip](https://github.com/capnkirok/animaniamod/files/4705001/Animania.zip)

**Comment by Tschipp** [comment]
Who made these? We can't just use any random models without knowing who made them.

**Comment by HatcheryRoosters** [comment]
Murbis created the bird models, and JPMkn made the alpaca and Clydesale models

**Comment by mk1213123** [comment]
that is supposed to be animania addon and i told 
Purplicious_Cow_ about it
