### ISSUE TITLE
Replacing existing vanilla mobs with Animania mobs?

### ISSUE THREAD

**Issue by tumbraaa** [capnkirok/animaniamod#431]
Is it possible for me to replace existing mobs with animania mobs (in an already existing world)? I played around with the configs but I can't quite seem to figure it out, is it even possible?

**Comment by Tschipp** [comment]
No not currently.

**Comment by HatcheryRoosters** [comment]
That used to be the case, then vanilla animals just vanished, then existing vanilla animals no longer  got deleted, you can kill them off though
