### ISSUE TITLE
"Split" modules misunderstanding and questions

### ISSUE THREAD

**Issue by GoldenGod48** [capnkirok/animaniamod#432]
I tried to ask on discord but for some reason it wont let me. You mentiond splitting the mod, that i understand. However, how many modules and what features are in each module is what I am wondering. Also, (if i dont annoy you by asking) how far done are you with the split and/or update to 1.15. (I am assuming 1.15 as that seems to be the next main modding version.)

**Comment by Tschipp** [comment]
Hey, all of these questions are answered in the FAQ. Also, what exactly do you mean with you couldn't ask? I reworked the permissions yesterday, but it should all work as normal now.
