### ISSUE TITLE
Comparators don't always update when animals eat from trough

### ISSUE THREAD

**Issue by dlowe-net** [capnkirok/animaniamod#433]
### Expected Behavior
Attached comparator should emit 0 signal when trough is empty after animals eat.

### Actual Behavior
Attached comparator emits previous (strength 1) signal and never updates. This may only occur when chunk is being loaded, since it does seem to work while I'm watching it.

### Steps to Reproduce
Make the following redstone:
```
TCB    T - Trough    C - Comparator    B - Any block
TD/     D - Dropper   / - redstone torch attached to B
```

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12.2, Animania 1.7.3, both single player and server

### Screenshots encouraged

![image](https://user-images.githubusercontent.com/188363/86495844-f5f52480-bd48-11ea-813f-83953f675876.png)

**Comment by PiggiesGoSqueal** [comment]
> Attached comparator emits previous (strength 1) signal and never updates. This may only occur when chunk is loaded, since it does seem to work while I'm watching it.

Did you mean when chunk **isn't** loaded? Because chunk would be loaded if you're watching it.

**Comment by dlowe-net** [comment]
"when chunk is _being_ loaded" I should have said.
