### ISSUE TITLE
[Bug] Rein recipe error with leather works

### ISSUE THREAD

**Issue by JhonDxD** [capnkirok/animaniamod#434]
### Expected Behavior
That there would be no problem with the recipes between mods

### Actual Behavior
There is a problem with the reins recipe as it conflicts with the leather sheet recipe of the leather works mod

### Steps to Reproduce
How can I deactivate the recipe of the rein shown by animalia

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2 - 1.7.0 - server

### Screenshots encouraged
![image](https://user-images.githubusercontent.com/67932180/86668278-1aa30380-bfb8-11ea-8701-a76c6f1d2805.png)
![image](https://user-images.githubusercontent.com/67932180/86668319-242c6b80-bfb8-11ea-854a-dca2bd73506b.png)

**Comment by Tschipp** [comment]
You can change the recipes with any tool like crafttweaker.
