### ISSUE TITLE
animals does not spawn naturally 

### ISSUE THREAD

**Issue by mk1213123** [capnkirok/animaniamod#435]
animals does not spawn

**Comment by Tschipp** [comment]
The (vanilla) spawning manager spawns most passive mobs (like animals) when a chunk is created for the first time. Then it significantly slows down and occasionally spawns new animals in already generated chunks, but only if the passive mobcap isn't full. If you can't find any Animania animals, try to remove (kill) all existing animals or to generate new chunks in your world.
