### ISSUE TITLE
[Bug] Animania Food gives full heal restore

### ISSUE THREAD

**Issue by talesofmabria** [capnkirok/animaniamod#438]
### Expected Behavior
Eating food gives a health restore similar to health potions.  I.E. Instant Health I should give 2 hearts (4 HP), Instant Health II should give 4 hearts (8 HP), etc.

### Actual Behavior
https://www.youtube.com/watch?v=IFefM8nuzT4
I've given myself a health boost in this demonstration, just to show how even the Instant Health I food gives way too much.

### Steps to Reproduce
Get low health, and eat a healing food item.

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2 MC, Animania 1.7.3, Singleplayer and Server (tested on both)

### Screenshots encouraged
See above for video

**Comment by James103** [comment]
The following foods give Instant Health potion effects that last for multiple ticks, hence why they heal so much more than expected:

`cheese_omelette` (2 * 16 = 32 HP restored)
https://github.com/capnkirok/animaniamod/blob/b84136973812569010b0d77369a3065aba600729/src/main/java/com/animania/addons/farm/common/handler/FarmAddonItemHandler.java#L130
`cooked_prime_beef` (10 * 8 = 80 HP restored)
`cooked_prime_steak` (5 * 8 = 40 HP restored)
https://github.com/capnkirok/animaniamod/blob/b84136973812569010b0d77369a3065aba600729/src/main/java/com/animania/addons/farm/common/handler/FarmAddonItemHandler.java#L141-L143
`cooked_prime_mutton` (5 * 8 = 40 HP restored)
https://github.com/capnkirok/animaniamod/blob/b84136973812569010b0d77369a3065aba600729/src/main/java/com/animania/addons/farm/common/handler/FarmAddonItemHandler.java#L158
`friesian_cheese_wedge` (6 * 16 = 96 HP restored)
`holstein_cheese_wedge` (12 * 16 = 192 HP restored)
`jersey_cheese_wedge` (10 * 16 = 160 HP restored)
`sheep_cheese_wedge` (10 * 4 = 40 HP restored)
https://github.com/capnkirok/animaniamod/blob/b84136973812569010b0d77369a3065aba600729/src/main/java/com/animania/addons/farm/common/handler/FarmAddonItemHandler.java#L171-L175
Block forms of the above cheese wedges give same Instant Health effects.
https://github.com/capnkirok/animaniamod/blob/b84136973812569010b0d77369a3065aba600729/src/main/java/com/animania/addons/farm/common/block/BlockCheese.java#L126-L133
Note that the Forge documents have the argument order as `new PotionEffect(Potion potionIn, int durationIn, int amplifierIn, boolean ambientIn, boolean showParticlesIn)`.

**Comment by Tschipp** [comment]
You are right, thanks for going through this 👍
