### ISSUE TITLE
[Bug] animal spawn on any type of solid block

### ISSUE THREAD

**Issue by Ethern8ai** [capnkirok/animaniamod#441]
### Expected Behavior
Spawn are supposed to be vanilla like, grass and some minimum space.

### Actual Behavior
Spawn in any solid block and small surfaces, line of blocks and mob farm that does not spawn spiders or enderman.

### Steps to Reproduce
regular version of the mod (1.7.3) and the beta version (the split one) in my skyblock modpack, on cobble and dirt lines and in my mob spawner in netherex bricks.

### Version of Minecraft, version of Animania, Single Player or Server
minecraft 1.12.2
animania latest release and latest beta
modded single player skyblock

list of all the other mods in my pack:
[other mods.txt](https://github.com/capnkirok/animaniamod/files/5193293/other.mods.txt)

my void biome from OTG:
[void txt.txt](https://github.com/capnkirok/animaniamod/files/5193299/void.txt.txt)

my otg world config:
[world config txt.txt](https://github.com/capnkirok/animaniamod/files/5193302/world.config.txt.txt)

### Screenshots encouraged

![2020-08-30_01 56 33](https://user-images.githubusercontent.com/17188943/92567865-3a83cb80-f276-11ea-8cf7-a92ce39b1a12.png)

Thank you

**Comment by Tschipp** [comment]
I'm able to confirm this. I'm gonna start removing mods (except OTG) until I figure out what is the problem

**Comment by Tschipp** [comment]
Alright, can now confirm that this even occurs without any mods other than animania. Will investigate more.

**Comment by Tschipp** [comment]
This seems to no longer occur on the latest test build, so I'm marking this as fixed.

**Comment by Ethern8ai** [comment]
Yes Totally fixed, Great job! ( and so quick :O )
Thank you!

**Comment by Tschipp** [comment]
Gonna keep this open until I publicly release it
