### ISSUE TITLE
Addons not Working

### ISSUE THREAD

**Issue by Flutterdragon** [capnkirok/animaniamod#442]
Hi! love your mod! I wanted to let you know the links for the addons for Animania are not working. They keep saying page not found on both of them. And the mod won't add in any features without them. Let me know if this can be fixed. If not that's fine. Thanks in advance!

Flutterdragon

**Comment by Tschipp** [comment]
Yes, sorry, the addons are not available yet. They will probably be approved by curse on monday (because they don't work on the weekend). Please use the previous animania version until then.
