### ISSUE TITLE
[Crash] Terrain generation crash with another mod

### ISSUE THREAD

**Issue by RodrigoTaipe93** [capnkirok/animaniamod#445]
### Crash log, latest.log

- https://paste.ee/p/GYW2V

-----------message-----------------------------------------------

Hello,

Recently I updated the following mods:

- Animania

- Treasure 2

for my private modpack. However, it now triggers a crash with Vanilla Tech.

This happens when I'm trying to create new terrain or a new chunk in an existing world.

I'm sending the crash to all the parties involved.

The previous versions of Animania or Treasure 2, didn't trigger a crash to Vanilla Tech.

Hope anyone can find a solution, since I don't really want to lose my world:

Crash: https://paste.ee/p/GYW2V

Latest log (too heavy for pastebin): https://mega.nz/file/dtsB1I7S#CHcXlqHcWOlc_525i-c1x41tAsDL8sWToMZV3exHhA4

**Comment by Tschipp** [comment]
If you downgrade just animania, does the crash still occur?

**Comment by RodrigoTaipe93** [comment]
Hello,
So, I’ve been trying to check what the issue was. So here are the following crash logs

1.	Crash log with all the mods, plus the newer versions:

-	https://paste.ee/p/wQZOI

2.	Crash log of only Animania, Treasure 2, and Vanilla Tech:

-	https://paste.ee/p/NzzLG

3.	Cras log of only Animania and Vanilla Tech

-	https://paste.ee/p/8JqqX

4.	Crash log of only Treasure 2 and Vanilla Tech

-	https://paste.ee/p/r8bjr

5.	Crash log of only Vanilla Tech

-	https://paste.ee/p/jcioB

6.	Log of Animania and Treasure 2

-	https://paste.ee/p/Y4awo

For some reason, Vanilla Tech (and Hammerlib) are failing. I don’t know why.
With previous versions of Animania and Treasure, I didn’t have this issue. Now Vanilla Tech all of a sudden decides to go wild. Strange, indeed.
Anyways, my apologies for bothering the authors of Animania and Treasure 2. 
However, please don’t make too many radical changes to your mods. Having a big modpack is like balancing on a tightrope.

**Comment by Tschipp** [comment]
To be honest, this looks a lot like an issue with Vanilla Tech, because
1. All the crashes only mention Vanilla Tech packages
2. The crashes only occur when Vanilla Tech is involved

**Comment by Tschipp** [comment]
Going to close this as I don't think it's an animania issue.
