### ISSUE TITLE
Chunk-Pregenerator by Speiger crashes when using Animania Base.

### ISSUE THREAD

**Issue by GoldenGod48** [capnkirok/animaniamod#449]
### Actual Behavior 
When trying to pregenerate a world using the previewer, the pregenerator crashes. When trying to pregenerate when inside the world, the command won't work

### Version of Minecraft, version of Animania, Single Player or Server
The newest Animania Base for 1.12.2 single player

### Crash log, latest.log
[crash-2020-05-20_17.17.28-client.txt](https://github.com/capnkirok/animaniamod/files/5250506/crash-2020-05-20_17.17.28-client.txt)

**Comment by Nanamiya738** [comment]
that happens to me too, once I create a new world.
it just somehow crash with 「Exception ticking world」or「No OpenGL context found」

same use newest Animania & CraftStudio, Forge is 2854, single player

**Comment by Tschipp** [comment]
Does this error occur without optifine?

**Comment by Nanamiya738** [comment]
right, I only use Animania& CraftStudio, no Optifine.

but it crash almost 3 second after open the world&preview

**Comment by Tschipp** [comment]
@GoldenGod48 does this error occur for you without optifine?

**Comment by Tschipp** [comment]
I'm going to need more info for this. Can you produce a crash for this that does not have optifine installed? Please send me that log.
