### ISSUE TITLE
Animania 1.4.8 for 1.12.2 shows update prompt to 1.4.8

### ISSUE THREAD

**Issue by MauveCloud** [capnkirok/animaniamod#45]
### Expected Behavior
Animania 1.4.8 suppresses update prompt (at least until 1.4.9 is available)

### Actual Behavior
Animania 1.4.8 shows update prompt (to 1.4.8!)
Opening the Forge mod list, the top text lines of the description are:
```
Animania
Version: 1.4.8 (1.4.7)
```

### Steps to Reproduce
1. Install Animania 1.4.8
2. Launch Minecraft.
3. Open a world.

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12.2
Animania 1.4.8
Forge 14.23.2.2655

### Screenshots encouraged
![2018-04-23_08 50 38](https://user-images.githubusercontent.com/8942955/39137934-aaa8ee1e-46d3-11e8-83e6-526bd02a6b95.png)
![2018-04-23_08 50 49](https://user-images.githubusercontent.com/8942955/39137941-ae6a9c32-46d3-11e8-80a1-2889369092a8.png)

**Comment by capnkirok** [comment]
Gah. Yeah, unfortunately, need to update the jar.

**Comment by capnkirok** [comment]
I'm just going to change my checker for now.
