### ISSUE TITLE
[Bug]ocelots are not turning into cats

### ISSUE THREAD

**Issue by Hgmega** [capnkirok/animaniamod#452]
I was decorating my world and decided to put ocelots, when I went to domesticate them, instead of becoming cats, they just let their hearts out and were not domesticated and that's how it is every time I try

![image](https://user-images.githubusercontent.com/71907295/94321518-1eff0d00-ff66-11ea-9b22-a3522ae3490e.png)

**Comment by Hgmega** [comment]
It's not a problem vanilla, because only with this mod that happens

**Comment by Tschipp** [comment]
Works totally fine for me. Do you have any other mods?
