### ISSUE TITLE
[crash] Crash when using Dynamicsurround

### ISSUE THREAD

**Issue by SakuraWuhen** [capnkirok/animaniamod#453]
### Expected Behavior
A crash is triggered when moving in the world, the error report points to the Animania and dynamic surround
Although this crash points to dynamicsurround, I have been using this version of dynamicsurround and the old version of Animal Valley. I think it is the new version of Animania that caused this problem, so I will contact you first

### Version of Minecraft, version of Animania, Single Player or Server
Animania 2.0 （All modules and All up to date）
forge 2854
spongeforge 2838-7.1.8
Run in sponge server environment

### Crash log, latest.log
[crash-2020-10-01_01.14.21-client.txt](https://github.com/capnkirok/animaniamod/files/5307366/crash-2020-10-01_01.14.21-client.txt)

Thanks for your great work :）

**Comment by aking4125** [comment]
Hey,

We're getting the same problem here on our Private Forge server. We are not running SpongeForge. 
[crash-2020-10-04_03.12.03-client.txt](https://github.com/capnkirok/animaniamod/files/5324622/crash-2020-10-04_03.12.03-client.txt)

Once a user enters the offending area. The screen stops rendering everything and all you see is the blue or grey skybox. After some time, VanillaFix will appear reporting the crash listed above. 

TPing the offending player out of the area saves the player. Currently performing a test where Dynamic Surroundings is temporarily removed. I can also confirm the pre-modular version of Animania worked perfectly fine with this version of Dynamic Surroundings as we just updated Animania on our server. 

EDIT: So far disabling Dynamic Surroundings mostly fixes the issue for us. Nothing reported yet.

**Comment by Tschipp** [comment]
Yes. This is an issue with Dynamic surroundings, because we updated our codebase. Disable the animania module in the dynamic surroundings config.

**Comment by Rbear20005** [comment]
I have the same issue, could you explain how to resolve it?

**Comment by Rbear20005** [comment]
@Tschipp could I have some help

**Comment by dani163** [comment]
How do you play with Animania and Dynamic surroundings at the same time

**Comment by Tschipp** [comment]
#510
