### ISSUE TITLE
[Bug] Mod not loading in privately hosted server

### ISSUE THREAD

**Issue by FireBreathingBirdie** [capnkirok/animaniamod#456]
So I've been trying to host a modded server with my significant other, but whenever I create a new local server Animania doesn't seem to load. What do I mean by this? The world spawns with vanilla animals, and no new creatures (such as frogs or hamsters.) I made sure to download the base mod with all the addons, and have the correct version of forge. When I create a new single player world, Animania loads perfectly, immediately spawning the modded version of animals. If I create a brand new server that I wish to share with my partner, the vanilla animals spawn instead. I'm not sure what is going wrong. Does it have to do with the multiplayer aspect? My partner has all of the same mods that I do.

**Comment by Tschipp** [comment]
This depends greatly on the world. Animals are much less likely to spawn in already generated chunks. Try finding new chunks. Also, animania doesn't replace any vanilla animals anymore.

**Comment by FireBreathingBirdie** [comment]
The thing is: if I create two completely new worlds, one singleplayer and the other multiplayer, the singleplayer one immediately spawns Animania animals while the multiplayer enabled one acts like I don't have Animania installed at all. It's almost like I'm missing a step in the installation, but I don't know what.

**Comment by Tschipp** [comment]
I‘m assuming you have installed all the mods on the server tol? Have you tried spawning animals with the spawn eggs on the server?

**Comment by FireBreathingBirdie** [comment]
Yeah, I made sure to install all the mods into my server. While the spawn eggs are available in creative mode, it won't actually let me drop them into the world (In multiplayer).

**Comment by Tschipp** [comment]
Yes ok then you've not actually installed the mods on the server. A vanilla server will still (mostly) allow modded clients, stuff just won't work. Does the /forge command work for you? If not, the server is not running with forge.

**Comment by FireBreathingBirdie** [comment]
Yeah, when I did the /forge command, nothing happens. It looks like that's my issue right there. I thought I'd followed all the steps to make my local server a modded one: install and run forge, then go in through forge, but it seems that I did something wrong.

**Comment by FireBreathingBirdie** [comment]
Okay, I figured out how to run the forge server (the /forge command works now), but it still doesn't seem to read Animania. It won't let me place animania spawn eggs either

**Comment by Tschipp** [comment]
Please show me your latest logs, your file hierarchy, some in game screenshots of the /forge

**Comment by FireBreathingBirdie** [comment]
Here you go:
https://filebin.net/u8dhdnn96me3suyl

**Comment by Tschipp** [comment]
This all looks fine... can you record a video of all of this happening?

**Comment by FireBreathingBirdie** [comment]
Sure!
https://filebin.net/07k18fokp84jxzn2

**Comment by Tschipp** [comment]
hmm... can you actually try using an animania item? It's weird that that cow spawned though... Also, I see you joined 0, which I suppose is the same as the test server that you had in your list? Or are those two different?

**Comment by Tschipp** [comment]
Also, what machine are you on? What machine is your server on?

**Comment by FireBreathingBirdie** [comment]
0 and the test server are one and the same. I just use 0 to get in because it's a local server, and it's being hosted on my laptop (A Dell Inspiron 15 7000 series). If someone was to join that server, they would do so by using my IP address. 

I did actually try to use the animania spawn egg. I was pressing it, but it wouldn't allow me to grab it, or drag it anywhere. Same with the instructions book that it showed me how to craft. I was trying to create it, but same as the egg, it wouldn't actually let me.

**Comment by Tschipp** [comment]
In the video you showed you weren't in cheat mode for JEI, so clicking would only show the recipe, not give the item. Have you tried taking it from the creative tab?

**Comment by FireBreathingBirdie** [comment]
So, after trial and error, I finally figured it out. I did everything you asked me to do in a fresh install of minecraft, and then I deleted my world file completely. And when I logged back in, it worked. Thanks so much for your help.
