### ISSUE TITLE
[Crash] Crash on world load

### ISSUE THREAD

**Issue by thotbegone** [capnkirok/animaniamod#457]
Had this crash multiple times on a privately hosted server and a singleplayer world.
Tried with and without Biomes O' Plenty, crashed both.
Tried this with only Animania Base/Farm just to check. Crashed.

### Expected Behavior
World loads normally.

### Actual Behavior
World crashes on load.

### Steps to Reproduce
Start world with Animania Base and Farm.

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft: 1.12.2
Animania base: 2.0.0.23
Animania farm: 1.0.0.23
Singleplayer, but have had same error on private server.

### Crash log, latest.log
Crash: https://pastebin.com/raw/DmLCg44e
Log: https://pastebin.com/raw/jhUdUBFh

**Comment by Jigbashmop** [comment]
I had the same issue, fixed it by downloading the Extra Animals module.

**Comment by Tschipp** [comment]
Thank you, I will try to fix this soon.
