### ISSUE TITLE
Help Me

### ISSUE THREAD

**Issue by AvaThePotato** [capnkirok/animaniamod#46]
### Expected Behavior
My Minecraft is supposed to open to the main screen with single player and all that stuff.

### Actual Behavior
My Minecraft launches but then it says that i need forge 13.20.1.2386 or above. I have Craft API installed for 1.11.2 too.

### Steps to Reproduce
??

### Version of Minecraft, version of Animania, Single Player or Server
1.11.2 , 1.11.2 , single player

**Comment by Deshiba** [comment]
The message that you need a higher forge version is pretty clear I would reckon. 
Please update your forge version http://www.minecraftforge.net/forum/topic/12628-updating-forge-modded-minecraft-easiest-way/

**Comment by capnkirok** [comment]
Thanks @Deshiba ... closing this one
