### ISSUE TITLE
[Bug?]Did "squid spawning only ocean" system removed?

### ISSUE THREAD

**Issue by B-Wither** [capnkirok/animaniamod#465]
### Expected Behavior
Before 2.0.0, there was a function to make squids spawn only in ocean.

### Actual Behavior
Squids spawns anywhere.
I thought I could use this feature without adding mobs, but did Animani Base lose this feature?

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12.2
Animania 2.0.0.23

**Comment by Tschipp** [comment]
The config is now part of the farm addon. I think this is a bit of a bad choice however, so I will move it back to the base module.

**Comment by B-Wither** [comment]
Thank you!
