### ISSUE TITLE
Crashing after load

### ISSUE THREAD

**Issue by EmbershadeSC** [capnkirok/animaniamod#467]
The game keeps crashing a few seconds after world load and the crash report says Animania's doing it
[crash-2020-11-06_21.36.20-client.txt](https://github.com/capnkirok/animaniamod/files/5504305/crash-2020-11-06_21.36.20-client.txt)

**Comment by GreenTample** [comment]
I'm having the same problem. When would be the next release with bugfix?

**Comment by dredgemage** [comment]
This issue appears to be related to Dynamic Surroundings. Version 3.6.2.0 of DS lists support for Animania 2.0 being added so it's very likely updating to that version should resolve this issue.
