### ISSUE TITLE
Crafttweaker oddity

### ISSUE THREAD

**Issue by Ash70** [capnkirok/animaniamod#47]
MC: 1.12.3
Forge: 2673
Crafttweaker: 4.1.8
Animania: 1.4.8

This works:
`recipes.addShapeless(<minecraft:wool:0>, [<animania:wool:1>, <ore:dyeWhite>]);`
But this does not:
`recipes.addShapeless(<minecraft:wool:0>, [<animania:wool:*>, <ore:dyeWhite>]);`
Not sure if this is on your end or Crafttweakers' (using the wildcard on other ingredients does work, so I am suspecting the wool)

**Comment by capnkirok** [comment]
Ok, this is fixed in the next version. It had to do with the way subblocks were registered. Also prevented Minecraft default search from working.
