### ISSUE TITLE
Loading entity [Crash]

### ISSUE THREAD

**Issue by NeonZlime** [capnkirok/animaniamod#471]
### Expected Behavior
The game not crashing

### Actual Behavior
The game crashed after a bunch of minecraft dirt texture appeared on the screen for a few seconds, I was just playing normally and then when I restarted the game it crashed the same way again

### Steps to Reproduce
Start the game
Walk around
Game crashes after trying to load a sheep entity

### Version of Minecraft, version of Animania, Single Player or Server
Forge 1.12.2
animania-1.12.2-base-2.0.0.23
Single player

### Crash log, latest.log
[crash-2020-11-24_16.40.54-client.txt](https://github.com/capnkirok/animaniamod/files/5592961/crash-2020-11-24_16.40.54-client.txt)

**Comment by Disxconected** [comment]
had the same problem something about EntityEweBase it's all right here
[crash-2020-11-25_00.02.08-client.txt](https://github.com/capnkirok/animaniamod/files/5594539/crash-2020-11-25_00.02.08-client.txt)

**Comment by NeonZlime** [comment]
I fixed the issue by setting my rendering chunks to 2, then logged in where the entity wasnt in the loaded chunks, opened to lan with cheats, used the kill command within 100 blocks for the specific type of entity (orpington hen for me) and then set back my chunks to 12 like i usually use, worked fine after that but i wouldnt be surprised if it happened again
