### ISSUE TITLE
[Bug] Hamster Weirdness

### ISSUE THREAD

**Issue by mxnmnm** [capnkirok/animaniamod#475]
### Expected Behavior
Hamster to not look like it is permenantly getting attacked by shulkers

### Actual Behavior
Hamster floats like it has magical powers and the ability to rule the world

### Steps to Reproduce
Not sure (maybe just have it be a baby?)

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2
1.0.0.23

### Screenshots encouraged
![2020-12-06_16 51 15](https://user-images.githubusercontent.com/8508976/101298612-b93fc480-37e3-11eb-91dc-87b105b22211.png)
![2020-12-06_16 51 17](https://user-images.githubusercontent.com/8508976/101298613-ba70f180-37e3-11eb-9cff-493cec7c2f91.png)

**Comment by Tschipp** [comment]
It's oddly small... do you have any other mods?

**Comment by mxnmnm** [comment]
Yes, If I remember correctly there is a mod that has slight size variations for mobs, but I can't remember which one it is.

**Comment by Tschipp** [comment]
Then it's definitely that one

**Comment by Tschipp** [comment]
Gonna close this as this is not up to us
