### ISSUE TITLE
[Crash] Crash on World Creation and Spawn in.

### ISSUE THREAD

**Issue by FernoXL** [capnkirok/animaniamod#476]
### Expected Behavior
Normal Modded Gameplay. 

### Actual Behavior
Crash on World Creation and Spawn in.

### Steps to Reproduce
Load in both Animania base and Animania Farm.
There is also a chance that my modpack may be causing conflicts.
Was told to Report.

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft Forge 1.12.2 14.23.5.2854
animania-1.12.2-base-2.0.1.25
animania-1.12.2-farm-1.0.1
Single Player

### Crash log, latest.log
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  OTGCorePlugin (OTG-Core.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
  RandomPatches (randompatches-1.12.2-1.22.1.7.jar)
  TransformLoader (DynamicSurroundings-1.12.2-3.6.2.1.jar)
  PhosphorFMLLoadingPlugin (phosphor-forge-mc1.12.2-0.2.7-universal.jar)
  AppleCore (AppleCore-mc1.12.2-3.4.0.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 12/20/20 10:12 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at net.minecraft.world.WorldEntitySpawner.func_77191_a(WorldEntitySpawner.java:428)
	at net.minecraft.world.gen.ChunkGeneratorOverworld.func_185931_b(ChunkGeneratorOverworld.java:466)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:999)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:344)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:210)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:233)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 641550040 bytes (611 MB) / 1073741824 bytes (1024 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_F5 54 mods loaded, 54 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version         | Source                                             | Signature                                |
	|:------ |:-------------------- |:--------------- |:-------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft            | 1.12.2          | minecraft.jar                                      | None                                     |
	| LCHIJA | mcp                  | 9.42            | minecraft.jar                                      | None                                     |
	| LCHIJA | FML                  | 8.0.99.99       | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                | 14.23.5.2854    | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | otgcore              | 1.12.2 - v9.0   | minecraft.jar                                      | None                                     |
	| LCHIJA | foamfixcore          | 7.7.4           | minecraft.jar                                      | None                                     |
	| LCHIJA | randompatches        | 1.12.2-1.22.1.7 | randompatches-1.12.2-1.22.1.7.jar                  | None                                     |
	| LCHIJA | akashictome          | 1.2-12          | AkashicTome-1.2-12.jar                             | None                                     |
	| LCHIJA | craftstudioapi       | 1.0.0           | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar | None                                     |
	| LCHIJA | openterraingenerator | v9.0            | OpenTerrainGenerator-1.12.2-v9.0.jar               | None                                     |
	| LCHIJA | harvestcraft         | 1.12.2zb        | Pam's+HarvestCraft+1.12.2zg.jar                    | None                                     |
	| LCHIJA | animania             | 2.0.1.25        | animania-1.12.2-base-2.0.1.25.jar                  | None                                     |
	| LCHIJA | applecore            | 3.4.0           | AppleCore-mc1.12.2-3.4.0.jar                       | None                                     |
	| LCHIJA | appleskin            | 1.0.14          | AppleSkin-mc1.12-1.0.14.jar                        | None                                     |
	| LCHIJA | autoreglib           | 1.3-32          | AutoRegLib-1.3-32.jar                              | None                                     |
	| LCHIJA | betterburning        | 0.9.2           | BetterBurning-1.12.2-0.9.2.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | bettercaves          | 1.12.2          | bettercaves-1.12.2-2.0.4.jar                       | None                                     |
	| LCHIJA | bettermineshafts     | 1.12.2-2.1.1    | BetterMineshaftsForge-1.12.2-2.1.1.jar             | None                                     |
	| LCHIJA | carryon              | 1.12.3          | carryon-1.12.2-1.12.3.15.jar                       | fd21553434f4905f2f73ea7838147ac4ea07bd88 |
	| LCHIJA | clumps               | 3.1.2           | Clumps-3.1.2.jar                                   | None                                     |
	| LCHIJA | crafttweaker         | 4.1.20          | CraftTweaker2-1.12-4.1.20.602.jar                  | None                                     |
	| LCHIJA | ctgui                | 1.0.0           | CraftTweaker2-1.12-4.1.20.602.jar                  | None                                     |
	| LCHIJA | crafttweakerjei      | 2.0.3           | CraftTweaker2-1.12-4.1.20.602.jar                  | None                                     |
	| LCHIJA | dimdoors             | 3.0.9+287       | DimensionalDoors-3.0.9-287.jar                     | None                                     |
	| LCHIJA | sereneseasons        | 1.2.18          | SereneSeasons-1.12.2-1.2.18-universal.jar          | None                                     |
	| LCHIJA | orelib               | 3.6.0.1         | OreLib-1.12.2-3.6.0.1.jar                          | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | dsurround            | 3.6.2.1         | DynamicSurroundings-1.12.2-3.6.2.1.jar             | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | dynamictrees         | 1.12.2-0.9.21   | DynamicTrees-1.12.2-0.9.21.jar                     | None                                     |
	| LCHIJA | dynamictreesphc      | 1.12.2-2.0.5    | DynamicTreesPHC-1.12.2-2.0.5.jar                   | None                                     |
	| LCHIJA | elenaidodge          | 1.12.0          | ElenaiDodge-1.12.2-1.12.0.jar                      | None                                     |
	| LCHIJA | fastfurnace          | 1.3.1           | FastFurnace-1.12.2-1.3.1.jar                       | None                                     |
	| LCHIJA | fastbench            | 1.7.3           | FastWorkbench-1.12.2-1.7.3.jar                     | None                                     |
	| LCHIJA | firstaid             | 1.6.13          | firstaid-1.6.14.jar                                | 7904c4e13947c8a616c5f39b26bdeba796500722 |
	| LCHIJA | foamfix              | 0.10.10-1.12.2  | foamfix-0.10.10-1.12.2.jar                         | None                                     |
	| LCHIJA | forgelin             | 1.8.4           | Forgelin-1.8.4.jar                                 | None                                     |
	| LCHIJA | gottschcore          | 1.13.1          | GottschCore-mc1.12.2-f14.23.5.2768-v1.13.1.jar     | None                                     |
	| LCHIJA | improvedbackpacks    | 1.12.2-1.5.0.0  | ImprovedBackpacks-1.12.2-1.5.0.0.jar               | None                                     |
	| LCHIJA | shadowmc             | 3.8.0           | ShadowMC-1.12-3.8.0.jar                            | None                                     |
	| LCHIJA | leveluphp            | 1.12.2-1.4.0    | leveluphp-1.12.2-1.4.0.jar                         | None                                     |
	| LCHIJA | locks                | 2.5.1           | locks-1.12.2-2.5.1.jar                             | None                                     |
	| LCHIJA | lostbooks            | 2.0.3           | LostBooks-II-1.12.2-2.0.3.jar                      | None                                     |
	| LCHIJA | patchouli            | 1.0-22          | Patchouli-1.0-22.jar                               | None                                     |
	| LCHIJA | placebo              | 1.6.0           | Placebo-1.12.2-1.6.0.jar                           | None                                     |
	| LCHIJA | savemystronghold     | 1.12.2-1.0.0    | savemystronghold-1.12.2-1.0.0.jar                  | None                                     |
	| LCHIJA | signpost             | 1.08.5          | signpost-1.12.2-1.08.5.jar                         | None                                     |
	| LCHIJA | spiceoflife          | 1.3.12          | SpiceOfLife-mc1.12-1.3.12.jar                      | None                                     |
	| LCHIJA | spiderstpo           | 1.0.3           | spiders-2.0-1.12.2-1.0.3.jar                       | None                                     |
	| LCHIJA | toughasnails         | 3.1.0.141       | ToughAsNails-1.12.2-3.1.0.141-universal.jar        | None                                     |
	| LCHIJA | treasure2            | 1.13.1          | Treasure2-mc1.12.2-f14.23.5.2768-v1.13.1.jar       | None                                     |
	| LCHIJA | universalbestiary    | 1.3.1           | universalbestiary-1.12.2-1.3.1.jar                 | None                                     |
	| LCHIJA | yungslaw             | 1.12.2          | YungsLaw-1.12.2-1.0.4.jar                          | None                                     |
	| LCHIJA | phosphor-lighting    | 1.12.2-0.2.7    | phosphor-forge-mc1.12.2-0.2.7-universal.jar        | None                                     |
	| LCHIJA | solcarrot            | 1.8.4           | solcarrot-1.12.2-1.8.4.jar                         | None                                     |
	| LCHIJA | totemexpansion       | 1.2.2           | totemexpansion-1.2.2-1.12.2.jar                    | None                                     |

	Loaded coremods (and transformers): 
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
OTGCorePlugin (OTG-Core.jar)
  com.pg85.otg.forge.asm.excluded.OTGClassTransformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
RandomPatches (randompatches-1.12.2-1.22.1.7.jar)
  com.therandomlabs.randompatches.core.RPTransformer
TransformLoader (DynamicSurroundings-1.12.2-3.6.2.1.jar)
  
PhosphorFMLLoadingPlugin (phosphor-forge-mc1.12.2-0.2.7-universal.jar)
  
AppleCore (AppleCore-mc1.12.2-3.4.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Patchouli open book context: n/a
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 460.89
	OpenGlRenderer: GeForce GTX 1070/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by FernoXL** [comment]
Here is a Crash Report With no Other Mods as Clutter.
I'm not good at reading Reports, but it seems like Animania Farm isn't on the list?

### Crash log, latest.log
---- Minecraft Crash Report ----
// Don't do that.

Time: 12/21/20 9:04 AM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at com.animania.common.handler.AddonInjectionHandler.runInjection(AddonInjectionHandler.java:25)
	at com.animania.addons.farm.common.entity.chickens.EntityRoosterBase.<init>(EntityRoosterBase.java:53)
	at com.animania.addons.farm.common.entity.chickens.ChickenRhodeIslandRed$EntityRoosterRhodeIslandRed.<init>(ChickenRhodeIslandRed.java:39)
	at com.animania.addons.farm.common.event.FarmAddonSpawnHandler.removeSpawns(FarmAddonSpawnHandler.java:283)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_33_FarmAddonSpawnHandler_removeSpawns_CheckSpawn.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.canEntitySpawn(ForgeEventFactory.java:224)
	at net.minecraft.world.WorldEntitySpawner.func_77191_a(WorldEntitySpawner.java:296)
	at net.minecraft.world.gen.ChunkGeneratorOverworld.func_185931_b(ChunkGeneratorOverworld.java:466)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:999)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:344)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:142)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:156)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 344645728 bytes (328 MB) / 603979776 bytes (576 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID             | Version      | Source                                             | Signature                                |
	|:------ |:-------------- |:------------ |:-------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft      | 1.12.2       | minecraft.jar                                      | None                                     |
	| LCHIJA | mcp            | 9.42         | minecraft.jar                                      | None                                     |
	| LCHIJA | FML            | 8.0.99.99    | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge          | 14.23.5.2854 | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | craftstudioapi | 1.0.0        | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar | None                                     |
	| LCHIJA | animania       | 2.0.1.25     | animania-1.12.2-base-2.0.1.25.jar                  | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by SaveTheJohnDoe** [comment]
Same issue, tried with this config by disabling a few things (beehives, goats, removing the 'MAGICAL' tag from the mooshroom biome - I managed to get the world gen once but crashed upon moving around the world a minute later- I suspect the animania animal models, at least one of them, may give a rendering issue?)

a_farm config: [https://pastebin.com/2FW2f5Hd](https://pastebin.com/2FW2f5Hd)
crash log: [https://pastebin.com/BRBqFCNY](https://pastebin.com/BRBqFCNY)

**Comment by Farlandercd** [comment]
Same here. Crash to desktop when generating new worlds, or when loading old worlds. Base version works but farm expansion proves fatal.

**Comment by Tschipp** [comment]
Fixed. Should be approved by curse soon. You only need to update Animania Base.
