### ISSUE TITLE
[Solved] Polar bear spawn rate is low by default. allowed mob spawn section.

### ISSUE THREAD

**Issue by alxcool** [capnkirok/animaniamod#48]
### Expected Behavior
Find or encounter all the modded mobs from a custom list of mods in single player.

### Actual Behavior
Chicken spawning and sheep spawning sometime is prevented by something that I don't know yet. PrimalCore is missing some mobs, the bears and alligators... As tested, brown and black bear could be loaded in the same world than one with Animania, but animania seems to prevent bear spawning on map or chunk creation. Then, I end up with a world without bear. Sometime I also have to travel many km in order to find a single sheep or chicken.

### Steps to Reproduce

With only primal core loaded, create a new world in single player. Fly in creative mode and find some primal bears, then save the game. Including animania this time, re-launch minecraft. Try to find any additional primal bears in some new generated chunks...
Note : I have read Primal core and Animania config file this morning to make sure this behavior or issue was not one of my mistakes. I may regenerate my config files later on to make sure it is fine and if there is any change, I'l let you know.

### Version of Minecraft, version of Animania, Single Player or Server
PrimalCore-1.12.2-0.6.47
animania-1.12.2-1.4.8
CraftStudio-1.0.0.93-mc1.12-alpha
Old minecraft launcher on singleplayer and forge 2668

### Screenshots encouraged
Well I don't see what should I take as screenshot. Feel free to ask, I'l be pleased to run some tests.

Note : English is not my first language, I'l be pleased to edit a few sentence when required.

**Comment by alxcool** [comment]
I'v made a few more test and its impossible for me to advance this theory.  Either primal bear spawn is too rare, only 1 out of 2 biome found as match (Ice mountain). Either I should create an Issue on their page. I hope I did not mistaken your mod if it is not the one causing this issue, sorry for that.

**Comment by alxcool** [comment]
Solved. I'm not sure how,but I've used to set all the ReplaceVanilla"__" as "false", in the game rule section. I've also updated Primalcore to V.48. If I could help by testing some trigger in soloplayer, to make sure this issue is closed, feel free to ask!

**Comment by capnkirok** [comment]
Very strange. Animania doesn't touch bears. You can see that in the code:
https://github.com/capnkirok/animaniamod/blob/1.12/src/main/java/com/animania/common/events/EventReplaceSpawnAnimals.java

**Comment by alxcool** [comment]
Hi! Thk for the reply, this was not an easy theory to test but I will try to reproduce this issue. Do you have some tricks to find entity by type like as example if I create a new world  without any loaded mods then try to find a bear? Then reload the same world while using animania, then try to find a second one, or even create a new world to test it?
I may use nature compas for its biome locator / teleport option but... It's kinda uneasy

**Comment by alxcool** [comment]
So I've changed the title as I've completed a few more tests this afternoon.
While loading a few mods I like with animania, I've created a large biome new world and have found a polar bear after 8min.
Just remember I've changed the config file, so.
I've set animania config file, every section to default value. Then I've created a new world and have found a polar bear after 8min (default world generation).
I've tested some more maybe I was just lucky.
So I've closed the game and restart with the same mods, default config, I've found a polar bear after 30min.
After that I'e even tried to find a bear without using forge, just minecraft 1.12.2, then I'v got bored and left after 6 min in a few cold biome (I had to find some too.)
So not only bear spawn rate is not influenced by animania, if an another mod want to spawn additional bear using the same mechanic, he have to plan with this extremely low spawn rate.

Sorry if It took me lots of time and forbearance to complete these test. I'm just annoyed on how hard it is to find a single entity in a new world.
The only question I'm left with is, how a mod chose which entity's family to spawn in a given chunk on chunk creation and does spawn rate is lower the more variety of mobs there is?
Does the rate of appearance for a given entity decrease depending on the amount of different species who are allowed, or meet spawn condition?

**Comment by capnkirok** [comment]
Wow, your dedication is impressive. To answer your question, YES, Minecraft has mob caps. This is probably the issue (look up https://minecraft.gamepedia.com/Spawn). Some of my mobs extend the vanilla versions. which means they would count towards the 'passive' cap that MC uses when it tries to spawn its mobs.

So, one thing you could try reduce the likelihood and the cap of Animania mobs. This would provide more opportunities for vanilla mobs to spawn. And may explain your very first discovery.

Thanks for this research, it has be thinking over a few things.
