### ISSUE TITLE
[Crash] With Animal spawn with spawn chance set to 0

### ISSUE THREAD

**Issue by TheQKnight** [capnkirok/animaniamod#483]
### Expected Behavior
Animals should not spawn naturally if config files for extra or farm have their animals spawn chances set to 0. In 2.0.1.26, the game will crash while playing if these fields are set to 0.

### Actual Behavior
The game crashes when attempting to spawn an animal with 0 weight

### Steps to Reproduce
Copy configs and install Animania base, extra and farm.

### Version of Minecraft, version of Animania, Single Player or Server
MC 1.12.2
Animania Base 2.0.1.26
Animania Farm 1.0.1
Animania Extras 1.0.1

### Crash log, latest.log
Config Base: https://gist.github.com/TheQKnight/1846b9d3ab2c1beca1cb676f5a6eb02d
Config Extra: https://gist.github.com/TheQKnight/9599d2575959ec2a41226313d401285b
Config Farm: https://gist.github.com/TheQKnight/267cd480e92f52570d048ee878f2459f
Crash: https://gist.github.com/TheQKnight/3c99cfd612626321d9070da53808f375
Latest.log: https://gist.github.com/TheQKnight/1a265056a0f54d6ab4fb5c973e6af172

**Comment by Tschipp** [comment]
thanks, will fix
