### ISSUE TITLE
Mod compatibility issue/Mobs don't spawn on transparent blocks

### ISSUE THREAD

**Issue by SirChamomile** [capnkirok/animaniamod#49]
### Expected Behavior
Mobs spawn, and when they do it's at the intended rate.

### Actual Behavior
Mobs do not spawn while mods are loaded that add biomes during the ` preInit` phase, as Animania queries the biome dictionary before other mods can register biomes do the dictionary. There is a specific line in Animania that addresses this but it only calls out certain mods. Renaming the mod to Zanimania allows the mobs from Animania to spawn. 

There is another problem however, as your mobs don't spawn on transparent blocks. The mod I'm using introduces almost complete ground cover, and all of the plants and leaf blocks are transparent blocks. As a result, the only places passive mobs spawn is on beaches and on mountain tops.

### Steps to Reproduce
I'm using a developmental version of Conquest Reforged for 1.12.2. It currently is not public, but if you are interested, I will post on this issue when it is released to the public.

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12.2, 
Zanimania-1.12.2-1.4.8
Single Player

**Comment by capnkirok** [comment]
What terraingen mods are you using?

**Comment by Tschipp** [comment]
Will close this if I don't hear back in two weeks.

**Comment by capnkirok** [comment]
I remember looking into this and realizing this is part of Minecraft spawn code. It specifically excludes transparent blocks. I mean, we could override it, but there are reasons.

**Comment by Tschipp** [comment]
Yeah I was thinking exactly the same thing, but I'm not sure that's what OP means

**Comment by SirChamomile** [comment]
The mod in question is Conquest Reforged. The terrain gen is such that most blocks are covered in unique plants and grasses. I was able to use this mod somewhat successfully after the name change, but the transparent blocks occluding spawning space were still a bit problematic, requiring the player to clear out vegetation for animals to spawn. That being said, I haven't been playing recently and the experience may have improved. I can update you later.

Here's the link to the mod in question: https://minecraft.curseforge.com/projects/conquest-reforged/files

**Comment by Deshiba** [comment]
Mobs shouldn't have a problem spawning in grass, tall grass, saplings and the like. I reckon that if the shrubbery prevents spawns in conquest that it's a problem on the shrubs end?

**Comment by Tschipp** [comment]
Yes, @Deshiba you're right. iirc, most shrub plants didn't behave like normal plants would (they weren't broken instantly, they stayed floating in midair... etc.) So I also think they probably forgot to label the blocks as transparent.

**Comment by Tschipp** [comment]
Is this still an issue?

**Comment by SirChamomile** [comment]
![2018-11-16_14 56 31](https://user-images.githubusercontent.com/23204608/48647899-06f5f400-e9b3-11e8-93a3-2dd0166414fa.png)

Looks like it works just fine now, thanks everyone!
