### ISSUE TITLE
[Crash] Dynamic Surroundings badge render crash with latest versions of both mods

### ISSUE THREAD

**Issue by SandwichHorror** [capnkirok/animaniamod#499]
### Expected Behavior
No crashes

### Actual Behavior
Crash when rendering sheep

### Steps to Reproduce
Use Dynamic Surroundings and Animania 

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2, single player, animania base 2.0.3.2.8, animania-1.12.2-farm-1.0.2.28.jar | Dynamic Surroundings 1.12.2 3.6.1.0

### Crash log, latest.log
https://haste.antti.codes/xezuzudepu.mccrash

**Comment by JustJory** [comment]
My game crashes whenever I see hedgehogs and the water and ice just flickers I also have Dynamic Surroundings as well btw

**Comment by Tschipp** [comment]
Update dynamic surroundings.
