### ISSUE TITLE
[Feature Request] Dimension blacklist for Animania spawning

### ISSUE THREAD

**Issue by MauveCloud** [capnkirok/animaniamod#50]
### Expected Behavior
Animania animals should not spawn in other dimensions by default (especially when stabilized in the overworld so that returning to existing chunks isn't causing new animals to spawn), or at least there should be a way to stop them from doing so without stopping them from spawning in the overworld.

### Actual Behavior
I have a farm in the overworld with Animania cows and one with vanilla sheep (I turned off the options to force despawning of vanilla animals), yet after some work on building a grass field in the Nether, I came back to the portal and found that some Animania animals had spawned.  See screenshot below.

### Steps to Reproduce
1. Visit the Nether (being in peaceful mode helps)
2. Start building a large grass area (if not in creative mode, a few starter grass blocks can be used with torches to allow the grass to spread)
3. Return to the Nether portal.

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12.2
Animania 1.4.8
Single Player

### Screenshots encouraged
![2018-04-27_23 33 13](https://user-images.githubusercontent.com/8942955/39393061-535e9c8a-4a75-11e8-8e6f-ce2dc7896329.png)

**Comment by Deshiba** [comment]
Hmm, shouldn't this be impossible since the animals are white listed for each biome?

```
		if (AnimaniaConfig.spawn.spawnAnimaniaPigs)
		{
			EntityRegistry.addSpawn(EntitySowYorkshire.class, AnimaniaConfig.spawn.spawnProbabilityPigs, 1, maxFam, EnumCreatureType.CREATURE, getBiomes(BiomeDictionary.Type.PLAINS));
			EntityRegistry.addSpawn(EntitySowOldSpot.class, AnimaniaConfig.spawn.spawnProbabilityPigs, 1, maxFam, EnumCreatureType.CREATURE, getBiomes(BiomeDictionary.Type.FOREST));
			EntityRegistry.addSpawn(EntitySowLargeBlack.class, AnimaniaConfig.spawn.spawnProbabilityPigs, 1, maxFam, EnumCreatureType.CREATURE, Biomes.BIRCH_FOREST);
			EntityRegistry.addSpawn(EntitySowLargeBlack.class, AnimaniaConfig.spawn.spawnProbabilityPigs, 1, maxFam, EnumCreatureType.CREATURE, getBiomes(BiomeDictionary.Type.SWAMP));
			EntityRegistry.addSpawn(EntitySowLargeWhite.class, AnimaniaConfig.spawn.spawnProbabilityPigs, 1, maxFam, EnumCreatureType.CREATURE, getBiomes(BiomeDictionary.Type.FOREST));
			EntityRegistry.addSpawn(EntitySowDuroc.class, AnimaniaConfig.spawn.spawnProbabilityPigs, 1, maxFam, EnumCreatureType.CREATURE, getBiomes(BiomeDictionary.Type.JUNGLE));
			EntityRegistry.addSpawn(EntitySowHampshire.class, AnimaniaConfig.spawn.spawnProbabilityPigs, 1, maxFam, EnumCreatureType.CREATURE, getBiomes(BiomeDictionary.Type.MOUNTAIN));
			EntityRegistry.addSpawn(EntitySowHampshire.class, AnimaniaConfig.spawn.spawnProbabilityPigs, 1, maxFam, EnumCreatureType.CREATURE, Biomes.EXTREME_HILLS, Biomes.EXTREME_HILLS_WITH_TREES);
}
```
Since the biome "Hell" Isn't one of the biome listed in the spawn probabilities, animals spawning there should not happen. Are you perhaps using a mod that adds more biomes to the nether? Could you open the F3 screen to show what biome this is happening in?

**Comment by Deshiba** [comment]
Hmm, well I'll let the devs give their thoughts on this one. I don't think a dimensional blacklist is the way to go as there's mods like RFTools that generate random dimensions with (I believe) random Id's within the dimension registry. That would be impossible to blacklist from animania's end.

Hold for Purp or Tschipp though, as they actually do code and stuff.

**Comment by capnkirok** [comment]
Wow @MauveCloud you are right. It's those 'Dry' tagged biome spawn entires. I see a Nigerian Dwarf, Merino Sheep, and a Jack Rabbit. That's hilarious. This is a bug. I know how to to fix it too :)

**Comment by kevinmd88** [comment]
I would like to +1 this request. I use a mod called JustEnoughDimensions to create just basic worlds for my server's players to travel around and explore, independent of each other. They all have predefined IDs that I am able to specify, of course.

I also make use of this feature to copy in single-player worlds that my friends would like to add in to the mix, and there are some instances where I would just rather leave the vanilla functionality intact on that dimension as much as possible. Most mods do provide blacklisting/whitelisting options to this effect. Animania is a neat mod that I'd love to be able to work with. :)

**Comment by capnkirok** [comment]
Ok, this is fixed in the next release.
