### ISSUE TITLE
[Crash] loading entity 

### ISSUE THREAD

**Issue by Disxconected** [capnkirok/animaniamod#504]
### Expected Behavior
uninterrupted functionality

### Actual Behavior
crash(see log for elaboration)

### Steps to Reproduce
unknown attempts to spawn all ewe types via egg yields no crash 
and attempts to summon  produce the message: Unable to summon object 

possibly just related to any ewe being rendered after being un-rendered 

### Version of Minecraft, version of Animania, Single Player or Server
minecraft 1.12.2
animania-1.12.2-base-2.0.3.28.jar

### Crash log, latest.log
[crash-2021-03-06_15.53.59-client.txt](https://github.com/capnkirok/animaniamod/files/6096113/crash-2021-03-06_15.53.59-client.txt)

**Comment by Tschipp** [comment]
Update dynamic surroundings.
