### ISSUE TITLE
[Crash]

### ISSUE THREAD

**Issue by Rbear20005** [capnkirok/animaniamod#506]
I know @Tschipp  already solved this in https://github.com/capnkirok/animaniamod/issues/453, but I was wondering how enact the solution of disabling the animania dynamic surroundings module.

**Comment by Tschipp** [comment]
Update dynamic surroundings to the latest version

**Comment by Rbear20005** [comment]
I am using the latest version for 1.12, but it is still crashing

**Comment by Tschipp** [comment]
I'm willing to bet that you are not. Please double check on curseforge. You need to select the BETA version.

**Comment by Rbear20005** [comment]
okay, thank you, I was using the latest release version, I do have a minor concern that using the beta may cause more issues, so how stable is the beta version?

**Comment by Tschipp** [comment]
According to the author, it's a bit hacky. But I haven't seen issues arise from it. In any case, back up your worlds.

**Comment by Rbear20005** [comment]
okay,  thank you for being so helpful.

**Comment by Rbear20005** [comment]
@Tschipp After updating, It has crashed again after a while and I'm not sure why

**Comment by Rbear20005** [comment]
You said that there is a way to disable the Animania module in dynamic surroundings, how do I do that? I don't want patches I just want to disable the issue causing interaction.

**Comment by Tschipp** [comment]
I don't know the dynamic surroundings config. But there is an entry somewhere for disabling the animania compatibility. Just Ctrl + F for Animania and I'm sure you'll find something.
