### ISSUE TITLE
[Crash]

### ISSUE THREAD

**Issue by Guinea35** [capnkirok/animaniamod#507]
### Expected Behavior
Render 

### Actual Behavior
Bluescreens/blackscreens game and crashes instantly

### Steps to Reproduce
Look at a Sheep Ewe

### Version of Minecraft, version of Animania, Single Player or Server
1.12, 2.0.3.28, Singleplayer

### Crash log, latest.log
Error: java.lang.NoClassDefFoundError: com/animania/common/entities/sheep/EntityEweBase
[crash-2021-03-14_15.42.23-client.txt](https://github.com/capnkirok/animaniamod/files/6137474/crash-2021-03-14_15.42.23-client.txt)

**Comment by Tschipp** [comment]
Update dynamic surroundings to the latest BETA version.
