### ISSUE TITLE
Issues with Ewes [Crash]

### ISSUE THREAD

**Issue by Rbear20005** [capnkirok/animaniamod#509]
### Steps to Reproduce
Unknown, but milked a cow right before it happened, possible cause but contradictory

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12.2, Animania Base 2.0.3.28, Animania farm & extra 1.0.2.28

### Crash log, latest.log
https://drive.google.com/file/d/1BNnILKKbrZIeFnvu8sJG1LgQoh_TJMRf/view?usp=sharing

### Important note
This is not caused by Dynamic Surroundings as I already tried removing it and the game still crashed

**Comment by Tschipp** [comment]
Yes, it is. It is still dynamic surroundings. 
```
at org.orecruncher.dsurround.client.renderer.AnimaniaBadge.scale(AnimaniaBadge.java:109)
```
is a Dynamic surroundings class. 
It even says right here that you still have it, and still have the wrong version:
```
	| LCHIJA | dsurround            | 3.6.1.0               | DynamicSurroundings-1.12.2-3.6.1.0.jar             | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
```
