### ISSUE TITLE
Animals congregating in corners

### ISSUE THREAD

**Issue by polartwins** [capnkirok/animaniamod#51]
### Expected Behavior
Animals wandering around their pens, staying inside of pens.

### Actual Behavior
Animals keep pushing into corners; I've noticed this mostly in cows and pigs. They keep pushing into a corner and have actually managed to kill a few piglets but sticking them there and when they aged up, they suffocated in the wall.
They also keep escaping and I haven't actually witnessed an animal make its way out of their pen so I am only guessing that this might be how it is happening. There isn't any regular way for them to get out (blocks/fences are too high and there are no raised surfaces inside of the pens)

### Steps to Reproduce
1. Build a pen (mine are 7x11 so I wouldn't think that's too small)
2. Put animals inside (I've seen this happen with as little as five animals)
3. Go about your business and sometimes when you return they will be doing this.

### Version of Minecraft, version of Animania, Single Player or Server
MC: 1.12.2
Animania: 1.4.8
Single Player

### Screenshots encouraged
![2018-04-29_18 36 57](https://user-images.githubusercontent.com/27713689/39413253-797dd03a-4bdc-11e8-8494-555d84b0b092.png)
![2018-04-29_18 37 29](https://user-images.githubusercontent.com/27713689/39413256-83940832-4bdc-11e8-83f2-7cb9fb0bb575.png)
![2018-04-29_18 37 21](https://user-images.githubusercontent.com/27713689/39413259-8865c9c2-4bdc-11e8-9af3-89757b7fa6cd.png)

Note: my computer kind of sucks so the low FPS is regular, not caused by this particular event

**Comment by desagas** [comment]
I spent an hour looking for two angus cows, and when I found a bull and a calf, I was happy, thinking one would grow into a cow. But, sadly, when it grew one stage, it glitched into the wall, and suffocated. Sad times. Did you find a vanilla way to keep them contained with out dying like this? The pack I am playing on has conveyors, but that is an unsightly pain to building pens out of.

**Comment by capnkirok** [comment]
Thanks, both, looking into this one. I have seen it too, but it's not consistent (btw, the glitching into the wall will be fixed).

**Comment by capnkirok** [comment]
Yeah, this will be fixed in the next update. Has to do with animals being able to 'see' through walls and find an objective they cannot reach.
