### ISSUE TITLE
[Crash] Ewe rending issues.

### ISSUE THREAD

**Issue by AC3KILLER12345** [capnkirok/animaniamod#511]
### Expected Behavior
At the start, everything runs fine, no bugs, everything goes smoothly, I thought it would stay like this.

### Actual Behavior
I get mid game-is and then it just crashes, saying there's a rendering issue with the Ewe, after reloading, the world is corrupted and I can't access it again.

### Steps to Reproduce
There wasn't anything in particular, it just happens at random times.

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2, single player world.

### Crash log, latest.log
I can't remember the exact code, it just said from what I remember; "EweBaseEntity failed to render. Exit code: -1"

**Comment by Tschipp** [comment]
#510
