### ISSUE TITLE
animania mod doesn't work

### ISSUE THREAD

**Issue by AlfariziPai** [capnkirok/animaniamod#512]
i have some issues in animania 2.0.3.28 for minecraft 1.12.2
the animania mobs doesn't exist although i created a new world. the items and blocks are exist while the animania mobs doesn't, it's still the vanilla mobs.
how do i fix that?

**Comment by Tschipp** [comment]
Animania doesn't replace vanilla mobs that are already in your world. However if you explore new chunks, animania animals will generate. They also generate in old chunks, but less frequently.

**Comment by AlfariziPai** [comment]
> Animania doesn't replace vanilla mobs that are already in your world. However if you explore new chunks, animania animals will generate. They also generate in old chunks, but less frequently.

but why the random animal spawn egg doesn't work?

**Comment by Sweetiechu1** [comment]
exactly, the random spawn eggs dont work either.
