### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by VeryBigMack** [capnkirok/animaniamod#515]
Hello, I keep on having a problem when the game tries to render the ewe, the game freezes, my screen goes blue and then it closes.

Here are some details:
Single player
forge 1.12.2
Animania 2.0.3.38 
log: The game crashed whilst rendering entity in world
Error: java.lang.NoClassDefFoundError: com/animania/common/entities/sheep/EntityEweBase
Exit Code: -1

**Comment by Tschipp** [comment]
#510
