### ISSUE TITLE
[Crash] 

### ISSUE THREAD

**Issue by DreRer** [capnkirok/animaniamod#516]
### Expected Behavior
I actually don know it just said rendering problem

### Actual Behavior
The game crashed whilst rendering entity in world
Error: java.lang.NoClassDefFoundError: com/animania/common/entities/sheep/EntityEweBase
Exit Code: -1

### Steps to Reproduce
None

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2, 2.0.3.28, singleplayer

### Crash log, latest.log
The game crashed whilst rendering entity in world
Error: java.lang.NoClassDefFoundError: com/animania/common/entities/sheep/EntityEweBase
Exit Code: -1

**Comment by Tschipp** [comment]
#510
