### ISSUE TITLE
Error: java.lang.NoClassDefFoundError: com/animania/common/entities/sheep/EntityEweBase Exit Code: -1

### ISSUE THREAD

**Issue by Sam12543** [capnkirok/animaniamod#517]
### Expected Behavior
Game render animania sheep

### Actual Behavior
Game crash when rendering animalia sheep

### Steps to Reproduce
Spawn animalia sheep in mod version animania-1.12.2-base-2.0.3.28 with following mods
![mods 2021-04-03 7_41_51 PM](https://user-images.githubusercontent.com/78450132/113493322-aa78ce00-94b4-11eb-90f2-83413446a32d.png)
![mods 2021-04-03 7_41_44 PM](https://user-images.githubusercontent.com/78450132/113493326-b5cbf980-94b4-11eb-86cc-ea5d2831076c.png)
![mods 2021-04-03 7_41_22 PM](https://user-images.githubusercontent.com/78450132/113493332-ba90ad80-94b4-11eb-971e-ae4497d086bd.png)
![mods 2021-04-03 7_40_59 PM](https://user-images.githubusercontent.com/78450132/113493335-c3817f00-94b4-11eb-862a-c3cfc322304e.png)

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2, singleplayer

### Crash log, latest.log
[crash-2021-04-03_19.30.49-client.txt](https://github.com/capnkirok/animaniamod/files/6253649/crash-2021-04-03_19.30.49-client.txt)
[latest.log](https://github.com/capnkirok/animaniamod/files/6253650/latest.log)

**Comment by Tschipp** [comment]
#510
