### ISSUE TITLE
[Crash] Random crashes occuring with no action prompting them

### ISSUE THREAD

**Issue by TacocaTYT** [capnkirok/animaniamod#527]
### Expected Behavior
Nothing happens

### Actual Behavior
Game crashes with a pale blue screen (possibly that color from aether mod) and crashes to the launcher

### Steps to Reproduce
Not really sure, it didnt happen consistently but it happened a few times while cetting up a custom pack

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2
![image](https://user-images.githubusercontent.com/37640938/117888383-d717c680-b266-11eb-9a71-ef885c54bbb4.png)

### Crash log, latest.log
[crash-2021-05-09_14.56.23-client.txt](https://github.com/capnkirok/animaniamod/files/6462149/crash-2021-05-09_14.56.23-client.txt)

crash report in the launcher mentioned something about an ewe from animania

**Comment by TacocaTYT** [comment]
the crash error that shows in the launcher is 
The game crashed whilst rendering entity in world
Error: java.lang.NoClassDefFoundError: com/animania/common/entities/sheep/EntityEweBase
Exit Code: -1

and this error shows any time a world is loaded after this crash occurs wihtin that world. any remedy would be nice

**Comment by TacocaTYT** [comment]
after some more poking around it seems it may have somethign to do with dynamic surroundings somehow, ill test and experiment with the different stuff i installed incase it fixes something

**Comment by TacocaTYT** [comment]
ah ok it didnt crash after removing dynamic surroundings

**Comment by Tschipp** [comment]
#510
