### ISSUE TITLE
[Crash] specific sheep type crashes the game to the point of being unable to reopen worlds

### ISSUE THREAD

**Issue by KSKitten** [capnkirok/animaniamod#528]
### Expected Behavior
All animals should be able to load without issue

### Actual Behavior
Most animals load properly and I can explore the world without issues, but as soon as one specific sheep type spawns (usually after I have set up a base and have gotten pretty far into the game) the game tries to load in a new sheep, then it crashes. Afterward, every time I try to load the world, the game crashes with the same error message; java.lang.NoClassDefFoundError: com/animania/common/entities/sheep/EntityEweBase

### Steps to Reproduce
I have no clue which sheep is the cause of the crashes, but with all of the worlds I have had this crash happen in, it had happened after I had recently started setting up an animal pen with at least one sheep in it.

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12.2
animania-1.12.2-base-2.0.3.28.jar
animania-1.12.2-extra-1.0.2.28.jar
animania-1.12.2-farm-1.0.2.28.jar
singleplayer

### Crash log, latest.log
[crash-2021-06-08_18.42.15-client.txt](https://github.com/capnkirok/animaniamod/files/6620008/crash-2021-06-08_18.42.15-client.txt)

**Comment by DaisyMayTheVxn** [comment]
I have this same issue

**Comment by Tschipp** [comment]
#510
