### ISSUE TITLE
Can't Mount Draft Horse?

### ISSUE THREAD

**Issue by ThorneWyvern** [capnkirok/animaniamod#53]
Put a saddle on my—happy as far as I can tell—draft horse, right clicked and nothing. Tried holding the riding crop and empty handed: left click, right click, and shift-right click. Also tried it before putting a saddle on.

Got pretty frustrated trying to find information on how to mount, as the wiki just says "use riding crop" which doesn't tell me what button to press and contradicts the saddle update (1.4.7) which says only the saddle is required to mount.
Meanwhile the curse forge page says "Use a Riding Crop on a Fed and Watered Draft Horse to ride it. No saddle is required." as well as saying to right click with the crop.

So I don't know if it is a bug or if I just don't know how to do it properly as everything says to do something different, but I've tried all the different ways listed.

### Version of Minecraft, version of Animania, Single Player or Server

1.11.2 (1.4.8) and 1.11.2 (1.4.7) both in Single Player

**Comment by capnkirok** [comment]
Hmmm.... I am not having any issues on 1.11. You don't need riding crop anymore. Just a happy horse with a saddle. Right click to mount.

[![Screenshot from Gyazo](https://gyazo.com/b1e37dda1ea45c6873ed994d91c6cdbc/raw)](https://gyazo.com/b1e37dda1ea45c6873ed994d91c6cdbc)

**Comment by capnkirok** [comment]
Closing this one. Let me know if you still run into issues after seeing the video.
