### ISSUE TITLE
Animals refuse to jump into the horse cart...

### ISSUE THREAD

**Issue by flyingovertherainbow** [capnkirok/animaniamod#54]
In the overview it says that if you lead an animal to the back of a horse cart, it will jump in. I've tried, but they refuse. Instead, they walk under the horse cart, or beside. I'm playing the 1.12.2 version single player. Is there any way I can do this, or is there any chance that you'll fix it?

**Comment by capnkirok** [comment]
Investigating this one.

**Comment by flyingovertherainbow** [comment]
Thank you for your answer! Right now I don't have access to my computer,
cuz I'm on vacation, but I'll test again it when I come home.

**Comment by capnkirok** [comment]
Ok, I'm closing this one. Just let me know if you run into it again.
