### ISSUE TITLE
[Crash] Animania sheep is seemingly crashing my game

### ISSUE THREAD

**Issue by cutecorgie** [capnkirok/animaniamod#541]
### Expected Behavior
Being able to load into my world and play, I guess.

### Actual Behavior
Seemingly, it was trying to render an animania sheep into the world and crashed because of it. That's the most I can gather from the crash report, I'm not really savvy when it comes to troubleshooting mods and the like.

### Steps to Reproduce
I'm not sure honestly. I was leaving the house I built yesterday to make a pen for some chickens and it suddenly crashed. Every time I try to enter the world it crashes instantly.

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2
Base 2.0.3.28 - Farm 1.0.2.28 - Extra 1.0.2.28 - Cats and Dogs 1.0.0.28
Singleplayer

### Crash log, latest.log
Attached below. If you'd rather I post it in the comments, just let me know.
[crash-2021-08-31_21.01.55-client.txt](https://github.com/capnkirok/animaniamod/files/7088200/crash-2021-08-31_21.01.55-client.txt)

EDIT: I'd like to add on real quick that I'm aware of the Dynamic Surroundings issue. However, when I downloaded the beta version of DS, it wouldn't even let my game load to the title screen. It'd crash so fast that there wasn't even a crash report for it.

**Comment by Tschipp** [comment]
#510

**Comment by cutecorgie** [comment]
Hey so,,,, while I have no doubt this works, it still doesn't help me much. Like I said in my edit, updating dynamic surroundings instantly crashes my game the moment I hit play and doesn't produce a crash report for it. Do you have any idea why it'd be doing that or am I on my own here..?

**Comment by Tschipp** [comment]
You will probably need to install mixinbootstrap as well

**Comment by cutecorgie** [comment]
Oh! That fixed it, thank you so much!!

**Comment by Tschipp** [comment]
np
