### ISSUE TITLE
Some ewes ruining my day [Crash]

### ISSUE THREAD

**Issue by Scratchybird** [capnkirok/animaniamod#548]
So for the past few days I keep getting this crash
![image](https://user-images.githubusercontent.com/93502681/139616830-f34553b9-d858-4e39-971c-e1893c498df9.png)
It seems to usually happen if I stay in one place for too long (like if I build a home) and when I open the save again it of course crashes so basically I have just lost many a save game due to this, I just lost one that I was planning of spending a lot of time in and I am a bit upset about this whole ordeal. So if anyone knows what is causing this and a way to fix it that would be good! I have deleted the farm pack from the mods folder but the save file I wish to play is still crashing.
Here is the crash report as well, I hope to get this issue resolved because I have had with losing some good saves to this.
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  iceandfire (iceandfire-1.9.1-1.12.2 (1).jar)
  OTGCorePlugin (OTG-Core.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.14-1.12.2.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 10/31/21 8:09 PM
Description: Rendering entity in world

java.lang.NoClassDefFoundError: com/animania/common/entities/sheep/EntityEweBase
	at org.orecruncher.dsurround.client.renderer.AnimaniaBadge.scale(AnimaniaBadge.java:109)
	at org.orecruncher.dsurround.client.renderer.BadgeRenderLayer.func_177141_a(BadgeRenderLayer.java:127)
	at net.minecraft.client.renderer.entity.RenderLivingBase.func_177093_a(RenderLivingBase.java:439)
	at net.minecraft.client.renderer.entity.RenderLivingBase.func_76986_a(RenderLivingBase.java:186)
	at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(SourceFile:41)
	at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(SourceFile:16)
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:384)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:368)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:628)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1347)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.animania.common.entities.sheep.EntityEweBase
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 21 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.orecruncher.dsurround.client.renderer.AnimaniaBadge.scale(AnimaniaBadge.java:109)
	at org.orecruncher.dsurround.client.renderer.BadgeRenderLayer.func_177141_a(BadgeRenderLayer.java:127)
	at net.minecraft.client.renderer.entity.RenderLivingBase.func_177093_a(RenderLivingBase.java:439)
	at net.minecraft.client.renderer.entity.RenderLivingBase.func_76986_a(RenderLivingBase.java:186)
	at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(SourceFile:41)
	at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(SourceFile:16)

-- Entity being rendered --
Details:
	Entity Type: animania:female_wolf (com.animania.addons.catsdogs.common.entity.canids.DogWolf.EntityFemaleWolf)
	Entity ID: 1921
	Entity Name: Female Wolf
	Entity's Exact location: 960.50, 71.00, 102.50
	Entity's Block location: World: (960,71,102), Chunk: (at 0,4,6 in 60,6; contains blocks 960,0,96 to 975,255,111), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
	Entity's Momentum: 0.00, -0.06, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: com.animania.addons.catsdogs.client.render.dogs.RenderDogGeneric@3c4d10ff
	Location: -1.89,0.00,1.10 - World: (-2,0,1), Chunk: (at 14,0,1 in -1,0; contains blocks -16,0,0 to -1,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Rotation: -90.0
	Delta: 0.7999954
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:384)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:368)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:628)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1347)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Scratchybird'/1394, l='MpServer', x=962.39, y=71.00, z=101.40]]
	Chunk stats: MultiplayerChunkCache: 328, 328
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-22841750,81,-13939813), Chunk: (at 10,5,11 in -1427610,-871239; contains blocks -22841760,0,-13939824 to -22841745,255,-13939809), Region: (-44613,-27227; contains chunks -1427616,-871264 to -1427585,-871233, blocks -22841856,0,-13940224 to -22841345,255,-13939713)
	Level time: 936972 game time, 1060039 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: true)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 31 total; [EntityTameableDragon['Antti'/1920, l='MpServer', x=934.00, y=74.06, z=99.94], EntityFemaleWolf['Female Wolf'/1921, l='MpServer', x=960.50, y=71.00, z=102.50], EntityDragonSkull['Dragon Skull'/1922, l='MpServer', x=931.50, y=83.00, z=99.50], EntityFemaleWolf['Female Wolf'/1925, l='MpServer', x=960.50, y=71.00, z=102.50], EntitySkeleton['Skeleton'/1927, l='MpServer', x=986.50, y=40.00, z=32.50], EntityPlayerSP['Scratchybird'/1394, l='MpServer', x=962.39, y=71.00, z=101.40], EntitySpider['Spider'/1928, l='MpServer', x=989.50, y=40.00, z=33.50], EntityBat['Bat'/2249, l='MpServer', x=1011.56, y=41.70, z=55.53], EntityBat['Bat'/2250, l='MpServer', x=1011.32, y=41.14, z=51.74], EntityBeetle['Beetle'/2124, l='MpServer', x=972.18, y=67.00, z=159.28], EntityBat['Bat'/2256, l='MpServer', x=1028.65, y=41.90, z=23.26], EntityBat['Bat'/2262, l='MpServer', x=1015.61, y=43.10, z=35.97], EntityEnderCrystal['entity.EnderCrystal.name'/2135, l='MpServer', x=988.50, y=95.00, z=96.50], EntityBat['Bat'/2263, l='MpServer', x=1012.10, y=40.80, z=34.78], EntityEnderCrystal['entity.EnderCrystal.name'/2136, l='MpServer', x=984.50, y=111.00, z=98.50], EntityBat['Bat'/2267, l='MpServer', x=1012.96, y=40.45, z=30.91], EntityCreeper['Creeper'/2268, l='MpServer', x=993.50, y=40.00, z=32.50], EntityButterfly['Butterfly'/1888, l='MpServer', x=914.49, y=81.12, z=92.27], EntitySpider['Spider'/1896, l='MpServer', x=928.82, y=63.00, z=21.40], EntityTameableDragon['Dragon'/1898, l='MpServer', x=932.40, y=64.00, z=31.60], EntitySpider['Spider'/1899, l='MpServer', x=936.17, y=64.00, z=21.70], EntityZombie['Zombie'/1901, l='MpServer', x=934.27, y=64.00, z=24.46], EntityPigeon['Pigeon'/1902, l='MpServer', x=918.87, y=68.00, z=45.62], EntityZombie['Zombie'/1905, l='MpServer', x=927.50, y=63.00, z=21.50], EntityButterfly['Butterfly'/1906, l='MpServer', x=913.64, y=77.73, z=27.69], EntityButterfly['Butterfly'/1907, l='MpServer', x=903.72, y=70.09, z=44.69], EntityFurby['Furby'/2167, l='MpServer', x=1000.71, y=64.00, z=147.50], EntityArmorStand['Armor Stand'/1914, l='MpServer', x=978.50, y=65.00, z=66.50], EntityEnderCrystal['entity.EnderCrystal.name'/1917, l='MpServer', x=932.50, y=71.00, z=98.50], EntityTameableDragon['Achird'/1918, l='MpServer', x=938.62, y=73.06, z=102.18], EntityTameableDragon['Avalanche'/1919, l='MpServer', x=934.01, y=74.06, z=97.44]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 840880896 bytes (801 MB) / 2013265920 bytes (1920 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 64 mods loaded, 64 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version        | Source                                             | Signature                                |
	|:------ |:-------------------- |:-------------- |:-------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft            | 1.12.2         | minecraft.jar                                      | None                                     |
	| LCHIJA | mcp                  | 9.42           | minecraft.jar                                      | None                                     |
	| LCHIJA | FML                  | 8.0.99.99      | forge-1.12.2-14.23.5.2855.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                | 14.23.5.2855   | forge-1.12.2-14.23.5.2855.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | ivtoolkit            | 1.3.3-1.12     | minecraft.jar                                      | None                                     |
	| LCHIJA | otgcore              | 1.12.2 - v8.3  | minecraft.jar                                      | None                                     |
	| LCHIJA | foamfixcore          | 7.7.4          | minecraft.jar                                      | None                                     |
	| LCHIJA | movillages           | 1.5.4          | [1.12]MoVillages-1.5.4.jar                         | None                                     |
	| LCHIJA | aether_legacy        | 1.5.3.2        | aether-1.12.2-v1.5.3.2.jar                         | None                                     |
	| LCHIJA | aether_legacy_addon  | 1.12.2-v1.3.0  | Aether+Continuation+v1.3.0.jar                     | None                                     |
	| LCHIJA | biomesoplenty        | 7.0.1.2444     | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar      | None                                     |
	| LCHIJA | craftstudioapi       | 1.0.0          | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar | None                                     |
	| LCHIJA | openterraingenerator | v8.3           | OpenTerrainGenerator-1.12.2+-+v8.3.jar             | None                                     |
	| LCHIJA | harvestcraft         | 1.12.2zb       | Pam's+HarvestCraft+1.12.2zg.jar                    | None                                     |
	| LCHIJA | animania             | 2.0.3.28       | animania-1.12.2-base-2.0.3.28.jar                  | None                                     |
	| LCHIJA | aquaculture          | 1.6.8          | Aquaculture-1.12.2-1.6.8.jar                       | None                                     |
	| LCHIJA | baubles              | 1.5.2          | Baubles-1.12-1.5.2.jar                             | None                                     |
	| LCHIJA | biomebundle          | 5.1            | Biome_Bundle-1.12.2-v6.1.jar                       | None                                     |
	| LCHIJA | bbop                 | 1.0            | Biome_Bundle_O_Plenty-1.12.2_v1.0.jar              | None                                     |
	| LCHIJA | byg                  | 1.7.1          | BiomesYouGo1.7.1.jar                               | None                                     |
	| LCHIJA | birdwmod             | 1.12.2-1.0.0   | TheBirdwatchingMod-1.5.0.jar                       | None                                     |
	| LCHIJA | bookworm             | 1.12.2-2.3.0   | bookworm-1.12.2-2.3.0.jar                          | None                                     |
	| LCHIJA | chunkpregenerator    | 2.1            | Chunk+Pregenerator+V1.12-2.3.jar                   | None                                     |
	| LCHIJA | comforts             | 1.4.1.3        | comforts-1.12.2-1.4.1.3.jar                        | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LCHIJA | coralreef            | 2.0            | CoralReef-2.5-1.12.2.jar                           | None                                     |
	| LCHIJA | extendedrenderer     | v1.0           | coroutil-1.12.1-1.2.32.jar                         | None                                     |
	| LCHIJA | coroutil             | 1.12.1-1.2.32  | coroutil-1.12.1-1.2.32.jar                         | None                                     |
	| LCHIJA | configmod            | v1.0           | coroutil-1.12.1-1.2.32.jar                         | None                                     |
	| LCHIJA | llibrary             | 1.7.19         | llibrary-1.7.19-1.12.2.jar                         | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | dragonmounts         | 1.12.2-1.6.2   | DragonMounts2-1.12.2-1.6.2.jar                     | None                                     |
	| LCHIJA | sereneseasons        | 1.2.18         | SereneSeasons-1.12.2-1.2.18-universal.jar          | None                                     |
	| LCHIJA | orelib               | 3.6.0.1        | OreLib-1.12.2-3.6.0.1.jar                          | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | dsurround            | 3.6.1.0        | DynamicSurroundings-1.12.2-3.6.1.0.jar             | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | reccomplex           | 1.4.8.2        | RecurrentComplex-1.4.8.2.jar                       | None                                     |
	| LCHIJA | dynamictrees         | 1.12.2-0.9.23  | DynamicTrees-1.12.2-0.9.23.jar                     | None                                     |
	| LCHIJA | dynamictreesbop      | 1.12.2-1.5.1   | DynamicTreesBOP-1.12.2-1.5.1.jar                   | None                                     |
	| LCHIJA | exoticbirds          | 1.0            | Exotic+Birds+1.12.2-3.1.0.jar                      | None                                     |
	| LCHIJA | extrautils2          | 1.0            | extrautils2-1.12-1.9.9.jar                         | None                                     |
	| LCHIJA | familiarfauna        | 1.0.11         | FamiliarFauna-1.12.2-1.0.11.jar                    | None                                     |
	| LCHIJA | farfromhome          | 1.0            | Far_From_Home-1.12.2-5.0.jar                       | None                                     |
	| LCHIJA | foamfix              | 0.10.14-1.12.2 | foamfix-0.10.14-1.12.2.jar                         | None                                     |
	| LCHIJA | jei                  | 4.16.1.301     | jei_1.12.2-4.16.1.301.jar                          | None                                     |
	| LCHIJA | forestry             | 5.8.2.387      | forestry_1.12.2-5.8.2.387.jar                      | None                                     |
	| LCHIJA | fossil               | 8.0.4          | fossilsarcheology-8.0.4.jar                        | None                                     |
	| LCHIJA | scfc                 | 0.1.1          | Furbcraft-1.12.2-0.1.1.jar                         | None                                     |
	| LCHIJA | cfm                  | 6.3.1          | furniture-6.3.1-1.12.2.jar                         | None                                     |
	| LCHIJA | iceandfire           | 1.9.1          | iceandfire-1.9.1-1.12.2 (1).jar                    | None                                     |
	| LCHIJA | iseedragons          | 0.12           | ISeeDragons-0.12.jar                               | None                                     |
	| LCHIJA | lost_aether          | 1.0.2          | lost-aether-content-1.12.2-1.0.2.jar               | None                                     |
	| LCHIJA | modnametooltip       | 1.10.1         | modnametooltip_1.12.2-1.10.1.jar                   | None                                     |
	| LCHIJA | mysticalworld        | 1.12.2-1.9.8   | mysticalworld-1.12.2-1.9.8.jar                     | None                                     |
	| LCHIJA | patchouli            | 1.0-23.6       | Patchouli-1.0-23.6.jar                             | None                                     |
	| LCHIJA | randomrespawn        | Release 1.0    | RandomRespawn-1.0-MC1.12.2.jar                     | None                                     |
	| LCHIJA | additionalstructures | 2.3.1          | Rex's-Additional-Structures-1.12.x-(v.2.3.1).jar   | None                                     |
	| LCHIJA | roguelike            | 1.8.0          | RoguelikeDungeons-1.12.2-1.8.0.jar                 | None                                     |
	| LCHIJA | sit                  | v1.3           | sit-1.12.2-v1.3.jar                                | None                                     |
	| LCHIJA | thaumcraft           | 6.1.BETA26     | Thaumcraft-1.12.2-6.1.BETA26.jar                   | None                                     |
	| LCHIJA | villagenames         | 3.2.1          | VillageNames-1.12.2-3.2.1.jar                      | None                                     |
	| LCHIJA | waystones            | 4.1.0          | Waystones_1.12.2-4.1.0.jar                         | None                                     |
	| LCHIJA | wearablebackpacks    | 3.1.4          | WearableBackpacks-1.12.2-3.1.4.jar                 | None                                     |
	| LCHIJA | weather2             | 1.12.1-2.6.12  | weather2-1.12.1-2.6.12.jar                         | None                                     |
	| LCHIJA | betteranimals        | 5.5.0          | betteranimals-1.12.2-5.5.0.jar                     | None                                     |
	| LCHIJA | betteranimalsplus    | 9.0.1          | betteranimalsplus-1.12.2-9.0.1.jar                 | None                                     |
	| LCHIJA | mysticallib          | 1.12.2-1.10.0  | mysticallib-1.12.2-1.10.0.jar                      | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
iceandfire (iceandfire-1.9.1-1.12.2 (1).jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
OTGCorePlugin (OTG-Core.jar)
  com.pg85.otg.forge.asm.excluded.OTGClassTransformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.14-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 445.87' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
	Patchouli open book context: n/a
	Launched Version: 1.12.2-forge-14.23.5.2855
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 445.87, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Mizunos 16 Craft_1.12.2-1.0.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 2x Intel(R) Core(TM)2 Duo CPU E7400 @ 2.80GHz

**Comment by Alexander3847575** [comment]
I was confused by this at first too because the no class error looked like it was from animania, but then after actually reading the stacktrace it's just the dynamic surroundings crash mentioned in the pinned comment. Update your dynamic surroundings to the latest _**beta**_ version (3.6.3 at time of writing). I would advise the creators to add 'Ewe crash' to the pinned comment lol

**Comment by Tschipp** [comment]
Yes, exactly that, See #510
