### ISSUE TITLE
animals get suck in a "finding food loop" and starve

### ISSUE THREAD

**Issue by njtxus** [capnkirok/animaniamod#55]
### Actual Behavior
Periodically animals stay in place and starve to death. Moving with a lead and letting go the animal  walks back to the same spot it left and starves. I loaded up hungry animals for the mob scanner and it verified that they were stuck in a loop eating food.

### Steps to Reproduce
Seems to be random

### Version of Minecraft, version of Animania, Single Player or Server
version 1.4.8

**Comment by capnkirok** [comment]
I've refactored the Find/Eat Food (again). Should be fixed in next release.
