### ISSUE TITLE
Cheese mold does not accept vanilla milk

### ISSUE THREAD

**Issue by Deshiba** [capnkirok/animaniamod#56]
It would be fantastic if you could use regular milk in a cheese mold to make a cheese wheel.
Currently right clicking a vanilla milk bucket on a cheese mold does show the use animation but does nothing.

![2018-05-14_08 39 18](https://user-images.githubusercontent.com/10565800/39981876-c73ca266-5752-11e8-9d5c-621563c6d56e.png)

This would allow for better support when the config option replaceVanillaCows is set to false.

**Comment by Tschipp** [comment]
Won't be done, at least for now, see reason in #107

**Comment by capnkirok** [comment]
Hey @Tschipp maybe you can add an error message for people who try to use regular milk and provide some guidance?

**Comment by Tschipp** [comment]
ok will do
