### ISSUE TITLE
[Crash] - Due to a sheep not rendering properly..

### ISSUE THREAD

**Issue by Lachfish** [capnkirok/animaniamod#567]
### Expected Behavior
Game NOT crashing

### Actual Behavior
Game crashing

### Steps to Reproduce 
not exactly sure what this means.

 ### Version of Minecraft, version of Animania, Single Player or Server
 --Single Player 1.12.2 JAVA EDITION [modded of course] 

animania-1.12.2-farm-1.0.2.28.jar 
animania-1.12.2-base-2.0.3.28.jar 
animania-1.12.2-extra-1.0.2.28.jar

 ### Crash log, latest.log

 **THE ERROR;** The game crashed whilst rendering entity in world Error: java.lang.NoClassDefFoundError: com/animania/common/entities/sheep/EntityEweBase[Crash] 

**[the log is probaly the most lines you've seen, but its not the amount of mods that caused this. It runs completley fine, minus this error]**

**Too beyond limit of characters here. Unable to post it. Here's the link to the log on google docs.**
_COPY AND PASTE INTO GOOGLE SEARCH BAR (or any search engine)_
[https://docs.google.com/document/d/1hUy8GjBoqH-LaD-4Gwti8W_Q3Wrmmov38a5y__Hy1GM/edit?usp=sharing](url)

Thanks,
Lachlan

**Comment by Tschipp** [comment]
#510
