### ISSUE TITLE
Roast prime steak should be Cooked prime steak

### ISSUE THREAD

**Issue by Deshiba** [capnkirok/animaniamod#57]
### Expected Behavior
For roast prime steak to be called cooked prime steak like all the other cooked steaks.

### Actual Behavior
Roast prime steak differs from the cooked prime steak of the Angus, Hereford and Longhorn type.

### Version of Minecraft, version of Animania, Single Player or Server
MC 1.12.2
Animania 1.4.8

### Screenshots encouraged
![2018-05-14_10 01 18](https://user-images.githubusercontent.com/10565800/39985145-d788c66c-575d-11e8-8fce-5398137b710f.png)
![2018-05-14_10 01 22](https://user-images.githubusercontent.com/10565800/39985147-d9f48b20-575d-11e8-97b4-c1f7e448a39b.png)

**Comment by capnkirok** [comment]
Thanks, I like the easy ones :)
