### ISSUE TITLE
Angus Do Not Breed without Intervention

### ISSUE THREAD

**Issue by desagas** [capnkirok/animaniamod#59]
### Expected Behavior
Angus cows bread without intervention. As in, without being fed by hand or trough. I do not know if this is intended, but Highland cows breed with just being "Well fed" in green. Meaning, Angus cows in the wild should breed on their own, getting food from grass, and water from lakes. They do this, but do not breed.

### Actual Behavior
Angus cows need to be hand fed wheat or fed in a trough.

### Steps to Reproduce
As explained above.

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2-1.4.8, server.

### Screenshots encouraged
Screenshots will not add to the issue.

If this is intended, is there a link to what makes all animals happy?

**Comment by capnkirok** [comment]
FYI, all cows use the same breeding code.

But tested anyway. This is working as intended. Probably you are at your cow spawn limit in the area where your Angus cows are. When you are at your spawn limit, you need to hand feed. To test this, you can go into the config and raise your spawn limit and see if they breed again.
