### ISSUE TITLE
No way to get rabbit hide

### ISSUE THREAD

**Issue by BlueWither** [capnkirok/animaniamod#60]
I can't get rabbit hide to kill rabbits...
So I can't make important item of ThaumCraft.

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12.2
Animania 1.4.8
Single

**Comment by Deshiba** [comment]
This has been requested before in the other repo. Way to fix is to create custom loottables, so the fix might take a while.

https://github.com/capnkirok/animania/issues/533
https://github.com/capnkirok/animania/issues/568

**Comment by capnkirok** [comment]
I will add a third drop to rabbits. Seems like the easiest solution.

**Comment by capnkirok** [comment]
added in next release
