### ISSUE TITLE
[SUGGESTION] Size variances for individual animals

### ISSUE THREAD

**Issue by Sunconure11** [capnkirok/animaniamod#61]
In lycanites mobs, all of the mobs would have size variances, even among their own breed/species. Would it be possible to implement something similar, so that say, two chickens of the same breed aren't always the same size?

**Comment by Tschipp** [comment]
I like that Idea and I think it can be implemented quite easily

**Comment by capnkirok** [comment]
We'd have to create some new Data Params, but yeah, can be done.
