### ISSUE TITLE
Animania Cows,Sheeps, and goats not producing milk in 1.11, and 1.12.2

### ISSUE THREAD

**Issue by Meegz0** [capnkirok/animaniamod#62]
### Expected Behavior
After feeding and watering the milkable animal to make it happy/get it preggers, you recieve either the vanilla milk or the animania special milk.

### Actual Behavior
nothing happens, no matter how many times you feed and water the animal. Only seems to work in 1.10.
Only way I've been able to get any sort of milk is with cooking with blockheads cow in a jar and botanias drum of the gathering. If only Animania is installed, there's no way for me to get milk. Restarting, changing configs/deleting configs and reloading game does nothing to fix. Waila also shows no "ready to milk" ever.

### Steps to Reproduce
Unsure, was working as far as I could tell 3 days ago. I changed the configs ambience mode regularly to see which way I liked better. Then its just stopped working 2 days ago.

Tried a new forge profile with only Animania and craftstudio installed, even tried older versions with no success on 1.11.2 and 1.12.2. Milking normally only happened in 1.10.2

### Version of Minecraft, version of Animania, Single Player or Server
single player, 1.12.2 and 1.11.2, 1.4.8, 1.4.7, 1.4.6

### Screenshots encouraged
Would have to post a video I think, I have no capture software sorry.

**Comment by capnkirok** [comment]
Let me know if it happens again.
