### ISSUE TITLE
[SUGGESTION] Lures that makes certain animals more likely to spawn nearby.

### ISSUE THREAD

**Issue by BeardStroker** [capnkirok/animaniamod#65]
After traveling far and wide for hours looking for chickens I would love to see something like this implemented. I imagine it like a block you can place a mobs favourite food into, and after some time it will rarely spawn a matching animal somewhere nearby, at the cost of a large portion of the food. 

I am all for exploring to get a farm going or finding all the species, but sometimes the RNG gods need a helping hand. This would help a lot when certain mods are gated behind something like leather or a single feather (looking at you thaumcraft) :)

**Comment by Tschipp** [comment]
We have decided against this, as it seems out of scope for the mod.
