### ISSUE TITLE
Vanilla Animals Not Spawning - Even After config file edit

### ISSUE THREAD

**Issue by timeherald** [capnkirok/animaniamod#66]
### Actual Behavior
For some reason, even after editing both the server and the client config files for Animania to allow vanilla animals (i.e. B:replaceVanillaCows=false), the following animals still won't spawn in game from spawn eggs, or naturally in the wild: 

 Sheep
Chickens
Cows

Pigs and horses seem to spawn fine from vanilla eggs, and they appear in the wild.

Minecraft 1.12.2
Animania 1.12.2-1.4.8
Multiplayer server.

**Comment by capnkirok** [comment]
Hmm... you might have an old config, with old entries.

On 1.12, it should be:

 B:"Remove vanilla Chickens"=false
 B:"Remove vanilla Cows"=false
 B:"Remove vanilla Horses"=false
 B:"Remove vanilla Pigs"=false
 B:"Remove vanilla Rabbits"=false
 B:"Remove vanilla Sheep"=false

Basically,  I just tested and it works fine. You can also/check use the in-game Config editor to be sure.

Couple of other notes, 
- Vanilla eggs don't work if these are set to true
- Re-spawns of vanilla animals are very slow after the chunk has been generated
