### ISSUE TITLE
Animania and Ice and Fire mod

### ISSUE THREAD

**Issue by caiorasch** [capnkirok/animaniamod#68]
So, the mod Ice and Fire adds the creature Cockatrice that has a chance to spawn from rotten eggs, which in turn has a chance to spawn from a chicken in place of regular eggs. Since I play replacing the vanilla animals I wanted to know if there is any way for me to add a chance for Animania's chicken to lay these "rotten eggs" in the nests in place of regular ones.

**Comment by capnkirok** [comment]
Unfortunately, this is not possible. However, you could add this as a secondary drop from a chicken.
