### ISSUE TITLE
[MINOR ISSUE] Mules unobtainable with REPLACE_VANILLA_HORSES

### ISSUE THREAD

**Issue by LordDan1989** [capnkirok/animaniamod#69]
I have just come to the realization that Mules would be unobtainable with Animania's default Vanilla Replacement functionality. Whilst this isn't a huge deal I feel that this 'breaks' a vanilla mechanic and hope to see Mules obtainable without having to resort to having both Draft Horses and Vanilla horses available.

**Vanilla Mechanic**
Obtaining a Mule is done by crossbreeding a Horse and a Donkey

**Version**
I'm on 1.12.2, but this would of course affect versions right back to when Stallions were introduced I'd imagine.

**Comment by capnkirok** [comment]
You are correct. I can actually check if they're donkeys or mules and not remove. Can add.

**Comment by LordDan1989** [comment]
Actually, I'm not sure that'd work.

Having disabled all mobs from spawning except Draft, horse, donkey and mule, I can see that Donkey's do in fact spawn. The problem is that there are no Vanilla Horses to breed with Donkeys to create Mules. Mules do not spawn naturally in Vanilla MC, they must be bred from a Donkey and a Vanilla horse.

I'm not sure how difficult, or even if it is possible to allow the Stallions to breed with Donkeys to create the Mules, If that isn't doable or is far to much effort, perhaps adding Mules to Animania's Natural Spawn config would be a solution to having them at least obtainable out of the box?
