### ISSUE TITLE
[SUGGESTION] Unique markings on every animal

### ISSUE THREAD

**Issue by MooniePie** [capnkirok/animaniamod#70]
Perhaps there could be a set of markings that an animal has a certain chance of obtaining when it is spawned into the world. There may also be multiple of these unique markings on an animal, or none at all. With certain creatures, such as fowl, there is a very slim chance for them to have markings, since that is pretty rare in the real world. Markings could also be passed down from parent to child.

**Comment by capnkirok** [comment]
Nice suggestion. I think this goes with the genetics plan that has yet to be implemented (speed, size, strength, etc.)
