### ISSUE TITLE
Jeresey Cheese does not register as part of the foodCheese Ore dict

### ISSUE THREAD

**Issue by fullphaser** [capnkirok/animaniamod#72]
### Expected Behavior
animania:jersey_cheese_wedge should register as part of the foodCheese ore 

### Actual Behavior
It appears to be the only cheese that doesn't register in the oredictionary as part of the foodCheese ore 

### Steps to Reproduce
Looking at oredict values

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft: 1.12.2
Forge: 14.23.4.2705
Animania: 1.4.8 (1.4.7) 
Singleplayer 

### Screenshots encouraged
![2018-07-02_18 33 30](https://user-images.githubusercontent.com/15974903/42189488-7254fd3e-7e26-11e8-83ed-175b28cc72cd.png)
![2018-07-02_18 33 33](https://user-images.githubusercontent.com/15974903/42189489-7262d51c-7e26-11e8-83f8-80b07f028629.png)

**Comment by capnkirok** [comment]
Thanks. Fixed in next release.
