### ISSUE TITLE
No animals

### ISSUE THREAD

**Issue by WingedRizon** [capnkirok/animaniamod#73]
### Expected Behavior
Animals Spawning

### Actual Behavior
None what so ever, spawn eggs works

### Steps to Reproduce
We added the mod into resonant rise 4

### Version of Minecraft, version of Animania, Single Player or Server
1.10.2 and the corresponding release version

**Comment by capnkirok** [comment]
Was it a pre-existing world?

**Comment by capnkirok** [comment]
I'm not supporting 1.10 anymore. It should work anyway, this likely has to do with a pre-existing world.
