### ISSUE TITLE
Crash when putting seed on the floor for chickens.

### ISSUE THREAD

**Issue by darkshadow1809** [capnkirok/animaniamod#74]
### Expected Behavior
No crash when putting seed on the floor to feed chickens

### Actual Behavior
Crash when putting seed (at random)

### Steps to Reproduce
Put down enough seeds until it crashes.

### Version of Minecraft, version of Animania, Single Player or Server

1.12.2, Latest Animania, Client crash.
### Screenshots encouraged
(Non applicable)

https://paste.dimdev.org/ezanidufin.mccrash

Not sure if the error orginates from animania or WAWLA, so I just posted it on both to be sure.

**Comment by capnkirok** [comment]
This looks like a forge issue, though it should have been closed. I guess I could put a try catch around this.

Similar issue posted here:
https://github.com/Glitchfiend/BiomesOPlenty/issues/763

**Comment by capnkirok** [comment]
Ok, I've put in a try/catch. If WAILA fails to identify the seed, it will show as wheat seeds.

I can't replicate without duplicating your setup, so this is the next best option. Added in next release.
