### ISSUE TITLE
[Suggestion] Free mode for pets

### ISSUE THREAD

**Issue by BlueWither** [capnkirok/animaniamod#75]
Tamed mobs, like hamsters and hedgehogs should have free moving mode.

**Comment by capnkirok** [comment]
What do you mean by free moving mode? Can you add a description?

**Comment by Deshiba** [comment]
Currently there are 2 options. 
 1. Sit & Stay
 2. Follow the player.

There is no option to have the pet roam without it teleporting to the player. It would be fabulous to have an option where they Roam & Stay. This way we can have our little ferret pets roam our premise without it constantly falling off the ledge we are building.

**Comment by capnkirok** [comment]
Actually.... I made an update in 1.5:
- Tamed animals no longer teleport to you (configurable, default is off).

Basically, they follow you around if you are nearby, but if you go outside of the radius (which is 144 blocks... kind of high, now that I think about it).

I can make the distance configurable, or even turn completely off. Let me know...

Code, for reference:
https://github.com/capnkirok/animaniamod/blob/1.12/src/main/java/com/animania/common/entities/generic/ai/EntityAIFollowOwner.java

**Comment by Tschipp** [comment]
Closing this
