### ISSUE TITLE
Animania mobs auto-dismount when riding another entity, messes up inter-mod interactions

### ISSUE THREAD

**Issue by Alex-the-666** [capnkirok/animaniamod#76]
### Expected Behavior
Animania mobs remain riding whatever mob that they mount

### Actual Behavior
Animania mobs dismount mobs they ride, sometimes only on client/server side

### Steps to Reproduce
->install Ice and Fire
-> dragon attacks animania mob which "shake" attack, animania mob jumps off dragon without being hurt
### Version of Minecraft, version of Animania, Single Player or Server
-> all versions, 1.12.2

**Comment by capnkirok** [comment]
Hmm.... I don't have anything special here regarding what mobs Aninania mobs ride.... except Hamsters, Ferrets, and Hedgehogs... but that's only for players. Will have to dive into this one more.

**Comment by capnkirok** [comment]
@Alex-the-666 I was not able to reproduce this (but I will do some more testing). But I'm guessing it's my custom AI. 

I can put in exceptions in my AI to check for IsRiding(). Will report back.

**Comment by Tschipp** [comment]
Found it while working on #99. Fixed in next release
