### ISSUE TITLE
Thirsty cows

### ISSUE THREAD

**Issue by mxnmnm** [capnkirok/animaniamod#78]
### Expected Behavior
Cows to drink water after being milked

### Actual Behavior
Cows do not drink water

### Steps to Reproduce

Milk cow after it gave birth
Try to milk later on with water sources/troughs nearby

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2
1.4.8
Singleplayer and lan world

### Screenshots encouraged

https://imgur.com/a/0SL6xaX

**Comment by capnkirok** [comment]
Already noted and fixed in next release.
