### ISSUE TITLE
Sheep ignore the woolRegrowthTimer config 

### ISSUE THREAD

**Issue by Deshiba** [capnkirok/animaniamod#8]
### Expected Behavior
With the standard config setting of 8000 ticks I'd expect sheep to not regrow their wool for 6 minutes 40 seconds

### Actual Behavior
When you shear sheep they regrow wool the second they eat grass like they do in vanilla

### Steps to Reproduce
*Start a fresh world
*Spawn in a bunch of sheep
*Shear the sheep
*watch them for a bit, they will regrow wool way before 30 seconds have even passed

### Version of Minecraft, version of Animania, Single Player or Server
I've tested this on both a server and single player world
Minecraft version: 1.12.2
Animania version: 1.4.6
Crafstudio version: 1.0.0
Decocraft version: 2.5.4
JEI version: 4.8.5.147
Hwyala version: 1.8.23
Appleskin: 1.0.9

**Comment by capnkirok** [comment]
Ahhh... another gift of extending vanilla animals. Thank you for the precise description.

**Comment by Deshiba** [comment]
You are very welcome, just trying to Tschipp in. *chuckles*
