### ISSUE TITLE
Sheep run away in their sleeping pose when perceiving a threat

### ISSUE THREAD

**Issue by angelnc1989** [capnkirok/animaniamod#80]
### Expected Behavior
Sheep stand up and run away when a threat is near them.

### Actual Behavior
Sheep stay in their sleeping pose and run away.

### Steps to Reproduce

- set the game to nighttime
- spawn in an Animania sheep
- spawn in a wolf next to the sheep

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12.2
Animania 1.5.0
Single Player

### Screenshots encouraged
https://gfycat.com/gifs/detail/HarmlessOrdinaryFairybluebird

**Comment by capnkirok** [comment]
Thanks. Fixed in next release.
