### ISSUE TITLE
New Update is running slower due to AI Tick Countdown Timer

### ISSUE THREAD

**Issue by Peach774** [capnkirok/animaniamod#83]
### Expected Behavior
Game should run better after updating

### Actual Behavior
Game runs much worse

### Steps to Reproduce
Run the game with the default tick rate of 100

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2
1.5.0
SSP and SMP and LAN

This can be fixed by increasing the tick time to 3600, 3 minutes instead of 5 seconds.

**Comment by capnkirok** [comment]
Well, it can't run slower due to the timer. Previous timer was set at 60. So it's something else. Can you share your modlist?

**Comment by Peach774** [comment]
I can share my mod list, but it definitely was running worse, because changing the tick rate to 3600 fixed it.
It's really late here, so the best I can do right now is link to the modpack. I'll update with an modlist tomorrow.

Here is the version where it happens: https://minecraft.curseforge.com/projects/smartcraft/files/2598177

**Comment by Peach774** [comment]
I also disabled sleep - maybe the two are related?

**Comment by capnkirok** [comment]
Could be Sleep, yes. Or something else that I added causing an issue. But performance is better on my side, so need to dig deeper.

**Comment by capnkirok** [comment]
Hey @Peach774 try the latest version 1.5.1.1 (when it is posted)
