### ISSUE TITLE
Server hamster/dragon crash

### ISSUE THREAD

**Issue by mxnmnm** [capnkirok/animaniamod#84]
### Expected Behavior

Not crashing when hamsters panic

### Actual Behavior

Crashing when hamsters panic from ice and fire dragons

### Steps to Reproduce

spawn dragon from ice and fire and spawn hamster

### Version of Minecraft, version of Animania, Single Player or Server

1.12.2
1.5.0
Server crash

### Screenshots encouraged

https://pastebin.com/WVxNL6cn

**Comment by mxnmnm** [comment]
I think a quick hotfix is needed for this...

**Comment by capnkirok** [comment]
Yup, thanks.
