### ISSUE TITLE
Continuous server spam finding bed

### ISSUE THREAD

**Issue by joklbash** [capnkirok/animaniamod#86]
### Expected Behavior
No server spam.

### Actual Behavior
So much spam that the logs grow out of control quickly. Constant logging of:
[Server thread/INFO] [STDOUT]: [com.animania.common.entities.cows.ai.EntityAISleep:func_75250_a:53]: finding bed

### Steps to Reproduce
Updated to 1.5.1 from 1.4.8 and visited our zoo, which is full of animals.

### Version of Minecraft, version of Animania, Single Player or Server
MC 1.12.2
Animania 1.5.1
Forge 14.23.4.2739
Server

**Comment by joklbash** [comment]
Disabling sleep saved me from having to revert back to a prior version for now. With it enabled and plenty of animals in the area, the server logs were growing out of control.

**Comment by capnkirok** [comment]
Thanks. Will have to hotfix this.

**Comment by capnkirok** [comment]
Fixed in 1.5.1.1, along with more perf. improvements
