### ISSUE TITLE
Tiller doesn't remove double-tall grass

### ISSUE THREAD

**Issue by laserlemons** [capnkirok/animaniamod#87]
### Expected Behavior
Since the tiller removes tall grass it should work for double tall grass too.

### Actual Behavior
Right now the double tall grass stays planted above the tilled soil.

### Steps to Reproduce
Use tiller on grass/dirt with double tall grass planted on it.

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2, 1.5.1.1, 14.23.4.2705, single player

**Comment by capnkirok** [comment]
Yeah, will fix. Thanks!

**Comment by mser7** [comment]
What about fern and double fern blocks?

**Comment by capnkirok** [comment]
Ok, this is fixed in 1.5.2
