### ISSUE TITLE
Update message present in latest version, links to older version

### ISSUE THREAD

**Issue by laserlemons** [capnkirok/animaniamod#88]
### Expected Behavior
It shouldn't give you a message if you're using the latest version.

### Actual Behavior
It says "Animania version 1.5.0 is available" on login.

### Steps to Reproduce
Log into world.

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2, 1.5.1.1, 14.23.4.2705, single player

**Comment by capnkirok** [comment]
Fixed!
