### ISSUE TITLE
Can't roast raw peacock

### ISSUE THREAD

**Issue by DryTaste** [capnkirok/animaniamod#89]
### Expected Behavior
Raw peacock can be cooked in a furnace.

### Actual Behavior
Raw peacock can't be cooked in a furnace.

### Steps to Reproduce
Put raw peacock in a furnace with some coal.

### Version of Minecraft, version of Animania, Single Player or Server
MC 1.12.2 FORGE 2749
Animania 1.5.1.1
Multiplayer

**Comment by capnkirok** [comment]
Thanks for the report. These are added in the next release.
