### ISSUE TITLE
Server crash after someone tried to catch an cute hedgehog with an golden lasso from extra utilities

### ISSUE THREAD

**Issue by TheRealDadbeard** [capnkirok/animaniamod#91]
Animania 1.5.1.1
Minecraft 1.12.2
Forge 2750

Crashlog: https://pastebin.com/dh6B1H8d

**Comment by capnkirok** [comment]
Ahhh, yes. A non-entity entity. Gotta love those. Will need to adjust for compat.

**Comment by capnkirok** [comment]
Actually this is a straight-up bug. Need to do a hotfix. Also see #93

**Comment by Tschipp** [comment]
Closing this duplicate
