### ISSUE TITLE
No Horse Cart/Covered Wagon

### ISSUE THREAD

**Issue by croxiin** [capnkirok/animaniamod#92]
Everything is current (1.12.2)
There's not even a wheel, and I'm just wondering if it's a bug, or if they were removed and I just can't find where it says they have been. I just need to gather some animals for a farm and riding a horse with a cart and an animal seems faster than leading an animal and my horse back to the farm, especially since the lead will break if the animal gets stuck or lags too far behind.

**Comment by capnkirok** [comment]
There is a config for removing these items. Is that possilbe that "Disable cart and wagon is set to false?"

**Comment by croxiin** [comment]
My apologies, it turns out every mod except Animania was updated. I had the 1.12.1 version, which does not have the horse cart and covered wagon.
