### ISSUE TITLE
Suggestion: config for "actual" spawn eggs

### ISSUE THREAD

**Issue by Partonetrain** [capnkirok/animaniamod#94]
Some mods (like [Thermal Expansion](https://github.com/CoFH/Feedback/issues/1176)) determine what entities are non-boss mobs by getting what entities have a valid (vanilla) spawn egg. Since Animania has custom spawn eggs, all Animania mobs are not seen by Thermal Expansion. 

I suspect you could just register the egg and not show it in the creative inventory, if the option is enabled.

**Comment by Tschipp** [comment]
It’s not smart to determine what entities are bosses based on if they have a spawnegg or not. By that logic, arrows, potions, minecarts, falling sand and many more would be considered bosses (unless you make exceptions for everything).

The reason the morbs don’t work, is that TE needs to get the mob colors (from the spawnegg) to determine the colors of the morb. Our animals also have registered colors, so I guess we could make a config for it.

**Comment by Partonetrain** [comment]
Makes sense. The part about non-boss entities is probably misinformation on my part. I could’ve sworn I read it on the CoFH wiki...

Not that it matters. I’m glad you are considering the solution.

**Comment by Tschipp** [comment]
While we won't support vanilla spawn eggs, we now will support Morbs in the next release.
