### ISSUE TITLE
[Suggestion] Dyeing sheep 

### ISSUE THREAD

**Issue by beeshroom** [capnkirok/animaniamod#98]
I know this mod's based on realistic farming of animals, but it'd be really great if dyeable sheep, even if only one breed of ewe was capable of being dyed, made it into this mod someday.

**Comment by Deshiba** [comment]
Hmm, Purp confirmed that dyable sheep were going to be added in https://github.com/capnkirok/animania/issues/351.

But 1.4 release has come and gone and this isn't in afaik.

**Comment by capnkirok** [comment]
You are right, I let this slip. Let's keep this up as a reminder.
