### ISSUE TITLE
Animals starve in their sleep

### ISSUE THREAD

**Issue by notfood** [capnkirok/animaniamod#99]
### Expected Behavior
Animals should wake up and seek food/water if they're dying.

### Actual Behavior
Even though the animal has water and food nearby in a through or any they will go to sleep and starve to death.

### Steps to Reproduce
Put food/water through, the animal and wait...

### Version of Minecraft, version of Animania, Single Player or Server
```ts
Minecraft 1.12.2
forge 1.12.2-14.23.4.2756
animania 1.12.2-1.5.1.1
``` 
Dedicated server

### Screenshots encouraged
![image](https://user-images.githubusercontent.com/5370107/44700366-6399e080-aa4e-11e8-8dd2-997c106f2d65.png)

**Comment by capnkirok** [comment]
Hmm.... I was pretty sure I disabled starving during sleep. Will check again, thanks.

**Comment by Tschipp** [comment]
Fixed in next release
